### ISSUE TITLE
Is using "issues" for discussion an issue? 

### ISSUE THREAD

**Issue by padeler** [devstaff-crete/DevStaff-Heraklion#1]
Lets try it and see if it works.

**Comment by gsaslis** [comment]
no, come on... it'll work great.. 

i'm sure @sonaht will agree :P

**Comment by sonaht** [comment]
I am happy with this, using issues to discuss an issue is not an issue... for me ;-)

**Comment by gsaslis** [comment]
i think we can safely close this then.. anyone can issue a PR if they want to see this policy changed

**Comment by padeler** [comment]
ok then!
