### ISSUE TITLE
Git Version Control System

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#10]

**Comment by gsaslis** [comment]
:+1: great idea!

**Comment by padeler** [comment]
:+1:

**Comment by sonaht** [comment]
:+1:

**Comment by gsaslis** [comment]
unanimous agreement. closing this, as it's already been agreed and added to the README.md

**Comment by zakkak** [comment]
The following post seems interesting: http://www.artificialworlds.net/blog/2014/07/15/what-git-server-should-i-use/
