### ISSUE TITLE
Orthopaedic problems associated with Development - Good practices to avoid them

### ISSUE THREAD

**Issue by npapnet** [devstaff-crete/DevStaff-Heraklion#101]
I am sure a lot of us spend over many hours a day in front of a computer. As a result a lot of people at some point might have problems associated with poor posture or others like:
- repetitive strain injury (rsi)
- headaches from bad posture
- frozen shoulder (rotator cuff impingement)
- carpal syndrome.

Has anyone been through that and has gathered some experience/good practices that wants to share with others?

**Comment by zakkak** [comment]
Have not suffered from any of the above, but I can give some hints on how to avoid RSI since I lately I have been involved in discussions about it.

I can mostly show people how to improve the way they use their keyboard and avoid using the mouse (you can use a trackball or a touchpad instead, if you really need it).

DISCLAIMER: I am not a doctor nor an expert, I have just gathered a few techniques from discussions on the topic.

**Comment by eirinikp** [comment]
yoga or pilates can help

**Comment by npapnet** [comment]
@eirinikp 
Also taichi would be good for rehabilitation, or swimming etc. However all of the above assume time or inclination to take up a sport during non-development time. 
 I am more interested in things that can be done *during* work hours (if there is such a thing), either from good posture pointers and/or stretching exercises during short breaks of a scrum session. :-)

**Comment by eirinikp** [comment]
I know you meant during work hours, but I mentioned them because these activities will improve the posture you will keep on working hours. 
Anyway since you don't want anything related to physical exercise, I hope other people will be more helpful

**Comment by zakkak** [comment]
You can also try replacing your chair with an exercise ball (at least for a part of the day, I can't imagine sitting on it all day):
http://www.gearfire.net/10-reasons-to-use-an-exercise-ball-as-your-chair/

Or even try using a standing desk:
http://lifehacker.com/five-best-standing-desks-1528244287

**Comment by npapnet** [comment]
@eirinikp 
I am afraid I've given the impression that I am a couch potato "Anyway since you don't want anything related to physical exercise,".
Its not that I don't want anything to do with exercises (every morning I spent about half an hour in breathing exercises and sit ups). Also, I prefer exercises like judo or aikido (more suited to my body type and personality) or dancing, which sometimes are accident prone, when I have time to exercise. 
And that is the main issue I am facing: Lack of time.  For the past three months I had to work from 9 till 6 in front of a computer, then from 6-9 giving classes standing up, and then from 10-12 I had to prepare the classes for next day over a PC or a table. So it was a bit uneven, half an hour of warm up and 12 to 14 hours of working in front of a PC or a table. (Its a good thing that my wife showed such understanding :-) ). 
  So sometimes its not a matter of wanting but having time/energy to do something outside working hours. 
  Also, sometimes injuries happen (as I get older things aren't any better), and in the process of protecting the injured member (e.g. shoulder) you develop guarding strategies which over-stress another member (e.g. the other shoulder). If you don't know how to protect yourself, during most of the day, I feel it will be a battle doomed to be lost.

**Comment by eirinikp** [comment]
Hehe I OK I completelly understand! :) I hope you get better!!

**Comment by sstauross** [comment]
:+1:

**Comment by gsaslis** [comment]
my right wrist was in a lot of pain up till a few years back.

This keyboard really **solved** it for me:
https://www.microsoft.com/accessories/en-us/products/keyboards/natural-ergonomic-keyboard-4000/b2m-00012
(Yes, I am recommending a Microsoft product here)

For the mouse, the solution was a mouse pad with wrist support:
http://www.bestprice.gr/search?q=Mouse%20pad%20gel

I also have a badass chair, as well as an
ingenious-but-yet-unrecognized-as-such idea (which i am happy to share
under cc) for desk chair designers to help office workers maintain their
posture.

Disclaimer: i am no doctor either, bla bla bla, these (only) worked for me,
but i am in no pain any more, so I thought I'd share.  ; )



-- 
Yorgos Saslis
Software Engineer

**Comment by Archimidis** [comment]
@gsaslis I remember that chair! I'm interested to learn more :P

**Comment by webdevgr** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by sbehnsen** [comment]
👍

**Comment by sugarenia** [comment]
👍

**Comment by msti** [comment]
:+1:

**Comment by xilourgos** [comment]
👍

**Comment by maninak** [comment]
:+1:

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
