### ISSUE TITLE
Agile/Scrum

### ISSUE THREAD

**Issue by skananitos** [devstaff-crete/DevStaff-Heraklion#103]
**Scrum** is an iterative and incremental agile software development methodology for managing product development. :speaker:

**Comment by padeler** [comment]
Nice topic. :+1:

**Comment by sstauross** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by sonaht** [comment]
:+1:

@skananitos will you be willing to actual host this as well ?

Agile software development is a great subject...

**Comment by msti** [comment]
:+1:

**Comment by skananitos** [comment]
@sonaht I was planning to make a presentation-overview of Scrum. Please feel free to contribute with any extra resource you find interesting! :smile:

**Comment by sonaht** [comment]
@skananitos if that's the case, pls add a :loud_sound:  icon in the original post to indicate ability and availability to present.

ty

**Comment by kritsot** [comment]
:+1:

**Comment by gsaslis** [comment]
I obviously have a lot to share on this topic (i'm hosting agileCrete.org), so :speaker:

**Comment by gsaslis** [comment]
P.S: new website for http://agilecrete.org

**Comment by Archimidis** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by AndronikiEnartia** [comment]
:+1:

**Comment by Hotshuk** [comment]
:+1:
I'll can also contribute as a speaker on this topic :speaker:

**Comment by gzografa** [comment]
:+1:

**Comment by gmanou** [comment]
:+1:

**Comment by gsaslis** [comment]
in the beerup last night @kabitakis suggested we have a small hack session for this topic, a little ahead of [#AgileCrete](http://agilecrete.org) 

How about setting this up in the last week of June, to give us time to prepare / read more and reconvene for AgileCrete in late July?

**Comment by webdevgr** [comment]
:+1:

**Comment by gsaslis** [comment]
Just noticed that @kabitakis opened a new issue ( #133 ), and it hasn't been mentioned here, so if any of you guys who were interested about Agile Software Development wanna join us, check it out! (it's TOMORROW)

**Comment by skananitos** [comment]
Hi guys! I hope you're fine! I'm in Berlin right now and I would like just to mention that Agile Software Development is a must for all the start-up companies here! So, yeap, go for it!

**Comment by gsaslis** [comment]
Is anybody still interested in this, after #AgileCrete,  or should we just close it ?

**Comment by msti** [comment]
I am still interested.
Did everybody here attended AgileCrete?

**Comment by sugarenia** [comment]
👍

**Comment by sifalios** [comment]
👍

**Comment by svelon** [comment]
👍

**Comment by eirinikp** [comment]
:+1:

**Comment by xilourgos** [comment]
👍

**Comment by iovar** [comment]
👍

**Comment by maninak** [comment]
:+1:

**Comment by svelon** [comment]
👍

**Comment by pappaschris** [comment]
👍

**Comment by gsaslis** [comment]
this has been scheduled for May 2017, so closing
