### ISSUE TITLE
Working for the EU

### ISSUE THREAD

**Issue by skananitos** [devstaff-crete/DevStaff-Heraklion#107]
- Agencies and other EU bodies
- Why EU Careers?
- Job opportunities

...and more :speaker:

**Comment by sstauross** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by Pepemakis** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:

**Comment by Pepemakis** [comment]
👍

**Comment by svelon** [comment]
:+1:

**Comment by gvre** [comment]
:+1:

**Comment by marinaG0** [comment]
👍

**Comment by skananitos** [comment]
Πλέον είμαι εκτος Ελλάδoς και δε μπορώ να κάνω offline παρουσίαση αυτού του topic. Αν ενδιαφέρεστε μπορώ ίσως να μιλήσω μέσω Skype, αλλιώς μπορείτε να το διαγράψετε .

**Comment by skananitos** [comment]
Hey guys, fyi: https://www.ecb.europa.eu/careers/vacancies/html/vacancydetails.en.html?id=005056853E201ED6A5A66D8214C6DBB7

Let me know if you need any info, help etc.

**Comment by msti** [comment]
👍

**Comment by agougousis** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by ManosGEM** [comment]
👍

**Comment by skananitos** [comment]
Hi ppl, check this https://www.ecb.europa.eu/careers/vacancies/html/vacancydetails.en.html?id=005056853E201ED7B28AE121CDEF5A38

Let me know if you need any help.

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
