### ISSUE TITLE
[Hack Session] High availabilty web stack using Docker and Rancher

### ISSUE THREAD

**Issue by msti** [devstaff-crete/DevStaff-Heraklion#111]
[Rancher](http://rancher.com/) is a platform that allows a user to deploy and manage docker containers through an intuitive user interface.

For the last few days I have been playing with Rancher (thanks @DaKnOb for the help) and the outcome is very positive.

My aim was (is) to evaluate Rancher for a high availability/performance web stack.

In this session we will see what Rancher can do and **quickly** build a high availability system.

If you find this session interesting, then please join!

You are more than welcome to join if you have experience in high performance/availability setups.

**Comment by gvre** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1: -- Rancher is v1.0.0! Great features and stability improvements btw.

**Comment by maounis** [comment]
Well great topic @msti 

:+1:

**Comment by gsaslis** [comment]
Count me in :thumbsup:

On Friday, 1 April 2016, Frank Maounis <notifications@github.com> wrote:

> Well great topic @msti <https://github.com/msti>
>
> [image: :+1:]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/devstaff-crete/DevStaff-Heraklion/issues/111#issuecomment-204535060>
>


-- 
-- 
Yorgos Saslis
Software Engineer

**Comment by Archimidis** [comment]
:thumbsup:

**Comment by sonaht** [comment]
goes without saying :+1:

**Comment by sonaht** [comment]
@msti any progress on this ?

is still an objective for you ?

**Comment by filipslavik** [comment]
@msti very interesting topic, I would be very glad to join.

**Comment by msti** [comment]
@sonaht Yes it is. Sorry guys, I have been l time deprived lately. 
I will be out of town some time in the next couple of weeks, so I intend to schedule it in October.

**Comment by agougousis** [comment]
@msti Is there any future in that session?  :-)  :+1:

**Comment by msti** [comment]
Yes, there is!
How would everyone feel about scheduling it someday bewteen 16-20 January?

**Comment by agougousis** [comment]
Μια χαρά μου φαίνεται.

**Comment by agougousis** [comment]
Έχουμε καμιά εξέλιξη; :-)

**Comment by sonaht** [comment]
@msti long time no see/hear etc. R u still interested in doing this ?

**Comment by msti** [comment]
Yeah, took too long and the interest has shifted. Closing....
