### ISSUE TITLE
1st Anniversary Meetup on beach

### ISSUE THREAD

**Issue by webdevgr** [devstaff-crete/DevStaff-Heraklion#117]
I suggest the 1st Anniversary Meetup (July 2016) to become on beach

**Comment by sonaht** [comment]
I am all for it, whatever the subject will be...

:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by DaKnOb** [comment]
👍 Although I may not be able to attend it

**Comment by Archimidis** [comment]
👍

**Comment by gsaslis** [comment]
What a great idea!

**Comment by estavrak** [comment]
:+1: 
but what about the projector, seating, etc?

**Comment by gsaslis** [comment]
"seating" !?

...

on the beach ?

...

...

really ?

-- 
Yorgos Saslis
Software Engineer

**Comment by sonaht** [comment]
We did actually do this:

http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/events/233583345/

GREAT
