### ISSUE TITLE
Beta Testing Section (Mobile Apps & Websites)

### ISSUE THREAD

**Issue by webdevgr** [devstaff-crete/DevStaff-Heraklion#118]
Can we create a section for beta testing (Mobile Apps & Websites)?

**Comment by Archimidis** [comment]
Can you clarify what do you mean with bet testing? E.g. having actual users test the software?

**Comment by webdevgr** [comment]
If you time why not :) or just a quick review. 
Four or more eyes are better than two :)

**Comment by kabitakis** [comment]
I agree with the idea. I'm just trying to visualise what this "section" would be. I think the easiest way to do it is to create a new issue including [Review] or sth similar in the title, asking people to review your app. How would you describe that "section" @webdevgr ?

**Comment by DaKnOb** [comment]
Maybe something like the OSS Projects section?

**Comment by webdevgr** [comment]
I think "section" is wrong word on github :) I meant "repository" in which we can create a new issue about our website or mobile app and all the comments on each issue to concern only the specific issue

**Comment by msti** [comment]
Updating a page under Devstaff every time someone requires some quick feedback for his app is not practical. 
Creating issues with a 'Review' tag as @kabitakis proposes is more appropriate. The issue can contain some instructions or link to an external repo.

**Comment by sonaht** [comment]
@webdevgr maybe we should try this (if you are still interested) as a slack channel, where pips can request/exchange etc. What do you think ?

**Comment by sonaht** [comment]
A very old one, closing it
