### ISSUE TITLE
Social Engineering & Physical Security

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#119]
Social Engineering is the art of convincing other people to perform certain tasks that may benefit you. That includes receiving discounts, getting free stuff, obtaining additional access, etc.

Physical Security is an area of Security which includes things like entering offices / buildings without permission, accessing unauthorized areas, dumpster diving, tailgating, etc. 

When these two techniques are combined, an individual or group can gain access within a trusted environment like an office space or a server room and perform malicious things like infecting hosts, installing equipment, exfiltrating information, etc. 

Some companies may be interested in cybersecurity, implement firewalls, provision low privilege accounts, etc. but very few are actually concerned about physical security. 

If you're interested in learning more about this, comment a `:+1:` ( 👍 ) and if you have experience in this topic comment a `:speaker:` ( 🔈 ).

**Comment by DaKnOb** [comment]
🔈 👍

**Comment by DaKnOb** [comment]
https://www.youtube.com/watch?v=pL9q2lOZ1Fw

**Comment by maounis** [comment]
Very interesting topic :)

👍

**Comment by gvre** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1

**Comment by zakkak** [comment]
:+1:

**Comment by DaKnOb** [comment]
@webdevgr We need one more `:` :P

**Comment by konchalas** [comment]
:+1:

**Comment by Archimidis** [comment]
👍

**Comment by eirinikp** [comment]
:+1:

**Comment by ariel2023** [comment]
👍

**Comment by estavrak** [comment]
:+1: 
:speaker:

**Comment by gsaslis** [comment]
![img_6023](https://cloud.githubusercontent.com/assets/2420882/15862953/ffe63334-2cd9-11e6-8154-931f715c2d1f.JPG)

Count the cameras in this photo... : O

**Comment by flouris** [comment]
:+1:

**Comment by msti** [comment]
👍

**Comment by ManosGEM** [comment]
👍

**Comment by nikos445** [comment]
👍

**Comment by markop** [comment]
:+1:

**Comment by maninak** [comment]
:+1:

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
