### ISSUE TITLE
Change the voting process

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#120]
Now that github has added support for "reactions" (https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments), maybe we should change the voting process to use reactions instead of `:+1:` comments.  This way we will also stop getting notification e-mails for every vote and only get notified for more important thinks, like new topics.

Related API (not stable yet): https://developer.github.com/v3/reactions/

**Comment by gsaslis** [comment]
Fully agree. 

Speaking to a few ppl, this was a common pain point, what with all the email notifications mess every time votes were coming in...

Would you care to open a PR for this?

**Comment by zakkak** [comment]
I made a PR for the readme changes #121.  Unfortunately I don't have time to change the analytics app as well.

**Comment by zakkak** [comment]
Opened https://github.com/kabitakis/github-analytics/issues/20 as well.

**Comment by zakkak** [comment]
Reasons we want the new way are:

1. Reactions are cleaner than comments
2. Reactions do not SPAM us
3. One can easily see the number of votes in a topic directly on github
4. more... ?

Are there any reasons we don't want reactions over comments?

At the moment the only I can think of is that the API is not stable.

**Comment by zakkak** [comment]
I just noticed that comments with just a :+1: are automatically transformed to reactions in gitlab. Maybe this is coming to github as well (so ignore my next comment which is a test for this ;) ).

**Comment by zakkak** [comment]
:+1:

**Comment by zakkak** [comment]
It seems it's not here yet...

**Comment by zakkak** [comment]
I just noticed that many people (including me) added `👍` instead of `:+1` on #161 (and I have no idea about other issues). 
These two are not the same and it is very easy to place the wrong one (the emoji) by just pressing enter on the auto-completion.
The problem with the emoji is that it is not recognized by the analytics app (I count 6 upvotes by the analytics shows only 3).

I believe it is time to move to reactions. I can even put some time to hack the analytics app to work with them.

**Comment by DaKnOb** [comment]
@zakkak The Python Analytics uses reactions only and the NodeJS Analytics uses comments only. It's up to you to make one of them use both.. :-)

Demo NodeJS: https://analytics.devstaff.gr/
Demo Python: https://analytics.devstaff.daknob.net/

**Comment by zakkak** [comment]
So, if we already have something working for reactions why don't we just change the way of voting?

@DaKnOb is your py-analytics open sourced?

\@all what do you think?

**Comment by gsaslis** [comment]
Interestingly, reactions are not supported on the github mobile website!?!?!?

**Comment by zakkak** [comment]
!?!?!?! Indeed. That's weird...

**Comment by sonaht** [comment]
@zakkak Initially it is best to raise this in the general channel of slack, so that all interested parties can take part in the discussion. As a quick response I would say it is very hard to change everyones way of doing things and "force" one way over another, instead of  just fixing the software to do both. Surely it will be a bit slower to double check  `if voted vs if reacted etc` but that was never an issue.

There is an open invitation for people to take this on and continue the code from where it was left.

Thats my 2 cents for now.

**Comment by msti** [comment]
It is strange that reactions do not work for mobile. Is it out of beta?

We will need a 'transition' period during which both reactions & votes are counted. As soon as the s/w is updated, we can use reactions alone.

**Comment by zakkak** [comment]
So how does this work currently? Does someone go issue by issue and count them manually?

Currently the software is broken even for our current voting scheme.
https://analytics.devstaff.gr/ only counts `:+1:` and not `👍` emojis.
https://analytics.devstaff.daknob.net/ counts only reactions.

They way I see it, we have the following options, each with it's 👍s and 👎s

1. Leave everything /as is/
    👍: we are used to it
    👎: it is *broken* since it does not work with emojis and many of us forget about it
2. Fix https://analytics.devstaff.gr/ to work reliably for our current scheme
    👍: we are used to it
    👎: continue receiving spam at each vote and add noise to the discussion about each topic
3. Strictly dump the old voting scheme and move to using reactions
    👍: https://analytics.devstaff.daknob.net/ is working so we have the software
    👎: we need to change a /habit/ and we can't vote from the mobile version of the github website
4. Fix (some) software to count both `:+1:`, `👍` emojis, and reactions and gradually move over to reactions
    👍: everyone is happy and is the safest/most stable way to do it
    👎: someone needs to hack the software

@sonaht I believe the whole discussion should be documented with all the opinions here on github, rather than having to scroll through slack.  Slack is for chatting not for resolving issues IMO. I will just leave a pointer there ;)

**Comment by sonaht** [comment]
My comment ref the slack goes solely to this: `why don't we just change the way of voting`

In order to change the voting system, either we put it up globally as a case of voting on voting or we discuss it on an org meetup in order to decide. It was brought up before and it was put forward in order to find people (volunteers) to tackle the coding issue.

Additionally slack now has threads, so a conversation thread on the matter or even a dedicated channel will not be out of place, but then again github is absolutely fine as well.

Point is that people need to get involved and express an opinion on the matter only if they are informed!!!

**Comment by zakkak** [comment]
I submitted a PR (https://github.com/kabitakis/github-analytics/pull/21) to fix https://analytics.devstaff.gr for the time being

**Comment by zakkak** [comment]
I also implemented the reactions counting (https://github.com/zakkak/github-analytics/tree/search-reactions). After @kabitakis pulls https://github.com/kabitakis/github-analytics/pull/21 I will create a new PR for it.

So, at this point I believe we can go on with the fourth choice:
> Fix (some) software to count both :+1:, 👍 emojis, and reactions and gradually move over to reactions

**Comment by gsaslis** [comment]
@zakkak - you rock!!! \m/

**Comment by gsaslis** [comment]
@zakkak do you think we can close this?

**Comment by irinikp** [comment]
Reactions are now supported in [https://analytics.devstaff.gr](https://analytics.devstaff.gr)

**Comment by kabitakis** [comment]
See https://github.com/kabitakis/github-analytics/issues/20 for more on this one.

@zakkak I've just read your comment. Sorry I missed it earlier :-\

**Comment by zakkak** [comment]
@kabitakis I also forgot about it ;) no worries.

The patch can be found [here](https://github.com/zakkak/github-analytics/commit/fbc6098d56e1708923d0287836769455cf39bb63), in case you need to merge it with @irinikp's

**Comment by kabitakis** [comment]
Thanks @zakkak!

Ok all, can you check the current functionality and approve the improvements? Comment on this issue if you APPROVE closing this issue.

**Comment by zakkak** [comment]
Closing since we have both reactions and comments working in https://analytics.devstaff.gr
