### ISSUE TITLE
DIY Quadcopters / Multicopters / Drones

### ISSUE THREAD

**Issue by padeler** [devstaff-crete/DevStaff-Heraklion#122]
This is not directly related with developers but I guess some might be interested so:

**What is needed to create a flying machine?**
- hardware parts and where to get them (a big issue for people in Greece)
- software. Lots of open source code out there, still lots of stuff to implement
- radios 
- basic soldering/crafting skills  
- money (but not as expensive as you may think)
- time (getting started is more or less a weekend project)

**Cool stuff to do with your flying machine:**
- Aerial photography
- FPV and drone racing (yeah!)
- autonomous flight
- ...the sky is the limit

I built my first DIY quad a few weeks ago and i got hooked, but it looks like there are not many people in the city working on such projects or I just don't know about them. I guess this could change :) 

Ideas for the hack session:
- an intro into what is needed and how to get started (see above)
- build a multicopter from scratch 
- heraklion drone racing league :)
- autonomous flight software projects and ideas
- ...

**Comment by zakkak** [comment]
:+1:

**Comment by padeler** [comment]
Hey @zakkak, what do you think about the hack-session? Do you have any experience with multicopters or want to know more about them?

**Comment by mikedi** [comment]
:+1:

**Comment by sonaht** [comment]
:+1: all in....

https://www.reddit.com/r/gadgets/comments/284kmj/game_of_drones_fight_club_for_quadcopters/

many many likessssss

**Comment by padeler** [comment]
@sonaht  to termatises! pros to paron ftiaxno ena fpv setup gia to quad mou alla ama psithi kosmos gia agones eimai panta mesa :)

**Comment by msti** [comment]
👍

**Comment by sonaht** [comment]
@padeler eimai poromenos xronia apo agglia me to robot wars (https://en.wikipedia.org/wiki/Robot_Wars_(TV_series) )

Irthe i ora gia to drone wars Crete-GR !!!

Ego mesa gi ahack session kai group kai fights or just flying around

**Comment by msti** [comment]
@sonaht  Robot wars, τι μου θύμισες! Το έβλεπα και εγώ φανατικά.
Πάρε εδώ ιδέα για drone wars: http://www.telegraph.co.uk/technology/2016/01/21/tokyo-police-are-using-drones-with-nets-to-catch-other-drones/

**Comment by maounis** [comment]
👍 

Έχω ένα TBS Discovery έτοιμο για πτήση :)

**Comment by sstauross** [comment]
👍

**Comment by padeler** [comment]
@maounis auto einai ena akrivo paixnidaki nice! Gia to hacksession eixa sto mialo mou perisotero DIY kai h/w pou kratane to kostos arketa xamila, gia na min to klais poli otan arxisis ta drone wars me ton @sonaht  :)

**Comment by sonaht** [comment]
ahahahaha ... siga siga tha ftasoume kai sta drone wars...ase pou eida fpv races tora kai ti na po ... !!!

**Comment by padeler** [comment]
@sonaht tha sou deikso fpv live molis mou erthei h epomeni paragelia mou (kai vro xrono na katso na ta ftiakso)

**Comment by DaKnOb** [comment]
👍 

Και εγώ έχω μερικά General Atomics MQ-1 Predator που βρήκα σε καλή τιμή και με μεγάλη διάρκεια μπαταρίας. Ποιός θέλει drone wars?

**Comment by padeler** [comment]
FYI: http://www.opengov.gr/yme/?p=3248

eurwph giname ...  Pantos exei kapoia poli periergous (aparadektous) periorismous opos apagorefsi ptiseon 8km apo aerodromia...

**Comment by padeler** [comment]
So, when do you think we should do this? 

I suggest Friday or in the weekend, @kabitakis is this ok? Can you be our host@office12?

**Comment by kabitakis** [comment]
Sure thing @padeler! As long as you don't fly your drones inside the office :)

**Comment by padeler** [comment]
@kabitakis not even a little hover? :) (just kidding). @sonaht, you initially suggested this week are you still ok with it?

**Comment by msti** [comment]
Friday is ok for me. 
I am not sure if I will be able to make it in the weekend.

**Comment by sonaht** [comment]
Sure, Friday is fine, weekend as far as I know details I can switch things around, but friday after work is fine

**Comment by padeler** [comment]
Ok how about ~19.00 @ office12 , (if @kabitakis is ok)

**Comment by maounis** [comment]
Office 12? Δηλαδή να τα φέρουμε σε φωτογραφίες μόνο ε? Που θα πετάξουμε? :)

Αλήθεια εξοπλισμό φέρνουμε ή όχι?

**Comment by sonaht** [comment]
όχι όχι να τον φέρεται τον εξοπλισμό... να δούμε και μεις κάτι....

**Comment by padeler** [comment]
xaxa nomiza oti h idea einai na doume ligo ti xriazete kai pos/poso/apo pou mpori kapoios na ta vrei. @maounis krata eksoplismo thelo na do to super duper quad sou :) tha fero kai ego to diko mou an kai den ksero an tha petaei. Efaga mia ksegirismeni ptosi simera kai einai sto sinergio!

**Comment by kroditakis** [comment]
i will be there! Μιχαήλ Ηλιάδη 12, Iraklio 714 09 , right?

**Comment by padeler** [comment]
@kroditakis yes!

**Comment by sonaht** [comment]
kai xamos tha ginei simera !!!

**Comment by padeler** [comment]
xamos! panikos!

**Comment by sonaht** [comment]
paizei na exoume kai ena dji matrice 100 !!!

**Comment by maounis** [comment]
Εφόσον είναι hack session: 

https://www.youtube.com/watch?v=5CzURm7OpAA

**Comment by padeler** [comment]
@sonaht o sven den exei ena tetoio ? :)

**Comment by sonaht** [comment]
nai nai nai ... isos erthei !!!

**Comment by padeler** [comment]
xaxa kai xthes mou ta masage sto tilefono, kai gamo tha exoume olo to range apo h/w :)

**Comment by padeler** [comment]
Chat room on gitter: https://gitter.im/devstaff-crete/diy-multicopters?utm_source=share-link&utm_medium=link&utm_campaign=share-link

Also my notes from today's hacksession: https://docs.google.com/presentation/d/1mQmKV86S5RGl9w_58T1F4KiOl_rYxcGnRUym_ZtOJ0k/edit?usp=sharing

**Comment by sonaht** [comment]
@padeler THANK YOU for the non stop, non nonsense presentation yesterday.

@maounis THANK YOU for the flight buzzzz, addictive to say the least !!!

**Comment by padeler** [comment]
and thanks to @kabitakis for the hosting!

@sonaht I hope I did not scare you away with all the technical stuff! In any case if you need any help let me know ...

**Comment by sonaht** [comment]
Goes without saying that MANY THANKS go to @kabitakis for kindly providing for us!!!

**Comment by danmilon** [comment]
thank you all :)

**Comment by zakkak** [comment]
@padeler sorry pou den apantisa pote... Eimoun ektws kai ap'oti vlepw exasa kai to hack session :(

Empiria den exw, mono oti exw dei apo edw k apo ekei, kapoia stigmi 8a i8ela na ftia3w ena alla den yparxei xronos auti tin periodo.  Ean pate gia kammia ptisi i gia deutero hack-session let me know.

**Comment by padeler** [comment]
@zakkak apo oti fenete psithike kosmos sto hacksession :) 

sigoura tha exeis tin efkairia se kapoio epomeno event. 
btw sto  [gitter](https://gitter.im/devstaff-crete/diy-multicopters) exei arxisi na ginete kouventa gia builds.
