### ISSUE TITLE
Improve Org Team Meetups

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#125]
Since its conception, DevStaff was intended to be an open community. Both in the sense that everyone can join, but more importantly - imho - in that everyone can also participate and help run the community. 
### How we decide on DevStaff Org issues

For all organizational issues, we had agreed that we would: 
- use GitHub issues to discuss any such topics (e.g. how to handle sponsors - #4 , the community CoC - #3 , etc.  )
- have face-to-face meetings to discuss any other topics that require greater bandwidth

Issues have worked relatively well imho, apart from the voting process (which I hope will be fixed with the new GitHub reactions, as discussed here #120 ) - but please feel free to disagree. 
### Improving Org Team Meetups

I do feel however that these could be improved. Here is an indicative list of issues that people have brought up over time: 
- People turned up to a beerup expecting... beer - i.e. a networking session - but not really org team talk. 
- People missed a beerup because they didn't know it was on. 
- Org Team meetups are dominated by guys, hardly any girls have participated, which is not representative of our community (btw, 15% DevStaff members are girls)
- We don't have a clear way of agreeing when we'll have a beerup (at the moment we just announce on Gitter)
- Meeting minutes (i.e. what was discussed) and action items (i.e. what was agreed) doesn't really make it back online (only stays in people's minds)
- ... add your own below please

**Comment by msti** [comment]
I agree with all the points.

Devstaff is very transparent and everybody knows that can come to the beerup meetings (there is announcement before every meetup) However, the truth is that the beerup is announced only in gitter a few days before. If you do not participate in gitter daily it is very easy to miss the announcement.
Perhaps we should set fixed dates or announce the beerup at least 10 days before.

Also, the agenta. We need a clear agenta before the beerups, decisions taken and perhaps follow up actions.

**Comment by sonaht** [comment]
This hs been covered long ago, closing this as old
