### ISSUE TITLE
How to search for and read academic papers [hack session]

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#132]
If people are interested I could do a hands-on workshop on how we (people in academia) search for cool papers and how we read them.

Date: ~~After 10th of July~~ ~~Someday in September~~ Someday
Place: Office12 if @kabitakis is willing to host us and participate, otherwise we can do it at FORTH
Limit on attendees: 10
Prerequisites: Good understanding of (written) English

**Comment by msti** [comment]
👍

**Comment by konchalas** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by danmilon** [comment]
Sounds interesting :)

**Comment by kabitakis** [comment]
👍 anytime @zakkak :)

**Comment by zakkak** [comment]
Guys sorry for not making this hack session in July.  Let's reschedule for September so that all of us are back in Heraklion.

**Comment by zakkak** [comment]
September is long gone now and December is approaching.  Who is still in?

**Comment by estavrak** [comment]
:+1:

**Comment by zakkak** [comment]
I am closing this due to lack of interest.
