### ISSUE TITLE
Agile Hack Session

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#133]
Especially useful for the participants of the AgileCrete unconference. The goals are to get familiar with the terminology, the format of the event and the basics of the agile world. The unconference is a bit unstructured and the value of the sessions comes from the contribution of each one involved. This "pregame" event will get us in the mood to start thinking on the topics we'd like be covered and help us all get the most out of the unconference.

~~Thursday~~ Wednesday ~~21~~ 13 / 7 / 2016 20:00 @Office12

**Comment by sonaht** [comment]
I'll there 

:+1:

**Comment by msti** [comment]
Is this about agile or for AgileCrete?

**Comment by sonaht** [comment]
@msti I believe this is a "pregame" event before AgileCrete, organised as a hacksession by @kabitakis to get us into the mood of how AgileCrete is done, add some value to the way we might wish to approach this in general. (IMHO)

**Comment by sstauross** [comment]
👍

**Comment by flouris** [comment]
It would be great (for me at least) to have a public google calendar with these planned meetups and hackessions so we can follow it and our phones can send us nice notifications/emails about upcoming events :)

**Comment by kabitakis** [comment]
Good idea @flouris! Wrong place however :P I'll open an issue for this one.

@msti "The goals are to get familiar with the terminology, the format of the event and the basics of the agile world". So we'll cover the basics, find out how each one works and what to expect when you meet other agile managers/masters/coaches etc. We'll do this following the format of the unconference.

**Comment by kabitakis** [comment]
#134 related issue

**Comment by gsaslis** [comment]
@kabitakis i see two entirely separate topics here:

- The [unconference format](https://en.wikipedia.org/wiki/Open_Space_Technology) 
- Agile Software Development practices

The two happen to coincide at #AgileCrete, BUT a. open spaces can be used for any sort of event (e.g. a DevStaff meetup on any topic), b. each is big enough on its own to warrant a separate discussion, c. i'm not sure which of the two you wanted emphasis on... 

I'm assuming you want this to be more like an "intro to agile" discussion?

In July, I can only make it between 11-15 July. 

P.S: imho, this doesn't really sound like a 'hack' session, since we're not really hacking on any technology

**Comment by kabitakis** [comment]
@gsaslis we're not going to discuss the unconference format or the forms it might take. We'll just use the format so the ppl can get familiar with it.

The event is going to be an "intro to agile" as well as an "AgileCrete tips" discussion.

**Comment by gsaslis** [comment]
Ok great!

I'm good with anytime in the week 11-15 July.  How about Wednesday the 13th
@ 19:00 or 20:00 ?


On Monday, 4 July 2016, Nikos Kampitakis <notifications@github.com> wrote:

> @gsaslis <https://github.com/gsaslis> we're not going to discuss the
> unconference format or the forms it might take. We'll just use the format
> so the ppl can get familiar with it.
>
> The event is going to be an "intro to agile" as well as an "AgileCrete
> tips" discussion.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/devstaff-crete/DevStaff-Heraklion/issues/133#issuecomment-230323687>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACTwkr5LNeLTOASaCCBgfZPveEyReFlwks5qSTSagaJpZM4JBgtf>
> .
>


-- 
-- 
Yorgos Saslis
Software Engineer

**Comment by kabitakis** [comment]
@sonaht, @sstauross, @Archimidis would you agree to @gsaslis? Could we have this session this Wednesday @ 20.00?

**Comment by sonaht** [comment]
I am ok for this but I would need to know early if the rest agree

**Comment by sstauross** [comment]
i am ok also!

**Comment by Archimidis** [comment]
Κανένα πρόβλημα για 13/7 από μένα!

**Comment by kabitakis** [comment]
So.. Wednesday 13/7/16 20:00 @ Office12 it is!
