### ISSUE TITLE
Create a calendar for the dev events

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#134]
As suggested by @flouris, we could have a calendar (google?) to keep track of dev events like meetups, org meetings, hack sessions and even ones unrelated to the DevStaff community like local conferences (AgileCrete, JCrete4Kids) or global ones that local community participate in.

**Comment by tzanis** [comment]
I would suggest the following solution (written by the skgtech guys) which I think is exactly what we need (?).

[https://github.com/skgtech/skgtech.github.io](url) (see it here in action: http://skgtech.io)

**Comment by gsaslis** [comment]
@kabitakis i see Office12 now offers such an event calendar... 

I'm leaving this here https://office12.gr/heraklion/ and I'm closing this issue for now. 

Please feel free to leave other comments with other similar calendars, etc.
