### ISSUE TITLE
Gitter does not work (for us)

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#138]
from talking to a few ppl, it seems to me Gitter doesn't really work all that well for the group chat. 
Even though there has been some interesting content shared there, some times it can feel a bit empty. 

Is it a problem with the tool?
Would you guys prefer, e.g. Slack ?

Any other suggestion?

**Comment by kapolos** [comment]
I didn't register with Gitter because it required permissions related to the Github teams I'm part of, which is an obvious no go (and it has no functional reason to ask that),

Slack is the best option by far imho. Very reliable, tons of features and has been proven to work with huge communities.

For more hip & hype, there's [Semaphore](https://spideroak.com/solutions/semaphor).

**Comment by msti** [comment]
Gitter is not the best tool in the market, but it does the job we want it to do. 
I would prefer slack though. Better UI, more features, native app and a standard.
On he plus side for Gitter is the low entry barrier. I do not think that every member of devstaff uses slack.

**Comment by msti** [comment]
The title should be more something 'Does Gitter work for us?'

**Comment by kapolos** [comment]
If accessing a Slack channel is considered a barrier to entry for a tech community, I have no words. I mean, if it was Knitting-Heraklion, I'd get it but...

**Comment by msti** [comment]
We have discussed in the past that devstaff wants to open up to other groups (even Knitting-Heraklion). I agree this should not be a barrier for anyone.

**Comment by kapolos** [comment]
If one can register and use Facebook, they can as easily register and use Slack. I'm pretty sure we can agree that's a really low bar to pass. What's more, aren't we all more than happy to assist every person in the rare case they meet some difficulty with it?

**Comment by msti** [comment]
People who wish to participate will definitely register and take a step further. People who are not regulars and want to ask a quick question will they go on and create a slack account? I doubt.

**Comment by kapolos** [comment]
Gitter requires a Github/Twitter account. How do you cope with that requirement if they don't have one? For example, I don't have a Twitter account and I do not agree with the permissions that Gitter asks for the Github integration.

A community chat's main purpose is community building and not general queries. In the devstaff web site it has a link to the Facebook account and an email for communication. Those two things should cover practically anyone in regards to questions. I think we can agree that everyone has an email account these days.

**Comment by gsaslis** [comment]
imho, github account is a much higher barrier to entry than a slack account. 
Also, yes, there's a Facebook page, so 'anyone' can contact us that way if they want to. 

Looks like we all agree for Slack over Gitter though, so far?

p.s. title is opinionated, just like when you raise a ticket... ; ) I will happily accept a #worksforme or #wontfix response, if that's what the outcome here is.

**Comment by msti** [comment]
@kapolos 
All devstaff members have a github account so joining Gitter is a non issue. 
When I mentioned about a quick question I was referring to technical questions.

@gsaslis 
I will be happy to ditch Gitter.

**Comment by msti** [comment]
@gsaslis 
Yes, like whenever newbies raise tickets :p

**Comment by kapolos** [comment]
@msti If one knows how to sign up for a Github account, I think we can agree that it is really easy for them to sign up for Slack.

**Comment by msti** [comment]
The fact that one needs to sign up for another account automatically raises the bar. 
Let's not continue this discussion, we both agree on switching to slack.

**Comment by mikedi** [comment]
Slack sounds good. Some of us already use it for work related communication. Having less communication applications running at the same time is a plus as well.

**Comment by sonaht** [comment]
As off yesterdays org meetup we are moving to slack. Closing this
