### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by sonaht** [devstaff-crete/DevStaff-Heraklion#14]
DevOps (a clipped compound of "development" and "operations") is a software development method that stresses communication, collaboration, integration, automation, and measurement of cooperation between software developers and other information-technology (IT) professionals.

DevOps driving factors:
* Use of agile and other development processes and methodologies
* Demand for an increased rate of production releases from application and business unit stakeholders
* Wide availability of virtualize and cloud infrastructure from internal and external providers
* Increased usage of data center automation and configuration management tools
* Tearing down silos and making sure developers and ops work together, more and better

Related topics:
* DevOps (description/ideology/mindset)
* Tooling
  * Ansible
  * Puppet
  * Chef
  * Other tools
* Continuous Integration methodology/tools (CI)  (**updated 11/07/2015**)
* and more

- [x] This is NOT a complete list, feel free to suggest more

**This will be the subject of the third meetup. no more voting**

**Comment by sonaht** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by gsaslis** [comment]
:+1:

-- 
Yorgos Saslis
Software Engineer

**Comment by zakkak** [comment]
:+1:

**Comment by pappaschris** [comment]
:+1:

**Comment by fadamakis** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by andronikigr** [comment]
:+1:

**Comment by akatopo** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by nkyriazis** [comment]
:+1:

**Comment by Hotshuk** [comment]
:+1:

**Comment by Sifis-Develop** [comment]
:+1:

**Comment by markop** [comment]
:+1:

**Comment by gsaslis** [comment]
btw -- at the danger of having this characterized as shameless promotion, so apologies in advance -- we're going to be discussing plenty of DevOps-related subjects at the [#AgileCrete Coach + Dev Camp](https://prezi.com/ahguyjmmdq2d/agilecrete-2015/), that starts this Thursday 16th July (we gave away one free ticket in our first meetup last week).

Subjects like #22 , #29, Continuous Delivery, Zero Downtime, as well as Infrastructure Automation, are all crucial to supporting the Agility of any company / organization, so I hope that at least the devs attending will find them interesting. 

Sorry for the 'promo', I just didn't want anyone coming up with an I-didn't-know excuse.. : )

**Comment by zakkak** [comment]
Regarding ansible there is a great set of recipes in https://github.com/sovereign/sovereign "to build and maintain your own private cloud"
