### ISSUE TITLE
[Hack Session] Docker monitoring and Docker infra visualisation tools

### ISSUE THREAD

**Issue by sonaht** [devstaff-crete/DevStaff-Heraklion#141]
I am very interested in tool that provide the following:

Docker metrics
Docker monitoring
Docker Infra visualisation
Docker logs management
etc

This seems like a good place to start a conversation in anticipation of a hack session (this will be a hack session as such)

This will require setup and some work before hand as it probably will need a lab setup as well.

🔈 I will be able to do some of the work.

(let me know who else out there is interested in doing some work as well)

**Comment by maounis** [comment]
👍

**Comment by DaKnOb** [comment]
👍

**Comment by filipslavik** [comment]
👍

**Comment by gvre** [comment]
:+1:

**Comment by sonaht** [comment]
Guys there will be a substantial (time wise) delay into completing this as things crept up. Any one else interested in taking point ?

**Comment by estavrak** [comment]
:+1:

**Comment by sonaht** [comment]
In anticipation of the latest Docker developments ref the experimental logs aggregation and pushing as well as the imminent inclusion of the infinit product line inside docker (infinit was bought by docker) I will close this hack session.

I believe we will have more on future version of docker so I shall reopen this (or a new one) as soon as the information are avail to me.
