### ISSUE TITLE
Developing and Maintaining Open Source Software

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#144]
Today we can find a ton of Open Source projects available, especially in websites like GitHub. They range from tiny projects that their author open sources, to huge ones, such as the Linux Kernel, Gitlab, Kubernetes, Go, etc.
In this topic, we will see how we can start a new project and Open Source it on GitHub, Open Source and existing project we may already have, contribute to an already existing project, as well as maintain one once we get started having Pull Requests.
A relevant Hack Session can also be organized afterwards for the people who are interested.
If you liked this topic, comment with a `:+1:` and add the 👍 reaction to it, and if you're comfortable speaking about it, comment with a `:speaker:`. 
If you want to see something more or can present something related to this, please comment and we can update the description as needed.

**Update 1:**
If we do not have more than two speakers, we can spend the third part of this event doing lightning rounds where every person interested can present their Open Source Project in one to five minutes. We already have some projects [here](https://github.com/devstaff-crete/DevStaff-Heraklion/blob/master/projects/README.md).

**Comment by DaKnOb** [comment]
👍

**Comment by DaKnOb** [comment]
🔈

**Comment by sbehnsen** [comment]
👍

**Comment by zakkak** [comment]
:+1: 

:speaker: (given I am available the date of the presentation)

**Comment by sonaht** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by gvre** [comment]
👍

**Comment by sstauross** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by gsaslis** [comment]
👍  🔈

**Comment by sugarenia** [comment]
👍

**Comment by flouris** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by mikedi** [comment]
👍

**Comment by msti** [comment]
👍

**Comment by svelon** [comment]
👍

**Comment by eirinikp** [comment]
:+1:

**Comment by svelon** [comment]
👍

**Comment by ManosGEM** [comment]
👍

**Comment by kounelios13** [comment]
👍

**Comment by maninak** [comment]
:+1:

**Comment by panosmk** [comment]
👍

**Comment by gsaslis** [comment]
Closing as it's been picked for the next topic (July 2017). 
We even have a couple of speakers who haven't added a 🔈  here.
