### ISSUE TITLE
Bitcoin, blockchain and the future

### ISSUE THREAD

**Issue by msti** [devstaff-crete/DevStaff-Heraklion#145]
I would like to see a session about Bitcoin (and other digital currencies), their underlying technology and the socioeconomic impact.

**Bitcoin**. 
Entry to bitcoin. What is it, how to use, buy and spend. Exchanges and related services. How does its future look like?

**Βlockchain**
Blockchain is the technology behind Bitcoin that keeps it secure. 
How does it work and what are some other interesting applications?

**Social impact**
Can Further adoption of bitcoin and blockchain bring fundamental changes to the operation of our society? What will be it be like and how will ordinary people benefit?

**Comment by sonaht** [comment]
A very nice subject and it should touch Ethereum (https://www.ethereum.org/) as well...great issue.

I was generously introduced to ethereum by Lefty, my mentor and guru in general (he is a shy fella)

:+1:

**Comment by DaKnOb** [comment]
👍

**Comment by DaKnOb** [comment]
🔈

**Comment by msti** [comment]
👍

**Comment by sugarenia** [comment]
👍

**Comment by Pepemakis** [comment]
👍

**Comment by flouris** [comment]
:+1:

**Comment by maounis** [comment]
👍 @msti Docker and Blockchain! Great team!

Bitcoin is just the first application of Blockchain. Great topic.
I also had the privilege to have the "double spend" opportunity in Ethereum after the hard fork. 
No I did not invested in theDAO :)

I could share some excitement :)

**Comment by DaKnOb** [comment]
@maounis Add the `:speaker:` tag in your comment and see what happens next.. :-) 

Ethereum / DAO was a failure. They broke their own rules. I wouldn't trust them with anything.

**Comment by maounis** [comment]
@DaKnOb Yep. 

That's why I now have both:

![image](https://cloud.githubusercontent.com/assets/1745644/19512678/b0230c16-95f5-11e6-914e-55f1b3e9366a.png)

**Comment by msti** [comment]
@maounis Apps on top of blockchain with docker. Very interesting!

**Comment by DaKnOb** [comment]
@maounis I have Bitcoins and Doge Coins from what I know.. :-)

**Comment by sonaht** [comment]
with Ethereum there are some wicked apps reference contracts and blockchains etc, very very interesting

**Comment by DaKnOb** [comment]
Yes, but if you suddenly make money without breaking the rules, everyone cries like a baby and wants a hard fork.. :P

**Comment by padeler** [comment]
:+1:

**Comment by maounis** [comment]
@msti Yes! Actually Blockchain is mastering Decentralization and Docker is mastering Distribution.

Rings any bells? :)

**Comment by danmilon** [comment]
Two buzz words joined together.. Masterpiece ensured!

**Comment by dsiganos** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by sstauross** [comment]
👍

**Comment by mikedi** [comment]
👍

**Comment by svelon** [comment]
👍

**Comment by eirinikp** [comment]
:+1:

**Comment by ManosGEM** [comment]
👍

**Comment by npapnet** [comment]
👍

**Comment by gsaslis** [comment]
👍

**Comment by maninak** [comment]
:+1:

**Comment by panosmk** [comment]
👍

**Comment by zakkak** [comment]
:+1: 

I would also like to see some discussion on the impact of such "currencies" on the environment...
To me it is a total non-sense... Could we have the same benefits that crypto-currencies offer without the "mining" process, or at least with bounded "mining"?

**Comment by gsaslis** [comment]
Closing as this topic has been selected for the Sep '17 topic.
