### ISSUE TITLE
Automated Vulnerability Scanning

### ISSUE THREAD

**Issue by estavrak** [devstaff-crete/DevStaff-Heraklion#149]
![kalidevs](https://cloud.githubusercontent.com/assets/13367693/19646189/f60e5190-9a00-11e6-8ab7-2c622fbb7171.jpg)

Remember that 'Developing with Security in Mind' [meetup](https://github.com/devstaff-crete/meetup07-Security) we had in February?

We are certain y' all have been 'practicing safe development', and would like to show you a few ways to double check your work. 

We will have a look at a few tools that can be used for web app [vulnerability scanning](https://www.owasp.org/index.php/Category:Vulnerability_Scanning_Tools), mostly '_point & click_' stuff included in Kali Linux, such as:
- httrack
- owasp-zap
- w3af
- nikto
- nmap
- wpscan
- golismero
- and a few more :facepunch: 

Of course, there will probably be some preaching about current threats, best practices, the earth being flat, and beer.

Anyone willing to contribute is more than welcome, so far @DaKnOb and I are thinking about this.

Special thanks to @eirinikp for the poster!

PS: @gsaslis “In this meetup, we will see how we can incorporate automated security testing in the Software Development Life Cycle so we can increase the Agility of the team."

**Comment by DaKnOb** [comment]
:+1:

**Comment by DaKnOb** [comment]
:speaker:

**Comment by maounis** [comment]
👍

**Comment by zakkak** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by sonaht** [comment]
:+1:

**Comment by gvre** [comment]
👍

**Comment by flouris** [comment]
👍

**Comment by estavrak** [comment]
:+1:

**Comment by estavrak** [comment]
:speaker:

**Comment by EraserheadX** [comment]
:+1:

**Comment by gsaslis** [comment]
Hmm interesting! 

👍 

Also, did you guys know about http://inspec.io/ ? Together with the CIS Security benchmarks (which are btw, embedded in `Chef Compliance`, a commercial Chef offering) it takes a somewhat different approach (if I understand correctly what you're proposing) to tackle some of the same issues. It basically says: let me check your server against a looooong list of known security vulnerabilities and come back to you with things you need to fix.

**Comment by mikedi** [comment]
👍

**Comment by msti** [comment]
👍

**Comment by gsaslis** [comment]
TIL  http://dev-sec.io/

**Comment by agougousis** [comment]
:+1:

**Comment by georgeangeletos** [comment]
:thumbsup:

**Comment by ManosGEM** [comment]
👍

**Comment by nikos445** [comment]
👍

**Comment by dzervas** [comment]
:+1:

**Comment by maninak** [comment]
:+1:

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
