### ISSUE TITLE
IoT (Internet of Things)

### ISSUE THREAD

**Issue by sonaht** [devstaff-crete/DevStaff-Heraklion#15]
The Internet of Things (IoT, sometimes Internet of Everything) is the network of physical objects or "things" embedded with electronics, software, sensors, and connectivity to enable objects to exchange data with the manufacturer, operator and/or other connected devices

Related topics:
* Definition
* Areas of Application
* Smart Cities
* Case studies
* etc

 - [x] This is NOT a complete list, feel free to suggest more

:speaker:

**Comment by sonaht** [comment]
:+1:

**Comment by sbehnsen** [comment]
:+1:

**Comment by fadamakis** [comment]
:-1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by frcr** [comment]
:+1:
"My vacuum cleaner has more followers than I do."
 I would like to hear more.

**Comment by sonaht** [comment]
@frcr this is a very interesting subject, not only because hardware is somehow used to get things done, but from the developers perspective as well if we factor into the equation that all data gathered from IoT devices need to be stored analysed presented via software platforms, mobile apps etc etc... stay tuned, as this is one of my favourites

**Comment by yiasou** [comment]
:+1:

**Comment by stivaktakis** [comment]
:+1:

**Comment by mKontakis** [comment]
:thumbsup:

**Comment by maounis** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by jvalsam** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by kabitakis** [comment]
Hey! Nice PNGs.. keep in mind that only a :+1: counts as a vote ;)

**Comment by msti** [comment]
:+1:

**Comment by stavrosAd** [comment]
:+1:

**Comment by zakkak** [comment]
:-1:

**Comment by webdevgr** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by maounis** [comment]
Since we were discussing this here are some links for a Raspberry Pi in Greece:

http://robotstore.gr/development-tools/raspberry-pi/raspberry-pi-2-model-b/

http://www.nettop.gr/index.php?option=com_virtuemart&view=productdetails&virtuemart_product_id=301&virtuemart_category_id=26&Itemid=1

Also some other interesting products/services are:

https://www.afero.io/ (Thanks Nikos)
https://www.particle.io/
https://io.adafruit.com/

**Comment by sbehnsen** [comment]
I also find these two sources quite good for Raspberry + Accessories

http://gr.rsdelivers.com/
https://www.adafruit.com/category/105

**Comment by sonaht** [comment]
And some more about collecting cloud platforms, seem nice:

https://www.temboo.com/
https://www.carriots.com/
http://www.nearbus.net/
http://ubidots.com/

**Comment by maounis** [comment]
Nice.

Two more cloud services:

https://xively.com/
https://thethings.io

**Comment by kabitakis** [comment]
I must reveal that @padeler has recently got some nice IoT toys but he prefers to play alone :P
Pascal tell us about your new robot!

**Comment by padeler** [comment]
@kabitakis: Well it is a "Thing" that can have an "Internet" connection but I don't think it is IoT material :) Great toy though!

**Comment by kabitakis** [comment]
It definitely  sounds like a ToI :P Can you give us the url of the product page?

**Comment by maounis** [comment]
This is also interesting: https://data.sparkfun.com/

**Comment by gzografa** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by sbehnsen** [comment]
:+1:

**Comment by npapnet** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by maounis** [comment]
The WIO Link from here is also interesting and it comes with RESTful API:

http://www.seeedstudio.com/blog/2016/01/19/2015recap-top-10-new-products/

**Comment by npasadakis** [comment]
:+1:

**Comment by sbehnsen** [comment]
:+1:

**Comment by mikedi** [comment]
![image](https://cloud.githubusercontent.com/assets/2017210/13871916/00ad39d2-ecef-11e5-9a10-000ea6e6ba4f.png)

**Comment by nkvorn** [comment]
:+1:

**Comment by sonaht** [comment]
Anyone interested in co-presenting this, just ping me on gitter

**Comment by DaKnOb** [comment]
:speaker:

**Comment by estavrak** [comment]
:+1:
:speaker:

**Comment by sbehnsen** [comment]
:speaker:

**Comment by sonaht** [comment]
CLOSING THIS

this will be the subject of meetup 09
