### ISSUE TITLE
Microservices

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#150]
Probably one of the most popular terms for software developers today. 

Let's explore what it means / how it works / when it should be used (and not). 

:speaker:

 :+1:

**Comment by sonaht** [comment]
:+1:

**Comment by maounis** [comment]
👍

**Comment by DaKnOb** [comment]
:speaker: :+1:

**Comment by gvre** [comment]
👍

**Comment by Archimidis** [comment]
:speaker: :+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by msti** [comment]
👍

**Comment by agougousis** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by maounis** [comment]
@gsaslis I am open for a micro-coffee session for this as well :)

**Comment by sstauross** [comment]
👍

**Comment by webdevgr** [comment]
:+1:

**Comment by padeler** [comment]
:+1: time to learn a new [buzz]word :)

**Comment by eirinikp** [comment]
:+1:

**Comment by pappaschris** [comment]
👍

**Comment by panosmk** [comment]
👍

**Comment by sonaht** [comment]
Closing this... see meetup 28
