### ISSUE TITLE
Django Hack Session

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#151]
For months, the most popular topic of DevStaff was Django, but we lacked the speakers and it was always postponed. It's time to change this: we are organizing a Django Hack Session where everyone interested can come and learn Django Web Development from scratch. The idea is we'll gather up and start following tutorials / building websites until we gain a "good enough" knowledge of the framework. Afterwards, if we're feeling okay, we can maybe organize the talk.

**Location** Computer Science Department, University of Crete
**Date** Let me know when you're available below, most likely after 20:00
**Seats** 10
**Projector** None available, please bring your own
**Map** Included
**Slack Channel** `#django-hacksession`

![map](https://cloud.githubusercontent.com/assets/743648/19999846/450f8ae6-a27d-11e6-8c98-8a89d627e3e7.png)

> NO PRIOR EXPERIENCE NECESSARY, JUST WILL TO LEARN

**Comment by svelon** [comment]
I'm interested, but I am only available on Thursdays and Fridays.

**Comment by ariel2023** [comment]
I'm in as well thanks!

**Comment by padeler** [comment]
I am in, but only if it is scheduled towards the end of this month (after next week) :+1:

**Comment by DaKnOb** [comment]
So far it looks like it can be 24-25 of November.. Let's see..

**Comment by msti** [comment]
👍

**Comment by EraserheadX** [comment]
:+1:

**Comment by EraserheadX** [comment]
Does this mean there won't be a talk? Just the hack session?

**Comment by DaKnOb** [comment]
@EraserheadX We will try and see what we can learn, and then use that to prepare a talk possibly, or if we don't feel comfortable with our knowledge, postpone the talk even further. Do you have any experience w/ Django?

**Comment by EraserheadX** [comment]
None whatsoever. :)

**Comment by DaKnOb** [comment]
Then you're a perfect fit! :P 

Let's see what we can learn and if it's good enough to present it to the others..

**Comment by agougousis** [comment]
:+1:  Με μια μικρή επιφύλαξη στις ημερομηνίες τις οποίες θα λείπω και δεν μπορώ να γνωρίζω ακόμα 100%. Γενικά, θα προτιμούσα τέλη του μήνα (μετά τις 20) με εξαίρεση τις 26-27 που θα είμαι Χανιά. Με τις ώρες δεν έχω πρόβλημα. Νυν υπέρ πάντων η επιμόρφωση!

**Comment by DaKnOb** [comment]
So 24-25/11 seems to be the best date for something like that? Can everyone make it?

**Comment by padeler** [comment]
I am probably ok with those dates but i'll know for sure by the end of the week.

**Comment by agougousis** [comment]
Από εμένα, εντάξει!

**Comment by svelon** [comment]
I will not be here on 24-25, nor on 19-20! Can we make it the first week of December?

**Comment by DaKnOb** [comment]
@daknob @padeler @svelon @agougousis @EraserheadX @msti @ariel2023 

Please complete the following Doodle:

http://doodle.com/poll/vctqznpstmtfsrkm

**Comment by DaKnOb** [comment]
The event has been scheduled for December the 1st, at 20:00 local time. @sonaht / @gsaslis can you please add this to the MeetUp?

Attendees, 
Please be by 19.50 in the "Recommended Entrance" marked above. We will wait up to 20.00 and then will have to go to the room the event will take place. If you're late there's no way to get in the building and will have to call me or DM me on Slack so I can come and open for you.

**Comment by gsaslis** [comment]
Done. ; )
