### ISSUE TITLE
PHP frameworks

### ISSUE THREAD

**Issue by svelon** [devstaff-crete/DevStaff-Heraklion#152]
PHP is the most commonly used language on the web. Therefore it has a lot of frameworks to choose from. But what do those frameworks offer? Which is the one most suitable for you?

I will to talk about Zend and my experience with PHP frameworks in general.

If you're interested in learning more about this, comment a :+1:  and if you would like to talk about a framework, or share your experience (good or bad!) comment a  🔈.

**Comment by DaKnOb** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by gvre** [comment]
+1

**Comment by DaKnOb** [comment]
@svelon Don't forget to add your own `:+1:` and `:speaker:`!

**Comment by svelon** [comment]
:+1: :speaker:

**Comment by sstauross** [comment]
👍

**Comment by staurosm** [comment]
:+1:

**Comment by agougousis** [comment]
:+1:  If the time be convinient, I could steal a 15-minute to talk about using no framework at all!  He,he!  Or talk a little about Laravel. Hmm! Will see.  :speaker:

**Comment by Archimidis** [comment]
:+1:

**Comment by sonaht** [comment]
@agougousis haha you know what comes next

you said it !!! you're doing it !!!

Great tho to have you talking about this... sounds great

**Comment by agougousis** [comment]
I am well aware of the consequences, τώρα πια. :v:

**Comment by sonaht** [comment]
I have great faith in you, the force is strong with this one :jedi:

**Comment by webdevgr** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:
An kataferete na pshsete kai thn @irinikp sigoura 8a exei kati na pei.

**Comment by eirinikp** [comment]
:+1:

**Comment by eepitropaki** [comment]
:+1:

**Comment by mzampetakis** [comment]
👍🔈

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
