### ISSUE TITLE
WordPress CMS

### ISSUE THREAD

**Issue by svelon** [devstaff-crete/DevStaff-Heraklion#153]
WordPress is the most used Open Source CMS in the web. This happens because of its simplicity (both in using and developing). WordPress is suitable for blogs and more complex websites, but it's not a panacea. 

I would like to talk about WordPress in general and get deeper about how to develop your own theme and/or plugin.

This talk could also be combined with a discussion about Drupal, Joomla or other CMSs.

If you're interested in learning more about this, comment a 👍 and if you would like to talk about it comment a 🔈.

**Comment by svelon** [comment]
:+1: :speaker:

**Comment by svelon** [comment]
:+1: :speaker:

**Comment by mikedi** [comment]
👍

**Comment by gvre** [comment]
👍

**Comment by sonaht** [comment]
:+1:

**Comment by msti** [comment]
👍

**Comment by maounis** [comment]
👍

**Comment by flouris** [comment]
:+1:

**Comment by sksksksk** [comment]
If there is time and interest, I'd make an introduction to TYPO3. A not so popular, but very flexible and powerful CMS
:+1: :speaker:

**Comment by EraserheadX** [comment]
:+1:

**Comment by msti** [comment]
🔈 
Μπορώ να μιλήσω για Drupal, αν και υπάρχει άλλο topic το οποίο όμως δεν φαίνεται να έχει traction

**Comment by gsaslis** [comment]
Ενδιαφέρον ...  Τι θα λέγατε να τα ενώσουμε σε ένα ας πούμε "CMS Overview" topic?

**Comment by sstauross** [comment]
👍

**Comment by webdevgr** [comment]
:+1:

**Comment by iotheo** [comment]
👍

**Comment by mkgrks** [comment]
:+1:

**Comment by sonaht** [comment]
This is merged in #160
