### ISSUE TITLE
Opensource E-shops

### ISSUE THREAD

**Issue by svelon** [devstaff-crete/DevStaff-Heraklion#156]
Opensource e-shops are like the CMS for online stores... There are too many to choose from, in various languages and with different features.
I would like to see a comparison, hear your personal stories and chat about the pros and cons for the most popular ones.

**Comment by svelon** [comment]
:+1:

**Comment by sonaht** [comment]
:+1:

**Comment by gvre** [comment]
👍

**Comment by webdevgr** [comment]
:+1:

**Comment by iotheo** [comment]
👍

**Comment by sstauross** [comment]
👍

**Comment by ggeorg0p** [comment]
:+1:

**Comment by maounis** [comment]
👍

**Comment by flouris** [comment]
👍

**Comment by eirinikp** [comment]
:+1:

**Comment by panosmk** [comment]
👍

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
