### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by VasilisGkogkidis** [devstaff-crete/DevStaff-Heraklion#158]
Gamification is the application of game-design elements and game principles in non-game contexts. 

I am working full time in a gamification company based in Brighton, UK. 

What we do is help organisations engage their customers and employee in a more effective way using what I call playful design. 

Gamification is a way to look at your company procedures and products from another lens and try and figure out how to make them more engaging and interesting. 

I enjoy public speaking so I would like to come to your meetup and talk about gamification and how you could apply it to solve problems in your companies and make products you already have or are making at the moment more engaging. 

Have a look at what we do:
https://gamificationplus.uk/

And have a look these links to learn more about gamification: 
https://www.youtube.com/watch?v=2lXh2n0aPyw&t=4s
https://www.youtube.com/watch?v=1dLK9MW-9sY
https://www.youtube.com/watch?v=dE1DuBesGYM&t=1s
https://en.wikipedia.org/wiki/Gamification

**Comment by maounis** [comment]
👍

**Comment by zakkak** [comment]
:+1:

**Comment by gsaslis** [comment]
:thumbsup:

**Comment by sonaht** [comment]
:+1:

@VasilisGkogkidis  please indicate with the ":speaker:" icon that you are willing to present the issue or assist in presenting it. ty

**Comment by padeler** [comment]
:+1:

**Comment by svelon** [comment]
👍

**Comment by VasilisGkogkidis** [comment]
👍

Willing to present! 🔈

**Comment by sstauross** [comment]
👍

**Comment by gvre** [comment]
👍

**Comment by Archimidis** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by flouris** [comment]
👍

**Comment by msti** [comment]
:+1:

**Comment by ManosGEM** [comment]
👍

**Comment by nikos445** [comment]
👍

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
