### ISSUE TITLE
Door Signs

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#16]
@kabitakis would it be possible to have something we could print on an A4 page to put on the building doors (x2), on the stairs(x1), elevator (x1) and on the actual door (x1) tomorrow to help ppl understand they've found us ?

I can take care of having them printed here, but I'd appreciate some help with what to print  ;)

**Comment by kabitakis** [comment]
Sure thing! What's the info it needs to include? A logo and an arrow? Room number maybe? Floor?

**Comment by gsaslis** [comment]
Yes, for the 4 downstairs ones, an upward arrow would do. 

Would the following info be enough ?

DevStaff Meetup
The GIT Version Control System @ STEP-C, Heraklion,
Thursday 9th July, 20:00 STEP-C building A, 1st floor

(in English?)

**Comment by kabitakis** [comment]
:+1:

**Comment by kabitakis** [comment]
Pull#18

**Comment by sonaht** [comment]
Closing this... the signs were excellent !!! especially the placement
