### ISSUE TITLE
System and Cluster monitoring

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#161]
System monitoring, especially at the cluster level, can be challenging.
We could talk about tools that help in system/cluster monitoring.

More specifically we could talk about:
* log aggregation tools
* automatic alerting (about resources running out, downtime, etc.) tools
* performance/utilization monitoring tools
* etc.

**Comment by zakkak** [comment]
🔈 I can present [grafana](grafana.org) and [prometheus](prometheus.io).

👍

**Comment by filipslavik** [comment]
That's an interesting one!

👍

**Comment by gvre** [comment]
👍

**Comment by DaKnOb** [comment]
:+1:

**Comment by DaKnOb** [comment]
@zakkak Please fix the two links by prepending `https://` :-)

**Comment by zakkak** [comment]
@DaKnOb please enrich your plugins list with [https everywhere](https://www.eff.org/Https-everywhere) ;)

**Comment by DaKnOb** [comment]
@zakkak I have it, and your links are truly HTTPS. They just redirect to GitHub issues and are 404's.. :P 

(GitHub treats them as internal URLs)

**Comment by zakkak** [comment]
@DaKnOb OK then. BTW grafana.org does not support HTTPS

**Comment by DaKnOb** [comment]
@zakkak Then we don't want to hear anything about it.. :P 

Okay, you can add the HTTP-Insecure version of it..

**Comment by sonaht** [comment]
:+1:

Super issue.

**Comment by estavrak** [comment]
👍

**Comment by gsaslis** [comment]
:thumbsup: :+1:

**Comment by padeler** [comment]
:+1:

**Comment by flouris** [comment]
👍

**Comment by alexzzzboom** [comment]
👍

**Comment by Archimidis** [comment]
:+1:

**Comment by ManosGEM** [comment]
👍

**Comment by nikos445** [comment]
👍

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
