### ISSUE TITLE
Types of Hosting

### ISSUE THREAD

**Issue by maounis** [devstaff-crete/DevStaff-Heraklion#166]
I am not a sysadmin nor an infrastructure specialist but I happen to be in the Hosting Industry for some years now.

I hosted a web server in a [don't remember how many] different ways, from an Arduino to AWS.
There are so many hosting solutions/keywords out there, and if you start writing down some of them like shared hosting, dedicated server, vps, vm, instance, droplet, linode, dyno...it's insane! Plus everyday something new is happening. Digital Ocean is announcing an "AWS like" Block Storage and AWS is announcing "Digital Ocean like" plans in amazonlightsail.com. Grrr! Admins are real heroes! 

I would like to see a Meetup with some talks and best practices on:

- What should really be the starting point for a developer/freelancer/agency/startup/SMB/enterprise customer?
- Does the hosting location/region/availability zone matters? Should my web server be close to my visitors or some more milliseconds don't really make any difference?
- What are the best practices to deal with other decisions like DNS, SSL type you need, CDN and Caching needs, LBs, redundancy, backups, security, monitoring and logging?

Frustrating? Don't worry. Some say that "hosting" is not going to exist as we know it by 2025! :)

I could share some basic high level thoughts on some of the above but people like @sonaht or others may have a lot more experience than me. 

🔈 

:+1:

**Comment by webdevgr** [comment]
👍

**Comment by gvre** [comment]
👍

**Comment by padeler** [comment]
:+1:

**Comment by sonaht** [comment]
This is very interesting and I am amazed that we did not touched base on this earlier.

I can offer my opinion and experiences on this.

🔈 
:+1:

**Comment by filipslavik** [comment]
Very interesting and broad topic. 

👍

**Comment by flouris** [comment]
👍

**Comment by irinikp** [comment]
:+1:

**Comment by alexzzzboom** [comment]
👍

**Comment by Archimidis** [comment]
:+1:

**Comment by sstauross** [comment]
👍

**Comment by msti** [comment]
:+1:

**Comment by agougousis** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by kabitakis** [comment]
👍

**Comment by tzermias** [comment]
:+1:

**Comment by svelon** [comment]
👍

**Comment by gsaslis** [comment]
Closing, as it's been selected as the June 2017 meetup.
Keep on voting!!
