### ISSUE TITLE
[Open Space] Remote Working

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#167]
Working remotely is a growing trend in our industry (whether you believe it or not  : )   ).

It would be great to have an [open space](https://en.wikipedia.org/wiki/Open_Space_Technology) discussion about the topic, so we can exchange ideas and past experience. 

Whether you've done it in the past and care to share some pains / gains, or if you're simply interested to learn more about it, you're more than welcome to join! 

(Logistics: No need to add 🔈 icons on this one, since we won't have presentations / talks. **Everyone who attends is a speaker.** Just add the usual :+1:  to indicate you're interested. Comments are - as always - welcome.)

**Comment by webdevgr** [comment]
👍

**Comment by Archimidis** [comment]
:+1:

**Comment by sugarenia** [comment]
👍  Would love to hear the employer's side as well!

**Comment by sstauross** [comment]
👍

**Comment by msti** [comment]
:+1:

**Comment by sonaht** [comment]
:+1: and 🔈

**Comment by hatdio** [comment]
👍

**Comment by webdevgr** [comment]
We need to educate employers about remote working 😄

**Comment by gvre** [comment]
👍

**Comment by filipslavik** [comment]
my life is all about remote working, so hell yeah 👍

**Comment by msti** [comment]
Since it is remote, I would say to do a google hangouts ;)

**Comment by maounis** [comment]
I am very interested. 

Except the normal recruiting all over the world and the fact that we are almost forcing our local managers to work remotely once a week, one member of my team just left Greece to work remotely in Chiang Mai for 1 month and this seems to be a great idea.

👍

**Comment by agougousis** [comment]
It would be also interested to hear from employers. Why the do or do not utlize remote working. They do they like about it or what do they afraid about it.

:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by flouris** [comment]
👍

**Comment by irinikp** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by kabitakis** [comment]
👍

**Comment by sstauross** [comment]
👍

**Comment by ariel2023** [comment]
:+1:

**Comment by gsaslis** [comment]
FYI - https://github.com/jessicard/remote-jobs

**Comment by svelon** [comment]
👍

**Comment by kapolos** [comment]
👍

**Comment by greenman18523** [comment]
👍

**Comment by ManosGEM** [comment]
👍

**Comment by gsaslis** [comment]
In the end, this won't be so much of an `Open Space` event, but it's been scheduled and it will involve some time for discussion, so closing this.
