### ISSUE TITLE
Apache Spark

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#170]
Apache Spark is a fast and general engine for large-scale data processing. Spark provides an interface for programming entire clusters with implicit data parallelism and fault-tolerance. It currently supports programs written in Scala, Java, Python, and R.

It would be interesting to have a meet up to learn about Spark and how it can be used both from a coding point of view as well as a set up and operation one.

To vote for this topic, add a `:+1:` (not the 👍 emoji) in the comments below and if you can speak about this, even briefly, or have experience in this topic, add a `: s p e a k e r :` (: s p e a k e r :).

**Comment by gvre** [comment]
👍

**Comment by DaKnOb** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by ManosGEM** [comment]
👍

**Comment by nikos445** [comment]
👍

**Comment by flouris** [comment]
👍

**Comment by gsaslis** [comment]
👍

**Comment by sonaht** [comment]
:+1:

**Comment by ealefrag** [comment]
👍

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
