### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#171]
Backups are very important for all devices with unique content stored. This includes personal computers, phones, tables, servers, everything. However, there are currently a lot of people who don't backup their devices, and there are possibly a lot of companies, that don't backup their servers.

In this topic we will explore solutions, methods, and ways to backup anything from personal devices to servers and ensure our data won't be irreversibly lost.

If you'd like to see this topic, comment a `:+1:` (not the 👍 emoji), and if you have experience and would like to maybe speak about that, add a `:speaker:` (:speaker:)  .

**Comment by DaKnOb** [comment]
:+1: 🔈

**Comment by svelon** [comment]
:+1:

**Comment by irinikp** [comment]
:+1:

**Comment by vervelak** [comment]
:+1:

**Comment by EraserheadX** [comment]
👍

**Comment by webdevgr** [comment]
:+1:

**Comment by sbehnsen** [comment]
👍 🔈

**Comment by maounis** [comment]
👍

**Comment by ManosGEM** [comment]
👍

**Comment by nikos445** [comment]
👍

**Comment by dzervas** [comment]
:+1:

**Comment by kounelios13** [comment]
👍

**Comment by flouris** [comment]
👍

**Comment by sonaht** [comment]
:+1:

**Comment by panosmk** [comment]
👍

**Comment by gsaslis** [comment]
closing this, since we had this as last meetup
