### ISSUE TITLE
WebAssembly.js

### ISSUE THREAD

**Issue by npapnet** [devstaff-crete/DevStaff-Heraklion#175]
With the recent implementation in Firefox WebAssembly seems to be entering our lives. In my view it starts turning the pcs/laptops into web connected devices. 

So the following questions spring to mind:
- What is it?
- What is the status of adoption/implementation/standardisation so far?
- Are there any actual performance benefits?
- Who should pay more attention to it?
- How does it effect end users/developers?

**Comment by webdevgr** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

**Comment by sstauross** [comment]
👍

**Comment by zakkak** [comment]
:+1:

🔈 (not an expert though)

**Comment by gvre** [comment]
👍

**Comment by kounelios13** [comment]
:+1:

**Comment by flouris** [comment]
👍

**Comment by maninak** [comment]
:+1:

**Comment by Hotshuk** [comment]
👍

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
