### ISSUE TITLE
Good practices for security anonimity

### ISSUE THREAD

**Issue by npapnet** [devstaff-crete/DevStaff-Heraklion#176]
__DISCLAIMER: This is not a per se issue for developers, it is more an every day, casual user concern.__

Following the well received presentation for TOR, I realised that I may not be doing even the basics to protect myself from online threats (identity theft, security, privacy etc). I also realised that there is a lot of experience in the speakers and a lot experience/good practices that can be shared.

So I would like to see a session (or half a session) for every day security practices both as a developer and as an end user. That may include information on: 
- machine configuration (e.g. blocking ports)
- browser extensions 
- online platforms 
- blogs

One final point, what I have in mind is either one time configuration, or tools which do not -greatly- diminish the online experience.  From that perspective, I would consider extreme and not practical, measures such as disabling by default Javascript (which I am sure will be the first thing the most security conscious people would suggest).

**Comment by Archimidis** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by sstauross** [comment]
👍

**Comment by gvre** [comment]
👍

**Comment by kounelios13** [comment]
:+1:

**Comment by irinikp** [comment]
👍

**Comment by flouris** [comment]
👍

**Comment by gsaslis** [comment]
👍

**Comment by maninak** [comment]
:+1:

**Comment by sonaht** [comment]
:+1:

**Comment by svelon** [comment]
👍

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
