### ISSUE TITLE
Building modern  desktop apps using  web technologies

### ISSUE THREAD

**Issue by kounelios13** [devstaff-crete/DevStaff-Heraklion#179]
Hello.I think that it would be interesting a meetup on this topic.Nowadays JavaScript ,HTML and CSS
can be used to build modern desktop apps using Electron and NodeJS.
So a few questions can be answered during the meetup:
* What is Electron
* How do we build desktop apps using Electron 
* How can we distribute our apps to the end user
* How can we achieve native app styling(Different styles for windows,linux,macOS etc...)
Also maybe we can take a look at NodeWebkit

**Comment by mkcodergr** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by irinikp** [comment]
👍

**Comment by papas-source** [comment]
Γιατί electron και όχι NW (γενικότερα την τεχνολογία αυτή);
Προσωπικά θεωρώ ότι το electron είναι λίγο ανάποδα δομημένο... :/ 
(αν δεν είναι εδώ το σωστό μέρος για κουβέντα σχετική, ενημερώστε με)

**Comment by kounelios13** [comment]
@papas-source  Η αλήθεια είναι οτι δεν ξέρω ιδιαίτερα τις διαφορες τους. Τωρα εχω αρχισει να τα χρησιμοποιω και αρχισα me electron .Αν γινεται να δουμε kai NW ακομα καλυτερα

**Comment by papas-source** [comment]
Η βασική τους διαφορά είναι ότι το NW ξεκινά με τον browser ο οποίος έχει access στο node env, ενώ το electron ξεκινά node και ανοίγει browser (υπεραπλουστευμένα). Η δεύτερη υλοποίηση έχει προβλήματα υλοποίησης (αν και μερικοί δεν το θεωρούν πρόβλημα), όπως για παράδειγμα η επικοινωνία μεταξύ των παραθύρων, ή ακόμα χειρότερα η επικοινωνία του node environment με το renderer (browser) που γίνεται μεσω ipc.

Αλλά εντάξει, το electron είναι in λόγω δυο-τριών εφαρμογών, namely slack/atom κλπ. Δεν είναι κακό, το ίδιο συμβαίνει και από την αποδοχή του react σε σχέση με άλλους js displayers (eg: [hyperhtml](https://github.com/WebReflection/hyperHTML) / [riot](https://github.com/riot/riot) / [svelte](https://github.com/sveltejs/svelte)) και αποδεικνύει ότι η κοινότητα των devs σήμερα είναι (τουλάχιστον) λίγο biased και - κλασικά - ακολουθεί τα buzzwords.

Χωρίς να θέλω να πω ότι το electron πάσχει κάπου ή ότι το NW είναι ανώτερο, οι διαφορές τους είναι (ή δεν είναι) σημαντικές ανάλογα με το milestone σου ;)

Hint: Try να εμφανίσεις [print preview](https://github.com/electron/electron/issues/5076) με electon ;) ή να τυπώσεις pdf (αυτό νομίζω το φτιάξανε με την χρήση external lib - δεν είμαι σίγουρος)

**Comment by maninak** [comment]
:+1:

**Comment by svelon** [comment]
👍

**Comment by ariel2023** [comment]
:+1:

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
