### ISSUE TITLE
Meetup Time: Is 20:00 ok as a start time?

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#187]
For the past ~2 years, most (if not all) meetups have been held at 20:00. 

As of late, there has been growing support for 19:00 as a start time. In the past org team meetup, we decided that the July meetup will be at 19:00. 

If there are objections / other suggestions, for an earlier / later time, please go ahead and voice them here.

**Comment by sonaht** [comment]
I am for the time change. It will allow us extra time to network at the end as well.

So 19.00 as a starting time for July meetups and onwards gets my vote :+1:

**Comment by svelon** [comment]
Let's see what will happen on July and decide later. It seems a good idea, but lets just test it first.

**Comment by kabitakis** [comment]
👎 from me since most of the week days my work time ends past 19.00. It's good we test it though and let's try to get as much feedback as possible.

**Comment by zakkak** [comment]
I liked the earlier starting time on the last meeting. When I used to work in FORTH I didn't like the starting hour being 20:00 because I usually wouldn't stay that long and I had to change my plans so I don't have to go back and forth. Nowadays I prefer the earlier starting hour because it allows me to get back home at more reasonable time, I guess that is a concern for other people as well, especially those with kids.

**Comment by kounelios13** [comment]
I would like to suggest 19:30 as a starting hour.

**Comment by gsaslis** [comment]
for a bit of history, I would like to explain here why - despite the comments / feedback here - we are still at 20:00. 

There was a discussion in a subsequent org meetup after "the July meetup", where there was a consensus to keep the meeting time at 20:00. 

I am thinking that given the "not everyone is on Github" line of argument, we should probably open this as a meetup poll and engage with everyone via email to vote on whether they prefer 19:00, 19:30 or 20:00 as a meeting time. 

(This is all assuming that @padeler can confirm those times are ok for our venue. )

Thoughts?

**Comment by padeler** [comment]
The later we set the meeting the more probable it is to find an available room, but in general, FORTH rooms are (almost always) available after 18.00.  I personally don't have any issues with setting the meetups earlier but maybe it is an issue for people who work 9-5 and then have to drive all the way to FORTH.  We could vote again.

**Comment by gsaslis** [comment]
Poll created: https://www.meetup.com/devstaff/polls/1263443/

@zakkak i think it was as simple as: there were more people at the org team meetup who agreed on 20:00 than the ppl here who favoured an earlier starting time back then. I don't recollect any more details i'm afraid.

**Comment by sonaht** [comment]
Meetup time has moved to 19:00. Closing this.
