### ISSUE TITLE
[Hack Session] Kubernetes, Docker Swarm, Apache Mesos (?), Openshift (?) and other orchestrators

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#188]
# What
Title says it all. Kubernetes, Docker Swarm, Apache Mesos (?), Openshift (?) and other orchestrators.

# Why
The idea is to play around a little with each one, see what we like / don't like, what works for us and what doesn't and learn more about orchestration in general. 

# When 
Some time next week 19-23 June.

# Who
CC'ing some ppl I know will be interested. *Anyone* else is welcome!
@sonaht 
@DaKnOb 
@rkrambovitis 

Please 👍  if interested.

**Comment by sonaht** [comment]
:+1: goes without saying !!!

**Comment by DaKnOb** [comment]
Unfortunately I will not be able to attend since I will not be there.

**Comment by sonaht** [comment]
@DaKnOb our loss !!!

**Comment by gvre** [comment]
👍

**Comment by filipslavik** [comment]
👍 for the topic, as it is more than interesting, however, most likely I won't make it as I will be unavailable from the 19th until (inclusive) the 25th of June.

**Comment by rkrambovitis** [comment]
:+1: could do with catching up

**Comment by zakkak** [comment]
:+1: (I have some experience with docker swarm if needed)

**Comment by gsaslis** [comment]
https://www.youtube.com/watch?v=nqeqmVVOlrY&feature=youtu.be
