### ISSUE TITLE
Sass

### ISSUE THREAD

**Issue by sugarenia** [devstaff-crete/DevStaff-Heraklion#19]
Could be interesting to front-end devs wanting to up their CSS game with preprocessors. It could also be a workshop, something like "migrate a project from vanilla CSS to Sass".

* Why Sass?
* How to start
* File structure
* Nesting
* Variables
* Mixins
* Extends
* Functions
* Pitfalls

**Comment by sugarenia** [comment]
Btw, any idea how can I add a label to an issue?

**Comment by andronikigr** [comment]
:+1:

**Comment by gsaslis** [comment]
:+1: 

( @sugarenia I think only maintainers can presently add labels... : /  )

**Comment by sugarenia** [comment]
@gsaslis thnx for the clarification!

**Comment by zakkak** [comment]
I am not very familiar with the topic, but I have also heard about LESS.  It would be nice to learn about both SASS and LESS if chosen.

**Comment by sugarenia** [comment]
@zakkak not familiar with LESS, but the main ideas (nesting, variables etc) are the same between preprocessors.

If anyone is a LESS fan, stand up! :)

**Comment by DaKnOb** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by frcr** [comment]
:+1:

**Comment by rzolindaki** [comment]
:+1:

**Comment by yiasou** [comment]
:+1:

**Comment by kboutsika** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by ghal** [comment]
:+1::+1::+1:

**Comment by stavrosAd** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by kormic** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by koskonstant** [comment]
:+1:

**Comment by Pepemakis** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by agougousis** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by maninak** [comment]
:+1:

**Comment by theothem** [comment]
:+1:

**Comment by agougousis** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by gsaslis** [comment]
Is there anyone else apart from @sugarenia who is interested in being a :speaker: ? 

(Note: if not, this will get postponed, even though it has most votes)

**Comment by sugarenia** [comment]
@gsaslis I can talk about Sass in the October event, no problem, but September is kinda busy.

**Comment by gsaslis** [comment]
@sugarenia ok thanks for confirming!! 

We can schedule this for October then, and we'll just get something with less votes, but with available speakers for September ;) 

Note: the invitation is still open for anyone else who also wants to speak / present sth about this topic. Just add a comment with a 🔈 below.

**Comment by gsaslis** [comment]
So, @sugarenia, are we ok for October for this one? ;)

**Comment by sugarenia** [comment]
@gsaslis yes we are! 🙊 🙉 🙈

**Comment by gsaslis** [comment]
closing, as this has been scheduled for October!  ;) \o/
