### ISSUE TITLE
Intellectual Property - Agreements - Licenses

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#191]
A dive into the legal matters and processes of software industry.

Because agreements never are as easy as https://m.signalvnoise.com/my-kind-of-contract-e7327e98e3ea

**Comment by kabitakis** [comment]
🔈 Katerina Tsakona
👍 

Personal IP pain point: My clients want us - as it's written in the agreements they provide - to transfer the intellectual property of the software we build to them even though a large part of it is under MIT license and another part is trivial and common among all our projects (e.g. a method to send and email).

Personal NDA pain point: A client says "We want to discuss our idea with you and you give us your estimates on the project, the technical challenges it might have and some of your ideas/consulting. We'll pay you nothing for this task but you have to sign an NDA which says you will never work on a similar project ever again in your life."

**Comment by svelon** [comment]
👍

**Comment by sonaht** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1

**Comment by gvre** [comment]
👍

**Comment by ealefrag** [comment]
:+1:

**Comment by irinikp** [comment]
👍

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
