### ISSUE TITLE
Kotlin Language

### ISSUE THREAD

**Issue by ioannisa** [devstaff-crete/DevStaff-Heraklion#194]
Kotlin is a brand new statically typed language from JetBrains with stable release only since 2016. At 2017, at Google I/O it got proclaimed as "Official Android Language".  Especially now with the androidthings release at IO, it will gain even more attention.

We will introduce pure language syntax and features in IntelliJ IDEA, starting from the "Hello DefStaff" and moving up all the way to some neat features like extension functions, extension properties, tail recursion, smart casting, and more...

If time allows we will play with android too and show some cool stuff, like "kotlin-android-extensions" to simplify the code interaction to our XML model, and so on.

So this talk/hands-on will give you a primer so you can start developing with Kotlin, right after. Consider having your laptop with you if there is WIFI connection available, even if you don't have Kotlin installed.

Take this opportunity to join thousands of developers as now is the best time to kick off with Kotlin!

**Comment by gsaslis** [comment]
Nice! Been meaning to look into Kotlin for a while now. 

Are you thinking of this as a hands-on "Hack Session", or is this more like a presentation / mob programming type of thing?

**Comment by ioannisa** [comment]
I can do hands on, or presentation, its all the same to me.  But with code, I will need less slides lol, so I need to know if I am to prepare extra slides, or not.  At the moment I have very basic slides, cause I did the same presentation in the GDG Heraklion with live code.

**Comment by maounis** [comment]
👍

**Comment by zakkak** [comment]
I am just gonna leave the following links here:

https://on.acm.org/t/what-can-kotlin-do-for-me/568

https://www.youtube.com/watch?v=YbF8Q8LxAJs

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
