### ISSUE TITLE
Revisiting topics

### ISSUE THREAD

**Issue by Detys** [devstaff-crete/DevStaff-Heraklion#196]
Meetups have been held consistently for the past few years. Having only joined relatively recently I feel like I have missed out on some rather interesting topics and considering that keep seeing new people at every meetup I’m sure I'm not alone.
Taking into consideration that finding speakers for some topics is a problem maybe it’s time we consider revisiting topics that have already been discussed. I believe it will be a great opportunity for:
1. New members to discover things they might have missed
2. As a refresher course for people that were present 
3. As a retrospective on what has changed since the original discussion

**Comment by irinikp** [comment]
I agree!

**Comment by gsaslis** [comment]
I can't believe it's taken me so long to reply to this one. 

@Detys you are absolutely right. We need a new way to come up with topics and schedule upcoming meetups. 

This issue has been brought up in a few org team meetups and in the last one we agreed to try to reach some decision for the new academic year (i.e. starting October). 

Please join us in the next [Org Team meetup](https://www.meetup.com/preview/DevStaff-A-Developer-Community-Gathering-In-Crete/events/243167422) where this will be the main topic on the agenda.

**Comment by sonaht** [comment]
Closing this. Has been inactive for years.

Please reopen if you feel this should remain.
