### ISSUE TITLE
Design for developers

### ISSUE THREAD

**Issue by sugarenia** [devstaff-crete/DevStaff-Heraklion#20]
I'm writing a book on the subject (http://book.sugarenia.com) so I could get the main points in a presentation, if people are so inclined.

The idea is to present some basic design principles in a way that developers can relate to. It's mostly about web/UI design, but most of the principles can be applied to any kind of design, really.

A rough skeleton:

* Colour
* Typography
* Layout
* Usability
* Graphics
* User testing
* Copywriting

**Comment by fadamakis** [comment]
:+1:

**Comment by andronikigr** [comment]
thumbs up

**Comment by andronikigr** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by gsaslis** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by akatopo** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by sbehnsen** [comment]
:+1: 
Having seen a lot of software projects over the last 3 decades it is my experience that very often (I would still say in over 50% of the cases) developers think very differently about the useability of software than the users. 
Still today the workflow (how the user is going to use an application) seems to come very late in the development process (if at all). The result are lots of applications that do great things but a difficult or strange to use. I find that particular part of the topic must interesting and i am interested in presentations and expecially dicussions about this.

**Comment by Hotshuk** [comment]
:+1:

**Comment by yiasou** [comment]
:+1:

**Comment by markop** [comment]
:+1:

**Comment by karvounistas** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by gfragiadoulakis** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by kboutsika** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by pappaschris** [comment]
:+1:

**Comment by msti** [comment]
:+1:

**Comment by stavrosAd** [comment]
:+1:

**Comment by kabitakis** [comment]
This is the topic of the 4th meetup!
Thank you all for your votes!
