### ISSUE TITLE
Working with git submodules and subtrees

### ISSUE THREAD

**Issue by npapnet** [devstaff-crete/DevStaff-Heraklion#201]
Consider the following use cases:
- you are developing a project and you are using a bleeding edge version of a library. In order to share the repository with other developers/machine you want to link the version of your application to a specific library (*DISCLAIMERS*: a)ok I know many node.js does that already, but for other poor sods that still have to program in other platforms, b) Ok, there is the obvious solution to copy everything.)
- you are developing a project and a library starts to have a life/usefulness of its own. Then its best to separate it from the main repository and put it in its own repo. However you don't want to mess too much with the hierarchy structure of your project. 

Git has *subtrees* and *submodules*, which can be useful in both of those use cases above. It would be nice to listen from people who have used them:
a) general rules of thumb when to use what
b) potential pitfalls in one or the other or both. 
c) other ways to solve the above problems.

**Comment by gsaslis** [comment]
@npapnet was this covered in https://www.meetup.com/devstaff/events/246863163/ ? 

Should this be closed?

**Comment by zakkak** [comment]
No, we didn't cover submodules.

**Comment by sonaht** [comment]
Guys is there still interest in this one ?  If not I suggest we close this and move on

**Comment by DaKnOb** [comment]
I think we should close this one.

**Comment by sonaht** [comment]
Ok then i guess if some one wishes to reopen one can certainly do it
