### ISSUE TITLE
Cannot join the slack group

### ISSUE THREAD

**Issue by jamiedarcher** [devstaff-crete/DevStaff-Heraklion#216]
Hey I came to the meeting this month but can't get on the Slack group
Email sign-ups for Slack group disabled.

![image](https://user-images.githubusercontent.com/6596910/35148544-449cfcde-fd1b-11e7-9fe6-f89d29a41f22.png)

**Comment by gsaslis** [comment]
@jamiedarcher plz drop an email to info@devstaff.gr so we can send you an invite.

Slack is silly like that - does not allow ppl to sign up, rather it needs invites to be sent to specific email addresses. 

There are a couple of external apps that help automate this process but we haven’t got round to setting it up...

**Comment by jamiedarcher** [comment]
Sent you the email thanks

**Comment by sonaht** [comment]
@jamiedarcher I have send you an invite using your github email as well as the one which made the request to the info@devstaff.gr

Please check your emails

Thanks
