### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by nkyriazis** [devstaff-crete/DevStaff-Heraklion#22]
It may be useful to discuss Unit testing across the following axes:
- What it is
- Why use it
- How to use it
  - Domains: Languages, systems, OS, ...
  - Conventions/Tools
  - Best practices
  - Coverage
  - Automation
etc..

My expectations from attending such a discussion would be to:
- be convinced that I **absolutely** need to incorporate unit testing in my project, as is rumored :)
- be given an idea on how to formalize the process of unit testing so that I am not lost in it

It is a big topic, but I feel it could be concentrated, by some expert, into at least an overview and some meaningful pointers.

**Comment by padeler** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by gsaslis** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: 
(disclaimer: still counts as one)

**Comment by DaKnOb** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: 
(Disclaimer: Counts as 6)

**Comment by greenman18523** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by kormic** [comment]
:+1:

**Comment by sbehnsen** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Hotshuk** [comment]
:+1:

**Comment by Sifis-Develop** [comment]
:+1:

**Comment by papoutsakos** [comment]
:thumbsup:

**Comment by svelon** [comment]
:+1:

**Comment by ghal** [comment]
:+1:

**Comment by kboutsika** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by evmaniadi** [comment]
+1

**Comment by evmaniadi** [comment]
:+1:

**Comment by gzografa** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:
However the topic title should be renamed to Test Driven Development and we should also touch issues like BDD, ui tests, integration tests and so on.

**Comment by zakkak** [comment]
The way the topic is described by @nkyriazis it seems closer to regression testing than test driven development.  We could add test driven development as a subtopic though, since you cannot perform test driven development without unit testing.

Regarding the title I personally believe Unit Testing is OK as is, and it would be better to avoid renaming topics at such a late stage (it is pretty popular already) to avoid potential confusion.

**Comment by papoutsakos** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by JChrist** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by andronikigr** [comment]
:+1:

**Comment by kabitakis** [comment]
So, our 5th meetup is scheduled for December the 10th, under the title Unit Testing!
Thank you all for your votes!
