### ISSUE TITLE
GDPR Mythbusting and Awareness

### ISSUE THREAD

**Issue by estavrak** [devstaff-crete/DevStaff-Heraklion#226]
A few of the key points that can/should be covered:

- Privacy and Data Protection as a Fundamental Right
- A few core definitions
- Territorial scope
- Principles of processing
- Grounds for processing
- Data subjects rights
- Data transfers
- Data breaches
- Administrative fines & sanctions
- Data protection impact assessment
- Compliance framework and relative standards.
- What is a risk to the Rights and Freedoms of individuals?
- What about the UK?

Take a deep breath, this is likely to be a long one.

**Comment by estavrak** [comment]
🔈

**Comment by mzampetakis** [comment]
🔈I don't know if we can split it somehow, but I could talk about the DPO (role, obligations,  rights), and how a company can be prepared...

**Comment by sonaht** [comment]
Closing this as it is the next topic for meetup may 2018
