### ISSUE TITLE
We don't know each other

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#24]
One of the comments from yesterday's first event was that there were a lot of ppl we didn't know, or ppl we did know but we didn't really know what they're working on atm.. 

It would help if we did, cause we could then find others with similar interests and start chatting to them or get working with them on pet projects, etc. 

A suggestion from my side would be for everyone to add a short profile (few words) on meetup.com, so that we could even look back and see what sort of stuff the new guys we meet every time are involved in.. 

Any other suggestions?  (e.g. LinkedIn profile links?)

**Comment by DaKnOb** [comment]
Maybe we can just give every person 2' on the next event to tell a little bit about {him,her}self. We should have done this in the first meeting, but nvm. :P

**Comment by sbehnsen** [comment]
:+1: I agree with DaKnOb.

Also (see different thread about alternative communication), it would be nice to have somehting like a forum (preferably on our website) which would allow us to have a thread where everyone can write about themselves. 

This would also allow us to threads for people looking for certain experience, cooperation etc.
Both for smaller meetings as well as for new peojects where someone might look for programmers etc...
This is one of the most important assets that Def Staff could bring to me.

**Comment by gsaslis** [comment]
yes this suggestion was on the table for the first meetup, we ended up deciding that we didn't want to put people 'on the spot' without introducing 'ourselves' / DevStaff itself first, so we thought we'd leave this for the 2nd meetup.. 

I am in favour of the short 1' min intro (even though with ~50 ppl, that would be close to an hour) but I agree it would be great value! 
Does anyone have a specific format for this that they'd like to recommend?

**Comment by frcr** [comment]
Maybe a LinkedIn group would do? I'm not only a usual uninteresting student, but I also start to shake and tremble and forget languages when speaking to more than three people. =(

**Comment by zakkak** [comment]
On 07/14/15 13:15 , frcr <notifications@github.com> wrote:
> Maybe a LinkedIn group would do? I'm not only a usual uninteresting student, but I also start to shake and tremble and forget languages when speaking to more than three people. =(
>

I totally understand you, but you should consider this a great
opportunity to change this.  After giving such talks/presentetions a few
times you will get more comfortable and improve your confidence.

Giving a short talk to a friendly environment, like the meetup, should
never make you feel uncomfortable, nobody is going to judge you or
anything even if you won't make it to the end.

**Comment by padeler** [comment]
Apart from the 2' personal presentation, I like the idea of an online way to lookup people and skills. I know that if I listen to 40 people describing what they do, I will probably forget most of the information immediately. 

A linked-in profile or a small description on the meetup account would be best.

**Comment by gsaslis** [comment]
An alternative idea (I was told at #AgileCrete) was to use a few stickers in our next meetup:
Each person can write 4 stickers with topics that interest them / would like to talk about and stick them on themselves... 
Then we can have an informal networking session to give ppl time to chat and discover who knows what, etc.  simply by walking around and looking at each other's stickers..   ; )

**Comment by sbehnsen** [comment]
personal presentation and stickers... All not bad, but I still believe that we should have an online method as well. Not everyone will be able to speak to everyone at a meeting every month. It would be good to have a Forum or similar where people can leave their CV/interests as well as the possibility to seek out certain skills directly.

**Comment by DaKnOb** [comment]
Let's not keep it too formal with CVs etc. Just a short bio (\leq 140 characters) that you could have somewhere like your Twitter account. 

DaKnOb

**Comment by zakkak** [comment]
1. [linkedin](https://gr.linkedin.com/in/zakkak)
 1. [personal website](http://foivos.zakkak.net/)

**Comment by webdevgr** [comment]
1. [linkedin](https://gr.linkedin.com/in/webdevgr)
2. [personal website](https://webdev.gr)

**Comment by zakkak** [comment]
I think we can close this issue

**Comment by gsaslis** [comment]
the issue itself is definitely not solved (there is still no formal way of getting people to introduce themselves), but there doesn't seem to be any progress, so you might be right... 

what's more I am getting some mixed feedback about the stickers idea... Even though we had abandoned it for some time, the issue came up during an Org Team session (not by me) and everyone agreed we should start using them again. 

if you think it doesn't work / "einai americania" / you don't like it / etc. please share that here. 

Any other suggestions are also **more** than welcome!

**Comment by zakkak** [comment]
I am one of those guys against the stickers, so I'll give my point of view.

I find it weird looking at someones shirt to see a bunch of keywords that are supposed to describe his interests/personality. If I am facing him I can ask him directly. If I am in a circle and not directly facing him I find it creepy (like checking his facebook page before talking to him) to try and read what is written on his sticker. After all you don't get to know someone because you know he is interested in Django.

I feel the same thing about conference badges, where some guys come in front of you and instead of asking what's your name and affiliation they try to read the badge and then talk to you... (at least they always talk to you, it would be much more weird if they read the badge and then just walk away :P)

I don't have any alternative suggestions. I believe joining a discussion circle after the presentations is the best, most natural, and genuine way to meet the people in it.

**Comment by gsaslis** [comment]
i'm closing this primarily due to inactivity. 

I would invite folks who come across this to actively try and do one thing: speak with one person they hadn't met before at every meetup.  ; )
