### ISSUE TITLE
[Hack session] Docker (containers) workshop

### ISSUE THREAD

**Issue by sonaht** [devstaff-crete/DevStaff-Heraklion#241]
A hands-on session to grasp some of the main concepts related to docker and containers in general

Please leave a +1 if interested.

Also suggest a particular issue that you might wish to be addressed.

https://doodle.com/poll/bbp58m3biqaw58pr

Date and Venue:

Date: 31 May 2018
Time: 20.00 - 22.00
Venue: Office12

**Comment by markop** [comment]
:+1:

**Comment by sksksksk** [comment]
:+1:

if timing permits due to me being in Chania.

**Comment by gsaslis** [comment]
@sonaht how about setting a time and place for this next week?

**Comment by sonaht** [comment]
@gsaslis did you vote on doodle ?

**Comment by gsaslis** [comment]
@sonaht i'm not sure i will be attending, but since this is a requirement for the k8s one, i think we should go ahead and schedule it. Seems there's enough ppl on there already anyway

**Comment by sonaht** [comment]
Guys it looks like Thursday 31/3 - 20.00-22.00 is our day. I am trying to secure the place so I will keep you posted

**Comment by gsaslis** [comment]
@sonaht 31/5 right?

**Comment by sonaht** [comment]
Τα ξαναλέω άλλη μία φορά και πάλι ξανα: 31/5, διότι κάποιος δεν το βλέπει

**Comment by sourcegr** [comment]
Να ρωτήσω, είναι σωστό ότι θα γίνει στις 31/5;

Παρακαλώ επιβεβαιώστε!

**Comment by gsaslis** [comment]
@sourcegr einai swsto. to exoume pei toulaxiston 3 fores ws twra. 

<img width="369" alt="screen shot 2018-05-25 at 13 13 25" src="https://user-images.githubusercontent.com/2420882/40539445-772f9fc0-601d-11e8-8bb6-50533302b06c.png">

NOT!

**Comment by kounelios13** [comment]
Θα βγεί κάποια ανακοινωση για να το δηλωσουμε στο meetup.com?

**Comment by gsaslis** [comment]
thanks @kounelios13 ! 

To evgala sto meetup nwritera

**Comment by sonaht** [comment]
Το κλεινω, έχει βγει ανακοίνωση, όπως επίσης και το level 2 το οποίο και έκλεισε ήδη από συμμετοχές.  Να δούμε πως θα πάει και ίσως κάνουμε και κάποιο άλλο μετά.
