### ISSUE TITLE
[Hack session] about Log Aggregation stacks like ELK 

### ISSUE THREAD

**Issue by vanton1** [devstaff-crete/DevStaff-Heraklion#249]
I have some subjects in mind that could help people working with Elastic or other similar stacks. I can show to whoever is interested how to migrate, for example,  from _ELK5.6.3_ to _ELK6.X.X_ and moving to Elastic Cloud at the same time.
If there is interest we can work on a couple of related subjects and organise a hacksession. I would prefer the 1st or 2nd of August as I will be in Heraklio.

**Comment by gsaslis** [comment]
is this still on for next time you're in town maybe @vanton1 ?

**Comment by vanton1** [comment]
Yes we can do it if there is interest from the community

**Comment by vanton1** [comment]
Possible dates https://doodle.com/poll/37vvdrq92gpt65xz

**Comment by gvre** [comment]
https://www.meetup.com/devstaff/events/258465480/
