### ISSUE TITLE
Change logo text from "meet up" to "community"

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#289]
By now devstaff has grown into something much more than a meetup.  

I think our logo is outdated and should be adapt to cater for this change. 

/cc @kabitakis @sonaht @padeler @gvre @mzampetakis @nickorfas @DaKnOb @svelon @sugarenia @sbehnsen @estavrak

**Comment by svelon** [comment]
Since we are looking into the logo thing, we could also change it altogether. I had a brief discussion with Michalis Meimaroglou (https://www.micmei.gr/), who is willing to make one for free, as a sponsorship.

**Comment by gsaslis** [comment]
@sonaht / @kabitakis so I take it this is fixed now, right?

closing (please reopen if it's not)
