### ISSUE TITLE
OKRs - Objectives and Key Results

### ISSUE THREAD

**Issue by vanton1** [devstaff-crete/DevStaff-Heraklion#291]
I would propose we run a meetup around OKRs and maybe other performance management and team alignment methodologies. I am willing to make a presentation or even a workshop if there is interest from the community.
``Objectives and key results (OKR) is a framework for defining and tracking objectives and their outcomes used by Google, LinkedIn, Uber, Walmart etc.
The development of OKRs is generally attributed to Andy Grove the "Father of OKRs", who introduced the approach to Intel during his tenure there``
 
1. What OKRs are
1. Why OKRs
1. Who use them
1. Experience sharing from teams and companies already use them

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
