### ISSUE TITLE
[Hack session] Hacking your "smart" thermostat

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#298]
Hello all, 

I recently got my hands on a "smart" thermostat. It is not actually smart at all, it just connects to the wifi and lets you control it (only basic staff) from your smartphone. Anyway, so I decided I could use it's connectivity to collect some data and do some analysis on them.

This hack session will take you from "Connecting the thing on the wall" to "I have an ELK stack with data of my house temperature etc.". In the process we will (if time permits):
1. Learn how to get what we want even if it's not documented (reverse engineering, but in our case mostly decompiling)
2. Find out how the REST API works through some trial and error
3. Get our first data
4. Setup ELK in a giffy
5. Glue everything together

**Comment by gsaslis** [comment]
Let me just leave this here:

https://twitter.com/codepitbull/status/1086750509774655494?s=21

**Comment by zakkak** [comment]
Please vote on the following doodle poll for the date of the hack session:
https://doodle.com/poll/fmz8wks4dw2q9ki2
