### ISSUE TITLE
Deep Learning

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#30]
I wouldn't really put this down as a topic suggestion, but I'd love to spend an afternoon (or two) with any ppl who are interested in the field and understand a little more on this. 

I guess I'm thinking more of sth along the lines of an open discussion and/or hack session(s)... 

Any takers?

**Comment by DaKnOb** [comment]
Depends on the date.. ;-)

**Comment by frcr** [comment]
I'm totally onboard. The date doesn't matter for me, neither does the time. Though I would prefer morning/midday over evening/night, but I'm going anyway.

**Comment by kabitakis** [comment]
@gsaslis then it sounds like it should be a topic :P

**Comment by padeler** [comment]
Great idea @gsaslis, count me in :)

**Comment by nkyriazis** [comment]
:+1:

**Comment by sonaht** [comment]
Ok guys thumbs up if this, as a topic, does it for you

**Comment by padeler** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by papoutsakos** [comment]
:thumbsup:

**Comment by ggeorgop** [comment]
:+1:

**Comment by frcr** [comment]
:+1:

**Comment by sonaht** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by msti** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by ManosGEM** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by kabutz** [comment]
+1

**Comment by stivaktakis** [comment]
:thumbsup:

**Comment by VaggeliC** [comment]
👍

**Comment by gsaslis** [comment]
We’re looking for 1-2 more speakers for this one, for April’s meetup. Please let me or one of the org team know if you have sth to share ;)
