### ISSUE TITLE
New label for completed hack sessions

### ISSUE THREAD

**Issue by gvre** [devstaff-crete/DevStaff-Heraklion#309]
**Problem**
There is no easy way to see the completed hack sessions on [this page](https://github.com/devstaff-crete/DevStaff-Heraklion/issues?q=is%3Aissue+is%3Aclosed+label%3A%22Hack+Session%22)

**Proposal**
A new label `Done` (green color) could be used in those, and maybe other, cases.

What do you all think about that?

**Comment by gsaslis** [comment]
Agreed on the issue  you’re bringing up.

 I think currently the only way to verify that would be to check against the past events on meetup.com.

 As far as I can remember, all the events that have taken place should exist there  ( perhaps with the exception of a couple of org meet up’s )

**Comment by gsaslis** [comment]
I am in favor of bringing this information into this repository as well ( what event has taken place, versus what event was proposed but did not eventually happen ), I would just like to:

*  Ideally do it in an automated way, in relation to the meetup.com platform 
*  I get that that might be difficult/too much work to be worth the effort, so if we do it manually, I would like to see a consistent approach for both main events, as well as hack session ( this means that if we go with the label solution, I would expect `done` to be applied to both `Topics` and `Hack Sessions` )
* Leave some documentation behind, explaining how we use/apply play bot leave some documentation behind, explaining how we use/apply labels.

**Comment by gvre** [comment]
@gsaslis 

> I think currently the only way to verify that would be to check against the past events on meetup.com.

There's also a list with all completed hack sessions [here](https://github.com/devstaff-crete/DevStaff-Heraklion#hack-sessions-video_game)

> I am in favor of bringing this information into this repository as well ( what event has taken place, versus what event was proposed but did not eventually happen )

That would be useful.

> Ideally do it in an automated way, in relation to the meetup.com platform

I think we can start doing it manually for now and will see how it goes.

> leave some documentation behind, explaining how we use/apply labels

That's good, too. I believe, if most people agree, we could start with the `Done` label, since it's a simple task. What do you think?

**Comment by gvre** [comment]
@gsaslis TIL that [labels](https://github.com/devstaff-crete/DevStaff-Heraklion/labels) can have a description. I think it's a good idea to use that field as documentation.

**Comment by gsaslis** [comment]
TIL indeed. 

how about "Has Taken Place" instead of "Done" ?

**Comment by gvre** [comment]
It depends on where do we plan to use this label. `Has Taken Place` is more specific to events (meetups, hack sessions), `Done` is more generic, so it can also be used for other types of issues.

**Comment by gsaslis** [comment]
well, yes, but, as they say, YAGNI ;)

**Comment by gvre** [comment]
¯\\_(ツ)_/¯

I'm fine with both of them, but I think we need feedback from others, too.

**Comment by mzampetakis** [comment]
If we intend to use it only for Hack Sessions and/or Topics I suggest that we use the '''Has taken place''' as we can use the '''Done''' label to other issues...

**Comment by gvre** [comment]
I'm closing this and will use the `Has Taken Place` as label. We can revise in the future, if needed.
Thanks @gsaslis @mzampetakis !
