### ISSUE TITLE
Not just text editors

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#31]
I propose a hack session on VIM and GNU Emacs, the two most mature and popular text editors.

* Newcomers could learn the reasoning behind all these weird key-bindings.
  * Maybe experienced users should try and explain why they (VIM and GNU Emacs) are so great.
* Experienced users could share their hacks, best practices, work flow etc.

**Comment by padeler** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by gsaslis** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by zakkak** [comment]
I believe we should change the label of this issue to `Hack Session` and probably split it so that we can have a hack session on VIM and another on Emacs.

If anyone of you considers himself an Atom experienced user I would like to see some advanced editing on it as well.

**Comment by kabitakis** [comment]
@zakkak we can close this one if you want (since you are the one who proposed it) and you should open other tickets for the hack sessions, following the guidelines described in the issue #63 . What do you think?

**Comment by zakkak** [comment]
Moved to #65
