### ISSUE TITLE
Topic Count 

### ISSUE THREAD

**Issue by sonaht** [devstaff-crete/DevStaff-Heraklion#32]
What follows is a count of thumbs up / thumbs down for the existing topics.

This will be updated on a regular basis and serve only as a quick way to see what is happening.

Follow this url to count the votes: https://powerful-sands-5380.herokuapp.com/

Topic | Thumbs UP | Thumbs Down
------------ | ------------- | ------------
LaTeX #50 | 3 | 0
Password and Key Management #49 | 10 | 0
Django Basics: Building a simple web application #47 | 11 | 0
Start-Ups, Spin-offs and other forms of bootstraping a company #36 | 14 | 0
Working at (extremely) large scale #35 | 7 | 0
Docker and alternatives #34 | 6 | 0
Developing with security in mind #33 | 14 | 0
Not just text editors #31 | 6 | 0
Deep Learning #30 | 11 | 0
Continuous Integration #29 | 5 | 0
Unit testing #22 | 24 | 0
Sass #19 | 11 | 0
IoT (Internet of Things) #15 | 13 | 1
Design for developers #20 - CLOSED - 4th meetup | 22 | 0
DevOps #14 - CLOSED - 3rd meetup | 16 | 0
NodeJS #13 - CLOSED - 2nd meetup | 23 | 0
Git #NaN - CLOSED - 1st meetup | 4| 0 

**remember** that only if you :+1: a vote will be counted.

(last update 15/10/2015 10:19)

**Comment by mKontakis** [comment]
:thumbsup:

**Comment by zakkak** [comment]
It would be nice to keep the thumb counts for past topics somewhere just for reference (without having to go through the logs).  Maybe a second array with 4 columns (1 topics, 2 thumbs up, 3, thumbs down, 4 meetup number) would do the trick.

**Comment by gsaslis** [comment]
gitlab supports this nicely (out-of-the-box).. 

looks like there's a looooong discussion about this on github: https://github.com/isaacs/github/issues/9

**Comment by kabitakis** [comment]
I edited the table in order to keep the counts in a way for now.

**Comment by DaKnOb** [comment]
Maybe you should include the original post as a +1 and not require a separate +1 from the author. In most if not all cases they are giving their +1..

**Comment by gsaslis** [comment]
yes, an easy way to implement this is to simply start counting from 1 (not from zero!)   ; )

**Comment by DaKnOb** [comment]
And of course exclude the :+1: from the topic author if it exists.

**Comment by kabitakis** [comment]
I don't think it's an issue since we're talking about just one vote (n+1). We're missing some more votes from people voting using :thumbsup: instead of :+1: and we should agree if we mast count those votes or not. But then, we should probably agree on :metal: also.. and so on. What do you think? I'm a fan of the keep_it_simple approach.

**Comment by sonaht** [comment]
Guys lets keep this simple...use only ":+1:" to cast a vote and the author as well to cast one!!!

**Comment by zakkak** [comment]
:+1:

**Comment by kabitakis** [comment]
Let me announce that the topic for the 4th meetup has been voted: Design for developers #20
The meetup date is going to be 12/11/2015

**Comment by kabitakis** [comment]
I think we can close this one since we have deployed: http://analytics.devstaff.gr/
