### ISSUE TITLE
Mocking Services

### ISSUE THREAD

**Issue by irinikp** [devstaff-crete/DevStaff-Heraklion#322]
- What is service mocking? 
- How do I intercept 3rd party calls?
- Present tools, like Mockery

**Comment by gsaslis** [comment]
@irinikp is this meant as a hack session?

 We might have a meet up coming up on testing,  if you would like to present this as a talk there ...?

**Comment by irinikp** [comment]
I guess it could be both. I am not ready to present anything yet. I am ready to watch someone talking about mocking though :P

**Comment by gsaslis** [comment]
@irinikp ok great! 

don't worry, you'll get plenty of time to prepare, even if this topic does get voted. 
thanks!

**Comment by irinikp** [comment]
In that case I can just present my WIP, trying to mock a REST API

**Comment by nickorfas** [comment]
@irinikp check if http://wiremock.org/ can cover your needs (it also provides standalone mode & configuration via JSON -> Programming Language agnostic).

I haven't used it to be honest, but some time ago I had checked its features and I believe it is pretty cool.

**Comment by irinikp** [comment]
Thanks @nickorfas I’ll check it. I’m actually interested not only in testing an external API (which we shouldn’t mock if we don’t own) but maybe mocking my own class that uses this API. I’ll update as I go
