### ISSUE TITLE
Move devstaff introductory presentation into an open format

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#328]
As @mzampetakis and @kouts suggested, the presentation should move to an open (source) format so anyone can submit PRs through github, to suggest changes made to that presentation.

**Comment by gsaslis** [comment]
@mzampetakis / @kouts thanks for volunteering!! 

We welcome new PRs!

**Comment by kouts** [comment]
Let's hear some suggestions about presentation formats,
I for one like [slides.com](https://slides.com/)

**Comment by gsaslis** [comment]
me too. 👍 

btw is that something that we could somehow all have access to edit ?

**Comment by irinikp** [comment]
I have used [reveal js](https://github.com/hakimel/reveal.js/) and I really enjoyed it so far. 
You upload all project files, and the whole presentation's content can be in a single file index.html, although you can organise each slide to a different file, if you want to. 
I haven't tried slides.com though to know their difference

**Comment by mzampetakis** [comment]
I have also used slides.com and found it really good and easy to use!
However I am not sure haw easy & fast is to create and maintain a presentation using reveal.js.
@irinikp could  you please provide some more information on this ?

**Comment by irinikp** [comment]
[https://revealjs.com](https://revealjs.com/)
I just realised that slides.com **is** reveal.js but for non coders :P
> Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at https://slides.com.

**Comment by mzampetakis** [comment]
Please note that the person who makes this intro speech has to edit it just in order to add the meetup's schedule (topics, speakers, breaks etc).

**Comment by kouts** [comment]
So I think I can try recreating the introductory presentation in [https://slides.com](https://slides.com).
I will need the existing presentation as a reference, is it available somewhere?
If not, can you please @gsaslis share it with us?

**Comment by gsaslis** [comment]
@kouts / @mzampetakis / @irinikp i've uploaded the intro (in 2 formats) in this branch: https://github.com/devstaff-crete/DevStaff-Heraklion/tree/devstaff-intro-html/documents

please let me know if you need anything else ;)

**Comment by irinikp** [comment]
thanks @gsaslis I'll check it soon

**Comment by kouts** [comment]
I have completed the conversion of  @gsaslis .key presentation into slides.com format.
You can view the end result here: https://slides.com/michaliszampetakis/devstaff-intro/fullscreen 
I tried my best to adhere to concepts already set by the original presentation (such as different colors
for different sections etc) and also apply a constant theme / look n feel throughout. 

One thing that's missing is the internal transitions of the slides, hopefully, someone with keynote
can help me with this.

**Comment by mzampetakis** [comment]
Thanks to @kouts (👏) the presentation has ported to slides.com with an open format (html / js). Where do you suggest to publish this? At this repo or a new one?

**Comment by nickorfas** [comment]
Congrats @kouts !
I would propose to upload it on this repo (just like our /designs/logo etc).
