### ISSUE TITLE
Developing with security in mind

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#33]
As more and more services are being deployed on the cloud or on devices that are almost always connected to the cloud/web, I believe developers should become aware of penetration testing techniques and tools to help them protect the end-users.

I would like to hear about:
 * Best practices
 * Popular tools
  * Automated penetration testing (that could probably be hooked to CI (#29)
  * Sanitizers
  * Fuzzers
 * Security focused static analysis tools
 * ... (if you are familiar with the topic please add more)

**Comment by sonaht** [comment]
@zakkak very very interesting subject. It surely touches on the more/most advanced issues albeit one of the most basic that form the fabric of infrastructures in general.

I would suggest a minor title change to "developing with security in mind", in order to get to the bottom of this by starting from the beginning. 

The sub topics could be
*  Penetration testing
*  Testing in general (security in mind)
*  Certifications and Protocols
*  Code review

and more.

**Comment by zakkak** [comment]
:+1:

**Comment by sonaht** [comment]
:+1: 

This is a great subject I must say ...again

**Comment by padeler** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by karvounistas** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

If I am in Heraklion I can help with this topic.

**Comment by eirinikp** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:

**Comment by jvalsam** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by gzografa** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by agougousis** [comment]
:+1:

**Comment by ggeorgop** [comment]
:+1:

**Comment by koskonstant** [comment]
:+1:

**Comment by gvre** [comment]
:+1:

**Comment by maounis** [comment]
:+1:

**Comment by kabitakis** [comment]
Hey all! This one has been decided as the topic of our 7th meetup on February 11, 2016. Are there any interested speakers? If so, please comment below using the :speaker: emoji!

**Comment by nikos90** [comment]
Is it possible to schedule meetings on weekends, so we can attend too?
I am located in Rethymno and it isn't easy to attend on Thursdays.

**Comment by kabitakis** [comment]
Well, I think it wouldn't be possible for the next two meetups, which have been arranged. We've already discussed this issue during a beerup - beer meeting of the community to take decisions on various issues - and most people involved are ok with the day. However, we are an open community and you can open a new issue suggesting your ideas. Maybe we could also start a new meetup series in Rethymno, or presenting some topics there. There are lots of options we can discuss if you are interested.

**Comment by nikos90** [comment]
Sure! :)

**Comment by DaKnOb** [comment]
:speaker:

**Comment by zakkak** [comment]
Please add the topics you can/are willing to cover when you volunteer as a speaker.  This way we can see the coverage of the topic and if we are missing anything.

**Comment by kabitakis** [comment]
And we can also check the speakers in our analytics app: http://analytics.devstaff.gr/?user=devstaff-crete&repo=DevStaff-Heraklion&labels=Topics&state=closed&term=:speaker:
:)
