### ISSUE TITLE
Website Accessibility

### ISSUE THREAD

**Issue by irinikp** [devstaff-crete/DevStaff-Heraklion#347]
What is website accessibility? 
Why do we need it?
How can we move towards this direction?
How do we test accessibility?

**Comment by irinikp** [comment]
In case of interest I believe I can find a speaker

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
