### ISSUE TITLE
Working at (extremely) large scale

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#35]
Running a personal mail server or a PHP application like Wordpress is extremely easy. Using svn or git for code is something we've been taught (:P). We all know how to do it, and probably we're all doing it. 

But what happens when you scale to hundreds of users or thousands of visits? 
You start using more VMs, load balancers, move to git, etc.

What happens when you scale to thousands of users? What about millions of users? What happens when traditional methods just can't keep up?

A topic that discusses:
- Software Deployment
- Server Deployment
- Server Patching
- The Cloud
- VCS'
- and a lot more

**Comment by padeler** [comment]
This is huge. Maybe a discussion on these issues could be split into multiple topics (devops, CI, etc)? 
My :+1:  is given never the less :)

**Comment by sonaht** [comment]
This is an extreme topic by far. I like it due the fact that probably is a bottomless pit of subjects, ideas and implementations. My vote for sure

:+1:

**Comment by DaKnOb** [comment]
Since many related topics are coming up, we need to decide if this will be a topic on its own or be a "chapter" in each talk it is related to. 

What do you guise think?

**Comment by eirinikp** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by ghal** [comment]
:+1:

**Comment by rzolindaki** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by gvre** [comment]
:+1:

**Comment by ghal** [comment]
:+1:

**Comment by nikos90** [comment]
:+1:

**Comment by nkvorn** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by ghal** [comment]
:+1::+1::+1:

**Comment by flouris** [comment]
:+1:

**Comment by estavrak** [comment]
:+1:

**Comment by markpapadakis** [comment]
:+1:

**Comment by Hotshuk** [comment]
:+1:

**Comment by nikcxs** [comment]
<img class="emoji" title=":+1:" alt=":+1:" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" height="20" width="20" align="absmiddle">

**Comment by kmgalanakis** [comment]
:+1:

**Comment by agougousis** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by msti** [comment]
👍

**Comment by ariel2023** [comment]
👍

**Comment by xilourgos** [comment]
👍

**Comment by gsaslis** [comment]
Scheduled for December
