### ISSUE TITLE
Start-Ups, Spin-offs and other forms of bootstraping a company

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#36]
This discussion should focus on the procedure of creating a new company.  I would prefer it to be focused on the Greek standards/laws, but it would be very interesting if we could do a short comparison with other countries as well.

Questions I believe we should answer are the following:
 1. What is a start-up?
 1. What is a spin-off?
 1. How do you start?
 1. How do I get funding?
 1. What if they "steal" my idea?
 1. Do I need to be knowledgeable in management, marketing, and other "unrelated" to software development skills?
 1. How do I recruit the first and most valuable people?
 1. Can I do it?
 1. What are the risks?
 1. What do I lose in the case of a failure?
 1. .. please add more

**Comment by sonaht** [comment]
Very interesting. My greatest issue was funding in certain endeavours!!

:+1:

**Comment by DaKnOb** [comment]
:+1:

I'd like to see more about other countries since starting a company right now in Greece might not be the best decision one can make, but some general talking is also good.

**Comment by gsaslis** [comment]
:+1:

**Comment by frcr** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by maounis** [comment]
:+1:

**Comment by snikiforos** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by msti** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by stavrosAd** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by sugarenia** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by zakkak** [comment]
Relative, but mainly targeted to researchers:

ΘΕΜΑ: InnovCrete Workshops: 29-30 October 2015

ΑΠΟΣΤΟΛΕΑΣ: Rodanthi Lasithiotaki - Secretariat IMBB [mailto:rodanthi@imbb.forth.gr]

Παρακαλούμε δείτε το σχετικό αρχείο:
http://news.uoc.gr/news/2015/21-10/innovcrete.workshop.zip

InnovCrete Workshops: 29-30 October 2015 

Innovation Management & Awareness
Innovation Capacity Building

The two workshops focus on one hand on identifying and securing IPR, IPR management, technology transfer and commercialization of research results, and on the other hand on building awareness about innovation and its impact in research organizations and SME’s, while providing an overview of Innovation Strategy (Why, Where and When to Innovate?) and Innovation Capacity (How to Innovate? With What People and Resources?). 

The workshops are organized in the framework of the EU/REGPOT project InnovCrete coordinated by Prof. M. Kokkinidis (IMBB/FORTH & UoC/Dept. of Biology).

Please submit your registration using the attached forms by October 27th, 2015. 
The workshops will take place 29-30 October 2015 (final agenda is attached) at the Science and Technology Park of Crete (STEP-C), Building B, Meeting Room 211, 1st floor.

Because the number of the participants to the workshops is limited to 30, it is highly recommended that you send back the completed form a.s.a.p

**Comment by kabutz** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by kabitakis** [comment]
So, there are some ongoing discussions about this issue. What would you say to take it out of our standard meetup process and organise a larger event instead. It's a topic where others, non-developers, would be also interested to participate and there are so many subjects we can present and discuss. We can arrange it for Saturday, Jan 30, 2016 from 10.00 to 17.00. What do you think?

**Comment by zakkak** [comment]
That would be great!

I don't really mind braking the *focus on developers*, but I believe we should still keep it to very practical things and hopefully tech companies.

PS: The presentations of the InnovCrete Workshops are available at http://www.innovcrete.eu/news.html (click on the 29-30 October bullet).  They are not of much interest to software startups but still you might find a pass through the slides interesting.

**Comment by kabutz** [comment]
Very good idea. How about we invite https://en.m.wikipedia.org/wiki/Giorgos_Stathakis too?  My accountant knows him.  In fact I think my accountant would also be interested in attending.

**Comment by kabitakis** [comment]
@zakkak yes, I didn't mention it's going to be about software companies (exclusively). My bad. However, there are many non-developers in these companies also :)

@kabutz you may have noticed that politicians are not the most welcomed people around :) And they also spend lots of time talking unproductively. Furthermore, if we invite a minister, we must also invite another 10 politicians to talk (MPs, Municipality, Region, FORTH, University and so on). However, we need to start discussing the main schedule and the goals of the event and see what to do with the politics  as we go.

**Comment by zakkak** [comment]
@kabutz I personally prefer speakers with hands on experience.  

I would like to learn from people who run a start-up or had in the past.  People who have successfully spinned-off.  Investors who spend money on such companies. Maybe some lawyers and/or accountants about the bureaucracy in Greece and the risks.  

When proposing this topic I had in mind something very practical, like a workshop that could boost/motivate people with an idea to start developing it the immediate day after the meetup.  I would like this meetup to provide solutions and not just ideas, or an overview about venture capitals and economics.

I personally do not know Mr Giorgos Stathakis, but looking at his career, he seems to be an academic with a strong theoretical background but no hands on experience.  And I am afraid @kabitakis is right about the side-effects of inviting a minister.

**Comment by kabutz** [comment]
No, I don't at all propose inviting any other politicians except this one, since he is the current "economic development" minister, at least until the next election in a couple of months time.  I thought that you were intending for this to be more of a workshop than a full-on conference, where we could have perhaps one session where we sit down with Stathakis and tell him what we would need in order to be successful in start-ups, etc.  Alternatively we could take a summary of our findings to him once the sessions are done.

I've been doing business for 37 years.  Most of the businesses I have started no longer exist.  Some are still going OK.  There are some things that I look for in a country if I want to do business in it.  Greece has a lot of human and intellectual capital to offer, but it is sorely lacking in anything to do with running businesses.  The red tape is mind boggling.  Things have improved in the last 9 years, but it is still very hard here.

Anyway, it's definitely not my call and I will shut up now :-)

**Comment by kabitakis** [comment]
@kabutz I think it's a decision to take all together (the organising committee?), but let's focus on the real thing first and add all the sauce afterwards :)

**Comment by zakkak** [comment]
@kabitakis do you think you could list here the people interested to give a talk, along with their expertise and the topic they are willing to focus on?

 If they don't fill like being listed in public maybe we could start a *private* mailing list or something.

**Comment by gsaslis** [comment]
@kabutz I think the general point is that a lot of us have given up hope in expecting politicians to change things for us, so we're looking to change them ourselves... : )
along these lines, advice from anyone with hands on experience -- and therefore your own advice, imho --  would be very useful!!  
(I am personally also against involving any politicians & officials, btw)

All in all, I love the idea of a business-oriented meetup / whatever-you-want-call-it especially targeted at tech / software companies, but yes there's lots to be discussed here, so perhaps anyone wanting to help organising that could sort out a meeting in person?

**Comment by kabutz** [comment]
@gsaslis actually my #1 message for the politicians would be: GET OUT OF OUR WAY!  :-D

**Comment by padeler** [comment]
I like the idea @gsaslis, a meeting in person would help, at least, to set the goals of such a meetup.

**Comment by msti** [comment]
Agree with @gsaslis and @kabitakis 100% I would not like to see any politicians involved. As a matter of fact I would not like to be part of something that the (any) politician will use for self promotion. In any case, we can share our findings or start an open discussion about it.

I would like to hear from people who have been there and done it. Founders to share their stories and investors to tell us what they are looking for. 
For example, the people behind the openfund http://theopenfund.com/partners/

**Comment by maounis** [comment]
I totally agree with @gsaslis, @kabitakis and @msti.

The real value for the community (devs and non-devs) is coming from the experience of people who have done this (with success on not) in Greece or elsewhere (US, UK etc), the problems they had and how they solved them.

**Comment by kabutz** [comment]
Sorry for suggesting it :-(

**Comment by msti** [comment]
@kabutz I am sure you have plenty to share in this matter from your 37 years business experience.

**Comment by zakkak** [comment]
@gsaslis I would like to help with the organization, but not before the 10th of December.  So please keep me in the circle :)

**Comment by kabutz** [comment]
@msti anybody trying to do business in Greece is at a massive disadvantage.  All I could tell you is: don't bother trying here.  It is difficult enough doing business, you don't need a handicap.  The most difficult is that it is completely impossible to plan ahead.  I understand that you've lost all trust in the Greek politicians.  It would be good for them to hear how they are affecting the economy.  I'm proudly Greek and have no intention of going elsewhere.  But it would be great if we could be more business startup friendly here.

**Comment by Sifis-Develop** [comment]
:+1: !!!

**Comment by gvre** [comment]
:+1:

**Comment by nikos90** [comment]
:+1: !!!

**Comment by zakkak** [comment]
Some interesting links https://www.reddit.com/r/YouShouldKnow/comments/3yds83/ysk_this_huge_list_to_help_you_learn_about/

**Comment by nikos90** [comment]
Is there any list of startups that are operating on Crete?

**Comment by DaKnOb** [comment]
@nikos90 Currently no, but I guess a lot of the DevStaff members work or have a startup in Crete.

**Comment by nikos90** [comment]
It would be great to gather them on a list.
Just to know what is growing around us or maybe to find the right fit for ourselves!

**Comment by DaKnOb** [comment]
@nikos90 So far we have a list of job vacancies but if others agree I suppose we can also create this list as well. 

@/all Do you think a Google Spreadsheet is good or should we have it here with Pull Requests etc.?

**Comment by kabitakis** [comment]
Let's use the repo wiki for this purpose. A page with the list and a page for each single company, would that be sufficient?

**Comment by sonaht** [comment]
I assume yes, wiki page per startup under startups main cat will be fine.

**Comment by nikos90** [comment]
That's great!

**Comment by agougousis** [comment]
:+1:

**Comment by kabitakis** [comment]
It seems March is the month we start talking about business! Thanks for voting!

**Comment by zakkak** [comment]
Since gitter is down

Θέμα: How to Startup Infornation - Kickstart the Swiss Accelerator
Ημερομηνία: 27-02-2016 08:56
Αποστολέας: Anu Oks - TTÜ Mektory <anu.oks@ttu.ee>


Dear all!

My name is Alessandra and I am leading the outreach efforts for the
Kickstart Accelerator: [1] a 3-MONTH SUMMER PROGRAM based in ZURICH
SWITZERLAND for INTERNATIONAL EARLY-STAGE STARTUPS in the fields of
FINTECH, FOOD, SMART & CONNECTED MACHINES (I.E. IOT, ROBOTICS, AI ETC.)
AND FUTURE & EMERGING TECHNOLOGIES.

We are Switzerland’s first accelerator that is backed by multiple
corporations including Switzerland's largest food retailer and producer
(Migros) and the largest telco and ISP (Swisscom) and we offer DEDICATED
MENTORS, ACCESS TO INDUSTRY PARTNERS, ACADEMIC PARTNERS AND INVESTORS.

Additionally, we provide startup teams with up to CHF 25,000 in
seed-funding (approximately $25,000) and a monthly FOUNDER STIPEND OF
CHF 1500 PER TEAM MEMBER to cover living costs and allow founders to
focus fully on building their business.

Applications [2] for our first cohort are due by 31 March 2016.

Would you be free for a quick call in the next week to talk about how we
can best reach your students to tell them about this program?

In the meantime if you are up for posting about Kickstart in any
relevant social media groups that you are part of, feel free to use one
of the sample messages posted at the bottom of my message. You can also
distribute our flyers [3] that are accessible via our media kit.

I look forward to hearing from you.

Best wishes,

Alessandra

**Comment by gsaslis** [comment]
This topic is related to entrepreneurship, so thought I'd leave a note here about 2 important events on the topic: 

* [A meetup on how to validate your idea for a startup](https://www.meetup.com/devstaff/events/258288640/), which we've set up in collaboration with the [very active folks at the Bizrupt team](https://www.bizrupt.gr/).
* My spider senses tell me @kabutz will be in Heraklion some time in the next couple of months, so we could have another session where we discuss the topic with him and learn from his experience (he has recently even released [a course on the topic](https://javaspecialists.teachable.com/p/entrepreneurially), so he clearly has a lot to share).

**Comment by gsaslis** [comment]
Just as a follow up comment - relating to Heinz's course - I forgot - and should have mentioned that it's not free, but there _is_ a free resource, in the form of a newsletter where he shares some tips I've found very valuable (and very much agree with!) : https://www.javaspecialists.eu/entrepreneurially/subscribe.jsp
