### ISSUE TITLE
Vegetarian & Vegan Pizza

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#366]
Dear all,
we have received complaints throughout the centuries, about our selection of pizzas. More specifically the lack of Vegan and Vegetarian options. I propose we get one pizza every six in a Vegan configuration, or maybe also one pizza every six as a vegetarian configuration.
What is your belief?

**Comment by sonaht** [comment]
I see no reason why this should not be the normal. Of course we can accommodate for Vegans and/or Vegetarians.

I am 100% for this, we should get at least one. 

(we must make sure that the Pizza house offers such options of course)

**Comment by pappaschris** [comment]
agree. this should be the normal. we should get at least 1 vegetarian (all pizzerias have) + 1 vegan (if available)

**Comment by irinikp** [comment]
Are there places where we can order vegan pizzas?

**Comment by sourcegr** [comment]
Well actually margarita pizzas are always present, and are vegan (unless they mean without cheese)...

It wouldn't hurt though to have some with only mushrooms / green peppers. Vegetarian pizzas are better than all the greasy salami bacon sausages sh*t they put in pizzas...

**Comment by irinikp** [comment]
Sorry @sourcegr but vegan pizzas don't have cheese :)

**Comment by sonaht** [comment]
Closing this as we already have dealt with
