### ISSUE TITLE
Pitchdeck workshop

### ISSUE THREAD

**Issue by ealefrag** [devstaff-crete/DevStaff-Heraklion#391]
Being motivated by a discussion I had with a colleague, and having attended a session over pitchdecks I thought that it would be a great start towards the product development. At least I enjoyed it big time and am willing to through a session myself. Anyone interested?

**Comment by sonaht** [comment]
Would you be interested in doing a hack session as such ?

**Comment by ealefrag** [comment]
I am closing this one off since there is no actual interest for over a year now. We could focus on bring up something more interesting.
