### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#4]
I think it would be neat if we could find sponsors that would help us cover some basic catering costs for the meetups! 

Mainly talking about snacks & soft drinks, even though i have to admit pizza would be pretty awesome!

**Comment by gsaslis** [comment]
After *public demand by the community*, I believe it's fair to add 'beer' here ...

**Comment by DaKnOb** [comment]
Pizza and beer. That's what we need. :-)

**Comment by sbehnsen** [comment]
In order to accomodate for the beer reqest, I am offering to bring 20 cold beers (Beck's since it is my favorite beer) to the next meetup. I challance others to do the same :-) (or any other amount of beers)
:+1: 

Also if found interesting, I can do a small fun presentation about solutions for continous cold beer when no electricity is available for several days... (e.g. camphing on the beach for several days).

**Comment by gsaslis** [comment]
amongst the very important issues - coming up to the 2nd meetup - is the issue of procuring pizzas!! 

would anyone mind if we offered a sponsorship to a company who would buy us the pizzas in return for e.g. a 5-min pitch (what their company does, etc)??

**Comment by padeler** [comment]
pizza is a critical issue :) . I think I am fine with a sponsor, be it a local pizza place or even better a technology oriented company :+1:

**Comment by gsaslis** [comment]
@sbehnsen is the offer still on for the beers? just let me know and we'll bring the rest... 

the amazing @kabitakis has also provisioned pizzas through a local-pizza-place sponsorship! woohoo!!

see you all tonight!

**Comment by sbehnsen** [comment]
Yes of course I will bring beer :-)
 

---
Sven Behnsen
Phone: +30 2810 244343
Mobile: +30 6974 152425 

 


  _____

**Comment by gsaslis** [comment]
Awesome!! ;)



—
Yorgos Saslis

**Comment by zakkak** [comment]
Now that pizzas and beers are the standard, do you think we can close this issue?

**Comment by gsaslis** [comment]
Hmmm... good point. 

I actually think it would make sense to publish the policy that was agreed for sponsors in the repo, so I will prepare a PR for this.

**Comment by gsaslis** [comment]
PR Submitted - **please DO review**
