### ISSUE TITLE
Moving to a different chat enviroment

### ISSUE THREAD

**Issue by HoodElliot** [devstaff-crete/DevStaff-Heraklion#402]
Well, my question is simple. Why are we still using slack?
Ok, some guys will get upset but the reason I'm mostly asking this is that we miss messages every 10.000 (EDIT: I actually thought the max messages where 100k but actually is even worse) which may sound a lot but it really isn't. So my "solution" is moving to a different free chat environment that supports unlimited messages. My suggestion is [discord.com](discord). The reason I'm suggesting this is that is similar to slack and supports unlimited messages as well as bots and other good stuff. The migration to some of you will sound hard as we already have a lot of members but some good greek phrase says "**κάλλιο αργά παρά ποτέ**". Feel free to suggest new ideas on how we can solve this message limit.

**Comment by mzampetakis** [comment]
From my perspective I would like to be able to have unlimited messages (even if I prefer to bookmark anything interesting I see!) but the people "migration" is an issue. Honestly, I believe that the active participants will willingly move to something new! The thing that is mostly concerning me is the fact that most of the people already use slack (for their work or other groups) so making them install and maintain another app might be a little frustrating.

**Comment by nickapos** [comment]
I am already using discourse. Would be happy to switch to a discourse based platform.
It's better to slack in many ways. Slack is good only for ephemeral discussions.

**Comment by sonaht** [comment]
Unfortunately I agree 100% with mzampetakis on the multiple chat systems one should/could or even is willing to maintain. I for one will not be kind at all in maintiaining yet another platform.

Having said that I would also like to have history (old messages) for all the right reasons.

This must be a decision that would involve a lot of community members in making the actual decision, as I would affect the community in its entirity !!!

**Comment by sonaht** [comment]
I am certain that this issue is currently in not considered. 

Please reopen, issue a PR or join our org meetups to state your case.

Closing this
