### ISSUE TITLE
Remove branches that are not needed

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#422]
There exist multiple `git` branches here, other than the `master`. A lot of them seem to be patches made by people directly on this repository, and not anything useful. More importantly, they all appear long merged.

An administrator should remove all branches that are no longer needed from this repository, as they can be misleading.

**Comment by DaKnOb** [comment]
People that can be assigned: @nickorfas @mzampetakis @kouts @sonaht

**Comment by mzampetakis** [comment]
I have removed lots of the branches that are no longer needed. Please ta a look and remove any other not needed!
Then we can close this issue.

**Comment by DaKnOb** [comment]
Thanks!
