### ISSUE TITLE
Django Basics: Building a simple web application

### ISSUE THREAD

**Issue by agelakis** [devstaff-crete/DevStaff-Heraklion#47]
How about a meetup about Django?
Building a simple web application using Django (the python based web development framework) using virtualenv.

*\* added the positive vote **
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by gsaslis** [comment]
been meaning to look into that for a while now...!! 
what better to way to learn about it all than a meetup / single afternoon?

:+1:

**Comment by sonaht** [comment]
gets my vote as well...
:+1:

**Comment by padeler** [comment]
yes please :) 
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by sugarenia** [comment]
:+1:

**Comment by gfragiadoulakis** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by gfragiadoulakis** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

**Comment by ggeorgop** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by ekartsak** [comment]
:+1:

**Comment by nikcxs** [comment]
<g-emoji alias="+1" class="emoji mr-1" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png"><img alt=":+1:" title=":+1:" class="emoji" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png" height="20" width="20" align="absmiddle"></g-emoji>

**Comment by mikedi** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by ChristosM32** [comment]
Very interesting 

:+1:

**Comment by gsaslis** [comment]
@agelakis would you be able to host a talk about this on thu, sep. 8th? 

Any other speakers here?

**Comment by DaKnOb** [comment]
@gsaslis @agelakis My only experience is with deploying Django apps and not actually writing them. Including dockerizing them.

**Comment by gsaslis** [comment]
@all / @agelakis : FYI - if we don't have any speakers show up by tomorrow, this will just have to get pushed down the queue.

**Comment by sifalios** [comment]
:+1:

**Comment by Sifis-Develop** [comment]
There you go ;)
:+1:

**Comment by StVak** [comment]
👍

**Comment by sonaht** [comment]
Guys we are actively seeking speakers for this presentation.

Please indicate availability with the speaker icon OR direct someone who might be willing to participate and present.

**Comment by msti** [comment]
👍

**Comment by christophad** [comment]
👍

2016-10-25 10:09 GMT+03:00 Michalis Stivaktakis <notifications@github.com>:

**Comment by VaggeliC** [comment]
👍

**Comment by gsaslis** [comment]
@VaggeliC We always struggled to get speakers for this one. 

@daknob led a hack session. 

I wonder if this should still be open...?

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
