### ISSUE TITLE
LaTeX

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#50]
An introduction to LaTeX:
- What is LaTeX?
- Why use it?
- Advantages
- Disadvantages
- Limitations?
- Tools to make it easier/user-friendly?

**Comment by padeler** [comment]
:+1:

**Comment by tzermias** [comment]
:+1:

**Comment by gfragiadoulakis** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by zakkak** [comment]
Maybe we should change this to a `Hack Session` as well.

**Comment by ekartsak** [comment]
:+1:

**Comment by hrysakis** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by ManosGEM** [comment]
👍

**Comment by gsaslis** [comment]
👍 

could we also perhaps explore `asciidoc` as part of this meetup?

**Comment by sonaht** [comment]
Closing this as we are currently managing the "next meetup topic" via a shared [form](https://docs.google.com/forms/d/e/1FAIpQLSd-xubuaYZIl0kl1B5wqy_nIE-Rq010OfUEfAdMyoSA6S9jAg/viewform)

Please reopen if you feel this should remain
