### ISSUE TITLE
Meetup 03 repository is missing

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#54]
Hi,

Could someone please upload the material from the last meetup? @sonaht maybe?

Foivos

**Comment by sonaht** [comment]
Time permitting will be done during weekend!!

**Comment by zakkak** [comment]
Thanks :)

**Comment by zakkak** [comment]
Bump

**Comment by kabitakis** [comment]
https://github.com/devstaff-crete/meetup03-DevOps
