### ISSUE TITLE
Mobile development 101

### ISSUE THREAD

**Issue by svelon** [devstaff-crete/DevStaff-Heraklion#55]
I would be very interested in learning the basics of mobile apps development.

- What languages I should use?
- What tools?
- What is the general file structure of an application?
- How can I use the device's DB? Is there any?
- What frameworks are there?
- How should I test?

I mean the complete basics, given that we all know how to write a loop and an if statement. I have absolutely no experience in that, so the presentation should be done by somebody else...

**Comment by padeler** [comment]
:+1:  I like the topic! To me, It looks like the mobile landscape is split between 2 platforms these days (android, ios). Apart from the tools and basic intro, It would be nice to have a comparison with pros and cons from each side.

**Comment by sonaht** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by andronikigr** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1: and @kritsot definitely!

**Comment by kritsot** [comment]
And of course as also mentioned in gitter channel, there is also the hybrid approach.
One codebase (to rule them all :P) and the easiest approach if you have a web background, since you don't have to learn a new language.

**Comment by Pepemakis** [comment]
:+1:

**Comment by msti** [comment]
This is a very nice but broad topic. 
I would be interested in learning more about the hybrid approach. 
A hands on with phonegap or similar framework would be nice.
:+1:

**Comment by kritsot** [comment]
phonegap (or cordova) provides you only with access to the native features (GPS, accelerometer, camera, sqlite etc) so it can't be used on its own. You have to use another framework to  structure the rest of your code (jquery Mobile, sencha, ionic [our choise, these days], etc...)

**Comment by flouris** [comment]
:+1:

**Comment by kritsot** [comment]
And of course there are other solutions that are not exactly hybrid (namely your main application is not just wrapped inside a webview) but promise to offer native performance and keep the advantage of using a single codebase (still javasript FTW!!) 
Some well-known candidates
* [Nativescript ](https://www.nativescript.org/) (which has earned a lot of hype during the last months. Opensource and supported by [telerik](http://www.telerik.com/))
* [Appcelerator titanium](http://www.appcelerator.com/product/) (I know this has been used by some of our meetup members)

Feel free to mention any other viable options

**Comment by svelon** [comment]
:+1: 
We can have an introductory presentation, about the complete basics and the comparison between each platform. After that we can talk about hybrid.

And don't forget Windows! Down with the monopoly of Apple and Google! Microsoft likes monopolies too!

**Comment by kormic** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by tzermias** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by Sifis-Develop** [comment]
:+1:
We can discuss about the hybrid and native technologies : the goodies and the difficulties. 
I agree that the native technologies are mainly three (ios, android, windows) but there are plenty of hybrid technologies that have been releases and some of us may have used them and give a feedback.

**Comment by nipapada** [comment]
:+1:

**Comment by kboutsika** [comment]
:+1:

**Comment by Hotshuk** [comment]
:+1:

**Comment by ekartsak** [comment]
:+1:

**Comment by koskonstant** [comment]
:+1:

**Comment by kabitakis** [comment]
This one has been decided as the topic of our 6th meetup on January 14, 2016. Are there any interested speakers? If so, please comment below using the :speaker: emoji!

**Comment by MariaPat** [comment]
:+1:

**Comment by greenman18523** [comment]
:speaker:
