### ISSUE TITLE
Talk: Secrets of Concurrency

### ISSUE THREAD

**Issue by kabutz** [devstaff-crete/DevStaff-Heraklion#56]
Title: The Secrets of Concurrency

Abstract:

From the first version of Java, we have been able to create multiple threads.  Initially, this was mostly used for making our GUIs more responsive.  For example, we would read a file using a separate thread from the main AWT thread, updating the GUI as to the progress.  Running many active threads on one CPU seldom made the program faster, on the contrary, the swapping overhead frequently bogged down the machine.

However, in the last few years, the speed increase of CPUs has not been the clock speed, but the number of cores on each chip.  We are in a position now where we can get a job done much faster by splitting it between multiple threads.

Unfortunately there is still a lack of understanding of the mysteries surrounding threading.  This has caused programmers to write code that is fundamentally incorrect, not taking into account best practices for threading.

Here is an example of such incorrect code, seen recently on a web forum:

    synchronized (namedQueues) {
      try {
        namedQueues.wait(5000);
      } catch (InterruptedException ie) {
        // Can safely ignore this
      }
    }
    if (isInterrupted() || isStopped())
      break;

In this talk, we look at ten laws that can help us to write more correct threaded code.  We will now briefly summarise these ten laws:

1. The Law of the Sabotaged Doorbell
    We show how to manage the InterruptedException.  Since they are thrown by several methods in Java 5, this is useful to know.

 2. The Law of the Xerox Copier
    Concurrency faults can sometimes be avoided by making copies of important objects, instead of allowing mutability.

 3. The Law of the Overstocked Haberdashery
    Threads use up resources, even if they are not active, putting an upper limit on the number of threads in our system.  Also, when analysing threading problems, we should know what every thread is doing.  If we gloss over one thread without understanding it, we can easily miss a problem.

 4. The Law of the Blind Spot
    Fields can be cached locally by threads to improve the performance of retrieving their value.  Thus, if one thread modifies a field, the other threads might not see the updated value.

 5. The Law of the Leaked Memo
    The Java Memory Model allows the hotspot compiler to reorder statements, as long as the final result is still correct.  This can lead to some results which seem logically impossible.

 6. The Law of the Corrupt Politician
    Data races can cause the best objects to become corrupt.  They can be really difficult to detect and analyse.  In this law, we look at how we can avoid these problems.

 7. The Law of the Micromanager
    Adding synchronization to our code can cause problems with contention, where threads are waiting for each other to execute a critical section.

 8. The Law of Cretan Driving
    The rules of the road for Java threading are quite strict, but not enforced by all of the Java Virtual Machines.  Even though your code seems correct, it might still be wrong.

 9. The Law of Sudden Riches
    Sometimes a system has latent defects that are only seen every few months.  When running the system on faster hardware, these defects are amplified and can happen more frequently.

10. The Law of the Uneaten Lutefisk
    It is often possible to detect deadlocks in Java, but unfortunately it is impossible to recover cleanly. The only option is to analyse the problem that caused it and then restart the JVM.

Prerequisites: Attendees should be confident in Java SE and should have ideally worked a bit with threads before.  The talk does have something for everybody, but is mainly aimed at the intermediate to advanced developer.  There are code samples and a short demonstration.

What you will get out of the talk: You will learn several tips that will help you in writing correct threaded code in Java.

Presentation Summary:

The talk starts with a quick introduction into threading, explaining why it has become so important of late.  It then presents ten laws that we can use to write more correct threaded code in Java.

Some of the ten laws have already been described in our newsletter. Here they are again:

The Law of the Sabotaged Doorbell
http://www.javaspecialists.eu/archive/Issue146.html

The Law of the Xerox Copier
http://www.javaspecialists.eu/archive/Issue176.html

The Law of the Overstocked Haberdashery
http://www.javaspecialists.eu/archive/Issue149.html

The Law of the Blind Spot
http://www.javaspecialists.eu/archive/Issue150.html

The Law of the Leaked Memo
http://www.javaspecialists.eu/archive/Issue151.html

The Law of the Corrupt Politician
http://www.javaspecialists.eu/archive/Issue152.html

The Law of the Micromanager
http://www.javaspecialists.eu/archive/Issue155.html

The Law of Cretan Driving
http://www.javaspecialists.eu/archive/Issue156.html

The Law of Sudden Riches
http://www.javaspecialists.eu/archive/Issue159.html

The Law of the Uneaten Lutefisk
http://www.javaspecialists.eu/archive/Issue160.html

Biography:

Dr Heinz Kabutz is best known for his creation of The Java Specialists' Newsletter, read in 134 countries by 70000 Java experts.  In his newsletter, he examines advanced aspects of Java that have helped Java developers around the world to produce better code.  As someone remarked on the Sun website: "Heinz Kabutz is a hero in the Java Developer Community. His newsletters have saved companies millions by helping burgeoning and experienced programmers deliver high quality products."

In order to fund the newsletter, Heinz writes Java code on contract and runs seminars.  His Java Specialist Master Course examines ten areas of advanced Java.  It is one of the only courses specifically aimed at the seasoned Java professional.  He also teaches on Java concurrency and performance.

Heinz was invited to speak at several Sun Tech Days events: Johannesburg 2006, Athens 2007, London 2007 and Frankfurt 2007.  He is a regular speaker at Java User Groups such as JavaPolis, JavaZone, JFall and JHUG.  In addition, he has spoken several times at the Server Side conferences in USA and Europe.

**Comment by kabutz** [comment]
Note, this is a Java-centric talk.  I've written code in other languages, but have been Java programming since 1997.  The talk is usually interesting for people who know a lot about Java, but also for those who have just dabbled a bit.

**Comment by gsaslis** [comment]
wow - I can't give enough :+1: to this one!!!

**Comment by padeler** [comment]
Lots of :+1:s from me as well!!!

**Comment by eirinikp** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by JChrist** [comment]
:+1:

**Comment by kabutz** [comment]
How many :+1: do we need to run this talk?

**Comment by padeler** [comment]
There is no set number of :+1: . We are just voting for the next topic. If it gets enough votes I guess it could be the 6th meetup.

**Comment by kabitakis** [comment]
:+1:

**Comment by kabitakis** [comment]
You can also find the current results here: https://powerful-sands-5380.herokuapp.com/
The topic of meetup 06 will be decided based on the vote counts on November 19, a week after the 4th meetup.

**Comment by kabutz** [comment]
Ah right, thanks.  I've edited my previous post to not have a thumbs up in it :-)

**Comment by kabitakis** [comment]
Hey! Why not? We need your vote also! :)

**Comment by kabutz** [comment]
Oh no, I'm not a politician who votes for himself :-)

**Comment by kritsot** [comment]
:+1:

**Comment by Ivanenok** [comment]
:thumbsup:

**Comment by kabutz** [comment]
Maxim if you vote, you will have to join us in Heraklion when I do the talk :-)

**Comment by jkrithin** [comment]
:+1:

**Comment by iakotopoulos** [comment]
(y)

**Comment by iakotopoulos** [comment]
:+1:

**Comment by pappaschris** [comment]
:+1:

**Comment by Archimidis** [comment]
Amazing!!!!!!!!!!!!!!!!!!!!!!!!!!! Please be the next topic!!!!
:+1:

**Comment by sonaht** [comment]
:+1:

**Comment by kabutz** [comment]
Ha ha Archimidis, I'm pretty sure this one will happen some time next year anyway.  My talk is entertaining and mildly useful, whereas #36 is incredibly important, especially in our current situation in Greece.  So I've voted for that instead :-)

**Comment by sonaht** [comment]
@kabutz politics aside, i think you should vote for your topic as well, everybody else has done so in the past, even as an indication of willingness (which is granted in your case I am certain)

**Comment by gsaslis** [comment]
@kabutz : we have a weird voting system. You can vote for more than one topic, but not for the same topic more than once. 

Even if you don't want to vote for your own, you can still vote for some of the others as well if you like.

**Comment by kabutz** [comment]
@gsaslis indeed, you have a weird voting system - and not just amongst DevStaff.  Since I became Greek last year, we've had 5 elections: 1 regional, 1 EU, 2 general and 1 referendum.  One cross, two crosses, different names, etc.  30 different pages of representatives.  You need a university degree just to understand how to vote :-)

**Comment by kritsot** [comment]
:+1:

**Comment by kabutz** [comment]
Ha I see this talk has gone down in the popularity rankings to #6.  Maybe we can schedule it for 2019 ;-)

**Comment by kmgalanakis** [comment]
:+1:

**Comment by Hotshuk** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by rkrambovitis** [comment]
:+1:

**Comment by papoutsakos** [comment]
:+1:

**Comment by nkyriazis** [comment]
:+1:

**Comment by kabutz** [comment]
Ah I see https://powerful-sands-5380.herokuapp.com/ has stopped updating.  We have 22 votes so far

**Comment by padeler** [comment]
Yes I noticed as well. @kabitakis do you update once per day or something? 
By the way @kabutz the easier url for the analytics is: http://analytics.devstaff.gr/

**Comment by zakkak** [comment]
http://analytics.devstaff.gr should be constantly up-to-date (just refresh to get the latest)

**Comment by kabitakis** [comment]
Hi all,

We get the data using the github API directly. However, if you check this url:

https://api.github.com/repos/devstaff-crete/DevStaff-Heraklion/issues/56/comments

you'll notice that the last comment is a few hours back and our latest comments are missing. There is a delay on the github API but I don't know why. The system status says everything works well:

https://status.github.com/

Let's be patient and check again in a few hours ;)

**Comment by kabitakis** [comment]
@kabutz it seems that sometimes less is more! We’ve run into a pagination issue here. We can only get 30 results per page using the github api and we have currently made 40 (including this one).
Fun fact: for every non-voting comment someone made, you lost a chance to get another vote counted.
I will deploy a hotfix for github-analytics tonight. Maybe a quick one using '?per_page=100'
See: http://developer.github.com/v3/#pagination

**Comment by kabitakis** [comment]
The updated http://analytics.devstaff.gr/ has been deployed!

**Comment by kabutz** [comment]
It's still wrong though - should be 22 if I counted correctly.

**Comment by kabutz** [comment]
Ah, I see what happened.  kritsot voted twice and Ivanenok used the wrong thumbs up... That's ok though, since Maxim won't be joining us in Heraklion :-)

**Comment by kabitakis** [comment]
Indeed! I suppose @kritsot tries to avoid being one of the next speakers, in vain :P

**Comment by gsaslis** [comment]
Great news fellas!! We have managed to finally work out a date for this with @kabutz, around his busy travel schedule. 

This talk will be scheduled for 9th June @ 19:30. 

As an extra bonus, the date coincides with one of @kcpeppe 's courses on Crete, so he will also probably be joining us!!!

**Comment by kabutz** [comment]
I would rather suggest that I give up my slot for Kirk Pepperdine, if he is willing to give a talk.  I live on the Island, but Kirk only comes here twice a year.

**Comment by gsaslis** [comment]
As you might just have seen in your inbox, this talk has now been scheduled as a separate event to our meetup series: http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/events/229885658/ 

Please RSVP on meetup.com, so we can ensure we have a big enough room... 
Warning: most of @kabutz's talks are standing room only...

**Comment by EraserheadX** [comment]
:+1:

**Comment by sonaht** [comment]
This has been scheduled for the 27th of may.

Closing this.
