### ISSUE TITLE
Herokuapp double vote

### ISSUE THREAD

**Issue by greenman18523** [devstaff-crete/DevStaff-Heraklion#57]
The app in https://powerful-sands-5380.herokuapp.com/ counts :+1: from the same user in different responses, in the same issue discussion, separately. 
It should count up to one vote per user.

e.g. in #56 padeler appears with two votes

**Comment by sonaht** [comment]
Corrected, padeler was making a point ... I changed the icon to (thumbs UP)

**Comment by zakkak** [comment]
I think, the app is the one that should be fixed and not the comment ;)

Additionally, it would be nice to support sorting by number of votes instead of issue number.

**Comment by greenman18523** [comment]
The issue is not on how padeler was making his point, but how the app is counting votes, so we probably need to fix the app.

I don't have the source code, but if it is available I could have a look into it.

**Comment by sonaht** [comment]
Guys absolutely correct, missed the point completely and was too quick to close the issue, apologies for that .....

**Comment by kabitakis** [comment]
Hey guys!
I'll do my best with your suggestions but you can also issue a pull request. You can find our app on github: https://github.com/kabitakis/github-analytics
There is a roadmap on changes I'd like to make and any suggestions are welcome!

**Comment by zakkak** [comment]
:+1:

**Comment by zakkak** [comment]
Fixed by https://github.com/kabitakis/github-analytics/commit/77381093856a1fe7a5f96310c304c8e5caab49ba.  Please close this issue.

**Comment by kabitakis** [comment]
@zakkak thanks for the contribution!
