### ISSUE TITLE
The Intro Presentation isn't being updated

### ISSUE THREAD

**Issue by daknob** [devstaff-crete/DevStaff-Heraklion#589]
The [intro-presentation](https://github.com/devstaff-crete/DevStaff-Heraklion/tree/master/intro-presentation) folder is unmaintained for at least 2 years.

Do we want to remove it, or do we need to create a process to keep it in sync?

Personally I'd like to have access to a version controlled presentation, but I understand that it takes a bit of extra effort to maintain it.

What do you think?

**Comment by mzampetakis** [comment]
The stored [slides-devstaff-intro.html](https://github.com/devstaff-crete/DevStaff-Heraklion/blob/master/intro-presentation/slides-devstaff-intro.html) are an older template we used from slides.com. We use almost the same template nowadays but with a few improvements. So, someone can download it, import to slides.com and then update accordingly.

So, I propose to keep it there but update with a more recent template that I could prepare.

**Comment by daknob** [comment]
Awesome! Just send a PR that fixes #589 ;)
