### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#6]
Consider setting up website, e.g. using Github Pages.

**Comment by sonaht** [comment]
I have created a web server ... so there exists a page at www.devstaff.gr

Either we can keep this or use an alternative way.

**Comment by gsaslis** [comment]
hmm good question - i guess would prefer GitHub pages just because it would be one less resource to maintain / worry about.. 

what about you guys ?  /cc @padeler @kabitakis

**Comment by padeler** [comment]
I agree with @gsaslis, github pages sounds good. We can use custom-urls and set  devstaff.gr to  point to our github pages.

**Comment by kabitakis** [comment]
Github Pages are awesome as soon as we don't use a db. There are also tools to have dynamic pages without a db and http://jekyllrb.com/ is one used a lot for github pages. However, we don't even need dynamic content for the first version of our website.

**Comment by sonaht** [comment]
Agreed, lets not use this and upon creation of the Github page i will create the CNAME records for the redirection needed

**Comment by gsaslis** [comment]
anyone care to go through the GitHub Pages wizard?
(available here: https://github.com/devstaff-crete/DevStaff-Heraklion/settings )

**Comment by gsaslis** [comment]
@kabitakis - please feel free to close this once you've uploaded your www folder here, since v0 of the website is essentially ready ;)
