### ISSUE TITLE
Docker Hack Session

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#60]
Anyone interested in Docker? Let's have a hands-on experience and try to share our know-how. We should work on groups of 9 at most.
* Host: Nikos Kampitakis
* Place: [Office_12 Coworking Space](http://office12.gr/)
* Date: To be announced
* Attendees: 9
* Prerequisites: To be announced

**Comment by sonaht** [comment]
count me in, :+1:

**Comment by msti** [comment]
definitely in
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

**Comment by kabitakis** [comment]
Shall we have a first session on Thursday 26/11 20:00? We need to find a better way to organise the hack sessions. If we are ok with the date I can rename the issue to 'Docker Hack Session 151126' maybe.

**Comment by webdevgr** [comment]
:+1:

**Comment by kabitakis** [comment]
http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/events/226964686/

**Comment by maounis** [comment]
:+1: What will the hack session include?

**Comment by kabitakis** [comment]
20' to decide what the hack session will include :) It depends on the level of the participants actually.

**Comment by kabitakis** [comment]
http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/
https://github.com/devstaff-crete/docker-hack-sessions
https://gitter.im/kabitakis/docker-hack-session

And a small outcome: https://hub.docker.com/r/kabitakis/github-analytics/

We are all expecting the 2nd Docker Hack Session with emphasis on the orchestration and application containerization!
