### ISSUE TITLE
Node.js Hack Session

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#61]
Anyone interested in Node? Let's have a hands-on experience and try to share our know-how. We should work on groups of 10 at most.
* Host: Nikos Kampitakis
* Place: [Office_12 Coworking Space](http://office12.gr/)
* Date: To be announced
* Attendees: 10
* Prerequisites: To be announced

**Comment by ariel2023** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

**Comment by tzermias** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by akatopo** [comment]
:+1:

**Comment by gvre** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by stavrosAd** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

**Comment by msti** [comment]
:+1: 
1ος επιλαχών

**Comment by pappaschris** [comment]
:+1: 
2ος επιλαχών

**Comment by maounis** [comment]
:+1: 

Επισκέπτης (αν επιτρέπονται) :)

**Comment by gzografa** [comment]
:+1:

**Comment by kabitakis** [comment]
So.. let's arrange this one.
Tuesday 26/7/2016 20.00 @Office12

**Comment by akatopo** [comment]
Still in :+1:

**Comment by gvre** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by kboutsika** [comment]
👍

**Comment by pappaschris** [comment]
👍

**Comment by sstauross** [comment]
:+1:

**Comment by Archimidis** [comment]
👍 

(Μπορώ να βοηθήσω με προετοιμασία αν χρειαστεί κάτι)

**Comment by gzografa** [comment]
👍

**Comment by msti** [comment]
δεν θα μπορέσω τελικά σήμερα :(

**Comment by kabitakis** [comment]
Πολύ ωραίο session! Θα το επαναλάβουμε κ θα εξελίξουμε το app. Thanks everybody!
https://gitter.im/devstaff-crete/nodejs-hack-session

**Comment by sonaht** [comment]
@kabitakis I am closing this, let me have date info etc, for the devstaff main git page pls
