### ISSUE TITLE
Coding for youngsters

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#62]
Κάποιες έρευνες αναφέρουν άνοιγμα 500k θέσεων εργασίας για developers μέσα στην επόμενη δεκαετία, ενώ στην Αμερική η Python πήρε τη θέση των Γαλλικών σαν δεύτερη γλώσσα στα δημοτικά σχολεία (http://www.information-age.com/it-management/skills-training-and-leadership/123460073/python-overtakes-french-most-popular-language-taught-primary-schools).

Στα πλαίσια του θέματος αυτού θα εξετάσουμε με ποιούς τρόπους μπορεί ένας νέος (παιδί/έφηβος) στην Ελλάδα να μάθει προγραμματισμό, αλλά είναι επίσης σημαντικό να εξετάσουμε κάποιες δράσεις για να ενημερωθούν οι μαθητές σχολείων για το αντικείμενο αυτό, για όσα μπορούν να δημιουργήσουν κ για τις επαγγελματικές ευκαιρίες από μια τέτοια ενασχόληση.

Το παρόν θέμα δεν θα εξεταστεί σε κάποιο meetup αλλά αποτελεί ένα initiation / cause στο οποίο θα ξεκινήσουμε από κάποιες συζητήσεις κ ίσως καταλήξουμε σε κάποιες παρουσιάσεις σε τοπικά σχολεία κ στη συμμετοχή μας σε ένα μαθητικό φεστιβάλ.

**Comment by kabitakis** [comment]
I'm keeping some links here:
http://thenextweb.com/dd/2015/11/16/teach-your-kids-to-code-with-this-neat-minecraft-lesson/

**Comment by zakkak** [comment]
:+1:

**Comment by kabitakis** [comment]
We have our first invitation for a talk in a school. It's for an afternoon between 11-16/1/16. We should have a meeting the people interested in it, @zakkak, @sonaht, @maounis, @DaKnOb. Anyone else interested?

**Comment by zakkak** [comment]
We could have a short discussion in the upcoming meetup (although I am not sure I will be able to join).

**Comment by maounis** [comment]
Great!

**Comment by svelon** [comment]
Μέτρα κι εμένα, αν και δεν είμαι σίγουρος για το τι θα πρέπει να πούμε στα παιδιά...

**Comment by msti** [comment]
Η παρουσίαση μιας εκπαιδευτικής πλατφόρμας όπως το raspberry pi/arduino θα μπορούσε να τους κεντρίσει το ενδιαφέρον, αλλά δεν έχω σχετική εμπειρία.

**Comment by flouris** [comment]
Great idea, here's two interesting sites for introductory coding for kids:
https://code.org/learn
https://bitsbox.com/ (subscription-based, but has some free apps to build too)

**Comment by maounis** [comment]
:+1:  for raspberry pi/arduino

One more URL: https://www.kidscodecs.com/

**Comment by zakkak** [comment]
Although the pis and the arduinos are really cool, I don't think they are the best thing to start with.  They are essentially embedded systems.  Additionally it is much better to show to kids something they can then continue working on at their home.  Probably most of the kids do not have access to a raspberry pi or an arduino but have access to some PC.  Especially websites like https://codecombat.com/ are most likely to attract kids that are not that *geeky* to hack on an arduino/pi.

We could also use https://koding.com/ for more advanced students.

Some more URLs are available here: https://developers.google.com/blockly/about/showcase

**Comment by maounis** [comment]
@zakkak You are probably right. Maybe arduinos and Pis are better if students are visiting an event, but not so good if you are visiting students. 

Either way, for me the goal is to inspire them :)

**Comment by kabitakis** [comment]
Shall we have a meeting and discuss the topic and the planning this coming weekend? Or next week maybe? Keep in mind there are various courses for different age groups, kids 5yo and students 17yo. It's an important parameter :)

**Comment by zakkak** [comment]
I can only make it on Saturday, otherwise after the 3rd of January.

**Comment by kabitakis** [comment]
Everyone interested can join us at https://gitter.im/devstaff-crete/iGenCoders
