### ISSUE TITLE
How to organise a Hack Session

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#63]
The process we use to organise our meetups seems to work well. We can not use the same process for the hack sessions. Meetups are events arranged on a specific date that can be attended by a large number of people. Hack sessions must be proposed somehow but they can be scheduled for any date, they must be scheduled quickly and flexibly and only a few people (5-10) can participate on each session. We can have different groups of course. Any ideas on how to do this using the github issues?

**Comment by Hotshuk** [comment]
*work well. :oP

**Comment by kabitakis** [comment]
Yes, I'm here to improve my language skills, whatever that is :P

**Comment by kabitakis** [comment]
We discussed a bit about this yesterday. A possible solution would be:
* Anyone can start a Hack Session.
* It's a good idea to have found at least one other interested member before opening an issue.
* The issue MUST contain:
  * 'hack session' in its title
  * A host
  * A proposed place
  * A proposed date
  * A limit on attendees (I think 8 is a reasonable number to begin with)
  * Some prerequisites such as attendees experience, tools to be installed, tutorials to be followed before the session etc.
Any other ideas would be appreciated!

**Comment by zakkak** [comment]
Looks reasonable, maybe we should add it to CONTRIBUTING.md and build on top of it with pull requests.

**Comment by gsaslis** [comment]
:thumbsup: @zakkak 



—
Yorgos Saslis

**Comment by sonaht** [comment]
I would suggest we do these from meetup.com as well since it looks to be the same (ish) format, plus meetup.com gives the opportunity to limit attendees to a certain number, thus securing the fact that first come first serve up to the limit set, and allows waitlist.

What do u think ?

**Comment by maounis** [comment]
:+1:

**Comment by gsaslis** [comment]
@sonaht :thumbsup: 



—
Yorgos Saslis

Software Engineer

**Comment by zakkak** [comment]
So the first hack sessions was successful(?) (and #60 should be probably closed).

Is there any feedback from this first attempt?  Thinks we can improve?

Additionally could you give some more details about Office_12?  Is it open to the public (as clients)?  Their website is not very informative.

What was the arrangement about the hack session, did you pay something/somehow for the hosting of the event?  Are we welcome to perform other hack sessions there, etc.?

Sorry for my many questions :)

**Comment by zakkak** [comment]
Hmm I just noticed it was rescheduled for the 1st of Dec?

As a side note, maybe we should include hack sessions in the website as well.

**Comment by kabitakis** [comment]
Hi @zakkak,
I agree we should keep some details on each session, but I'm not sure if we should use our website, a github repo or both. I think we'll conclude on this really soon after the first sessions.

Office_12 is a small coworking office I own, however it's not in production mode yet. For now it hosts friends & family business events mostly, but it's going to be open to the public in about a month or so. The space is about 150sq.m., including an open space, a meeting room, a private office and a kitchen, and it can host up to 15 people for their day-to-day work. It's also open to the clients.

You are very welcome to perform other hack sessions there (no charge), as far as there there is availability :)

**Comment by kabitakis** [comment]
Some insights from the first completed hack session.
* 8 users/laptops is good limit to start. Above this limit, you need more advanced organisational level, more strict planning, create groups etc.
* Keep it at least 3-4 hours long, or it may be unproductive.
* We worked on 7 Digital Ocean VMs and we experienced no network issues.
* Create a Gitter channel and add the participants! You need to share data quickly.
* It helps (a lot) to have a whiteboard and a projector/large screen.
* It helps (a lot) to everybody have done their homework (examples, tutorials etc).

Related stuff:
http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/
https://github.com/devstaff-crete/docker-hack-sessions
https://gitter.im/kabitakis/docker-hack-session

**Comment by gsaslis** [comment]
wow - very interesting insights! Thanks for sharing!

**Comment by maounis** [comment]
Thanks! Very helpful!

**Comment by kabitakis** [comment]
Some notes from this issue have been moved to a new section [How to Start a Hack Session](https://github.com/devstaff-crete/DevStaff-Heraklion/blob/master/HackSessionHowTo.md). We can close this one and add more suggestions to the new section using pull requests.
Thank you all!
