### ISSUE TITLE
Hack Session: Emacs for beginners (and vim fans)

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#65]
- | -
------ | -------------
Host | @zakkak
Place | [Office_12](http://office12.gr/)
Date | Thursday 28 January @ 21:00
Limit on attendees | let's say 8 (if we are more we might split it in two sessions)

Prerequisites:
* Bring a laptop
* Install Emacs (preferably version 24.x) on that laptop or to a machine you have remote access from that laptop
* Follow the tutorial until you get bored/tired/pissed of (Opening emacs you will see an "Emacs Tutorial" link, click it or go over it with the arrows and press enter, alternatively just type `Ctrl-h t`)
* Bring questions with you ;)

Agenda:
 * org-mode (the emacs organizer)
 * god-mode (modular editing, vim-like)
 * tramp (remote file editing and much much more)
 * yasnippet
 * projectile
 * undo-tree
 * use-package
 * company-mode (auto-completion)
 * magit (a git front-end that is better than git itself)
 * mu4e (email-client)
 * which-key
 * auctex (for writing latex, if anyone is interested in it)
 * xcape and karabiner (bonus)

**Comment by zakkak** [comment]
http://codingquark.com/getting-started-with-emacs/

**Comment by vervelak** [comment]
:+1

**Comment by kabitakis** [comment]
Ok @zakkak you convinced me I should try it for a week :+1:

**Comment by Archimidis** [comment]
Well, @zakkak also convinced to give emacs a try (vim fan here) :P
:+1:

**Comment by gsaslis** [comment]
@Archimidis star wars ain't even out yet and you're already on the dark side...

**Comment by Archimidis** [comment]
Emacs is already installed on my laptop. It is now time to mess up my workflow by mixing up vim and emacs shortcuts in my head. What could possibly go wrong?

**Comment by zakkak** [comment]
Go through the tutorial, it should be smooth...  

If you fail big time try viper-mode (Vi Emulation) (I think it comes with a tutorial as well, but I am not sure).  Although I believe it should be better to wait for the hack session ;)

**Comment by Archimidis** [comment]
I've found the tutorial but didn't started yet. I think it's better to go straight into the emacs way of things.
Just schedule the hack session, already! :metal::rage2::metal:

**Comment by zakkak** [comment]
@Archimidis @kabitakis @vervelak If you are really anxious about it we can schedule it for this Thursday (or maybe Friday).  Otherwise it is going to happen in January.

**Comment by vervelak** [comment]
I'm available every evening (after 19:00)

**Comment by Archimidis** [comment]
I am available this Thursday after 19:00 as well.

**Comment by kabitakis** [comment]
Sorry guys, I can't make it for this Thursday :(

**Comment by zakkak** [comment]
OK, then let's do it next year :)

**Comment by zakkak** [comment]
So, I am back and available in the afternoons! Who else is available and when?

**Comment by Archimidis** [comment]
Good morning and a happy new year!
Let's use [doodle](http://doodle.com/) or anything else that suits you to organize the event.

**Comment by zakkak** [comment]
I created a [dudle](https://dudle.inf.tu-dresden.de/devstaff-emacs/) for the next week.

Hint: You can use the tab key and the arrows to mark your preferences a bit faster than using the mouse ;)

**Comment by kabitakis** [comment]
Hey guys!
I'm just reminding this week's other events. The mobile dev meetup on Thu 14 and the tor hack session on Tue 12. There is no actual conflict in case you arrange another hack session on one of these days, so feel free to go on in case you are not interested in one of them.

**Comment by zakkak** [comment]
@kabitakis are you still planning to join us? If so, please fill the dudle and comment here.

It looks like Friday is the best fit, but if you want to join and it doesn't suit you we can do it next week or even later.

**Comment by kabitakis** [comment]
I'm interested but unfortunately this week is a full scheduled week for me :-/

**Comment by zakkak** [comment]
OK, let's do it later then, do you believe the next week will be better?

**Comment by kabitakis** [comment]
Certainly! :)

**Comment by zakkak** [comment]
OK, so lets all fill the [dudle](https://dudle.inf.tu-dresden.de/devstaff-emacs/) like it is for the next week and not for this one.

**Comment by zakkak** [comment]
So, it looks like Thursday at 20:00 is the best. @kabitakis are you willing to host us at Office_12? I can also host us at the CSD building at UoC. What do you guys prefer?

**Comment by konchalas** [comment]
I am using [spacemacs](https://github.com/syl20bnr/spacemacs) right now, which makes a smooth transition from vim to Emacs and i find it great thus far.

My question to @zakkak  is, will you dive into Emacs Lisp during the session? I am not that interested to Emacs default key bindings since i find evil mode great, but i would to enhance my Emacs Lisp skills, which are pretty poor. Also, will you talk about org-mode? Thanks.

**Comment by zakkak** [comment]
I have heard (read actually) a lot about spacemacs and I believe it would be really nice if you would share your experience with us (maybe compare how it improves the experience over the more "vanilla" approach I will present).

Regarding Emacs Lisp, I am certainly going to explain a few things about it so that you will be able to tweak your configuration. Basically I was thinking about going through my configuration and explaining a few things. Don't expect to learn how to program in Emacs Lisp (I can't help you with that yet ;) ).

Org-mode is certainly on the list.

In general I am going to present the things I use most:

 * org-mode (the emacs organizer)
 * tramp (remote file editing and much much more)
 * yasnippet
 * projectile
 * undo-tree
 * use-package
 * company-mode (auto-completion)
 * magit (a git front-end that is better than git itself)
 * mu4e (email-client)
 * auctex (for writing latex, if anyone is interested in it)

**Comment by konchalas** [comment]
Great. I already use the majority of these. Count me in.

**Comment by kabitakis** [comment]
@zakkak absolutely we can have the session at Office_12 :)

**Comment by zakkak** [comment]
Nice, thanks @kabitakis! (It is much closer than UoC :) )

**Comment by zakkak** [comment]
@sonaht we will be waiting for you! ;)

**Comment by sonaht** [comment]
@All guys it is very unfortunate but I will not be able to make it tonight (even tho I WANT to). Sorry for the late cancelation!!!

**Comment by vervelak** [comment]
Distixos oute ego tha ta katafero simera.....

**Comment by Archimidis** [comment]
Reschedule?

**Comment by zakkak** [comment]
Well, @sonaht was coming more for the fun of it.  So I guess he doesn't mind (that much) if he misses it. @vervelak  is already using emacs with a significant part of my configuration (he was anxious), so I guess he can also skip it.

So if no one else (@Archimidis @kabitakis @konchalas) needs to reschedule I would suggest to do it tonight.

**Comment by kabitakis** [comment]
Guys k egw eimai ligo xalia giati me talairwrei kapoia iwsh edw k meres. Rescheduling would be fine but we can also leave it as is and I may not join you (depending on my condition) :-/

**Comment by zakkak** [comment]
You should better rest, so let's reschedule, this way there are more chances for @sonaht and @vervelak to join as well :)

Please edit the dudle once again to match your needs for next week

**Comment by Archimidis** [comment]
My hours are the same for next week. @kabitakis rest with netflix :P

**Comment by zakkak** [comment]
So, it looks like Thursday is the only day again. There is a slight chance I might be available a bit earlier than 21:00, so if @kabitakis agrees, we could start gathering at about 20:30, and if I make it, start earlier.  But to be safe anyone who doesn't want to wait should better come at 21:00. What do you think?

**Comment by vervelak** [comment]
I'm ok with Thursday let me know the place and the time.

**Comment by Archimidis** [comment]
Πέμπτη 21:00 είναι μια χαρά για μένα. Έχει στοιχειώσει αυτό το hack session :)

**Comment by kabitakis** [comment]
Ok για Πέμπτη στις 21.00 κ ας το αφήσουμε για 21.00 ακριβώς!

**Comment by konchalas** [comment]
Δυστυχώς εγώ δεν θα μπόρεσω να έρθω λόγο εξεταστικής. Have fun!

**Comment by vervelak** [comment]
Το μέρος πιο είναι?

**Comment by zakkak** [comment]
http://office12.gr/

**Comment by zakkak** [comment]
It looks like we have at least one new emacs user ;)

**Comment by zakkak** [comment]
PS: I forgot to tell you guys that org-mode is supported in github and gitlab as well you can use it instead of markdown for most things!

**Comment by zakkak** [comment]
About the discussion we had regarding running a shell in emacs, we just had to use `term` or `ansi-term` instead of `eshell` and `shell`. `htop` works fine. I think @Archimidis this way you can drop tmux ;)

For more info you can see this https://www.masteringemacs.org/article/running-shells-in-emacs-overview

**Comment by sonaht** [comment]
@zakkak Thank you for a very interesting session

**Comment by zakkak** [comment]
For anyone interested I started a [gitter room for Emacs](https://gitter.im/zakkak/Emacs-hack-session).
