### ISSUE TITLE
Wiki 

### ISSUE THREAD

**Issue by sonaht** [devstaff-crete/DevStaff-Heraklion#7]
I suggest that we use a wiki for the wiki, that is a wiki on the main repo

**Comment by padeler** [comment]
So a wiki under a repo other than devstaff-heraklion?

**Comment by gsaslis** [comment]
hmm.. not sure why we need that ... ?

What sort of info would you add to that wiki?

I was thinking e.g. for each meetup we'd have a page with some of the presentations maybe and some useful links, but then again, this could easily be a folder in this repo...  ; ) 

tbh, i don't really think we need a separate wiki .. : /

**Comment by sonaht** [comment]
I only mentioned that cause I believed we are in need of a wiki (due to the name chosen). IF not then disregard this as not-needed.

**Comment by gsaslis** [comment]
ok - closing this as #wontfix
