### ISSUE TITLE
[Hack Session] Playing With Time (a.k.a. which language / framework has the best support for time travel?)

### ISSUE THREAD

**Issue by gsaslis** [devstaff-crete/DevStaff-Heraklion#70]
I've been wanting to play with this for some time (yes, still stuck on Java7), so I'll be spending an afternoon over the next few days on this... Which would probably be better to do so in some company, if anyone else wants to _learn_ about this... (i.e. if you already know enough about it, I'm not sure you'd learn a lot in this session  ;)  )

I would like to implement a web app where each user can select their own timezone, and have a different timezone on the application server and different on the db server, etc... you get the point... 

the idea is to become familiar with all the new classes `Instant`, `Period`, `Duration`, `TemporalAdjusters`, `ZonedTimes`, all the formatters (of course), `add-your-own-here`, etc. 

Nothing formal.. etc. Hoping there won't be more than 5 of us, so we can easily sort out a time (pun intended) for our meeting.. ;)

**Comment by greenman18523** [comment]
:+1: 

For pre Java 8 this is very close: http://www.joda.org/joda-time/
We can also consider a "diff" between joda time and java 8 time -for those needing better/easier time handling and still stuck in pre-java 8-. (I think they are very close regarding the logic behind them since the dev of joda time was part of the JSR committee)

**Comment by gsaslis** [comment]
I see there's not a lot of interest, so I'm gonna try making this a little more generic, as I'd actually be quite interested to see the support for 'time' across languages / frameworks. (will change title accordingly)

Can anyone help me understand how well multiple timezones, arithmetic between timestamps, etc. are handled in their favourite framework / language ?

**Comment by kabitakis** [comment]
Sure! http://momentjs.com/ :heart:

**Comment by DaKnOb** [comment]
This should be an interesting hack session...

https://www.youtube.com/watch?v=-5wpm-gesOY

**Comment by Archimidis** [comment]
Don't forget these classics too:
* http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time
* http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time

Madness I tell you!

**Comment by sonaht** [comment]
Closing this. Has been inactive for years.

Please reopen if you feel this should remain.
