### ISSUE TITLE
Πανελλήνιο Συνέδριο Φοιτητών Ηλεκτρολόγων Μηχανικών και Μηχανικών Υπολογιστών (ΣΦΗΜΜΥ)

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#73]
Καλησπέρα παιδιά,

Στις 22-24 Απριλίου θα διοργανωθεί στα Χανιά το 9ο Πανελλήνιο Συνέδριο Φοιτητών Ηλεκτρολόγων Μηχανικών και Μηχανικών Υπολογιστών (ΣΦΗΜΜΥ).  
Πιστεύετε ότι θα είχε νόημα το devstaff να κάνει την εμφάνιση του με κάποια παρουσίαση;
Προσωπικά το θεωρώ μία καλή ευκαιρία να ανοίξουμε τον κύκλο μας.

Πιθανώς θα ήταν και μία ευκαιρία να γίνει bootstrap το devstaff-crete/devstaff-chania.

Για περισσότερες πληροφορίες για το Συνέδριο: http://www.sfhmmy.gr

**Comment by padeler** [comment]
Ωραία η ιδέα για το bootstrap του devstaff-chania. Ίσως να ξανά-ανοίγαμε ένα topic από τα παλιά (git?) σε μορφή workshop?

**Comment by zakkak** [comment]
Έχω στείλει ένα e-mail και περιμένω απάντηση σχετικά με το τι θέματα τους ενδιαφέρουν.  Όταν λάβω απάντηση θα ενημερώσω σχετικά.  Νομίζω πάντως πως είναι καλή η ιδέα με το git ή με κάποιο άλλο από τα παλιά θέματα.

**Comment by zakkak** [comment]
Από την απάντηση που έλαβα είναι ανοιχτοί στην θεματολογία και θα προτιμούσαν κάποια παρουσίαση σε μορφή workshop/hack-session όπου θα μπορούν όσοι θέλουν να έχουν τα λάπτοπ τους και να συμμετέχουν διαδραστικά.  Πιστεύω ότι ένα τέτοιο workshop για το git είναι εφικτό αν έχουμε 2 ώρες διαθέσιμες.  Σκεφτόμουν ένα 10λεπτο-15λεπτο εισαγωγική παρουσίαση για το devstaff-heraklion, 40-45 λεπτά εισαγωγική παρουσίαση για τα VCS, ένα σύντομο διάλειμμα και τέλος διαδραστική δημιουργία ενός project και παραδείγματα χρήσης.

**Comment by svelon** [comment]
Πολύ ωραία ιδέα, ποιοι όμως θα πάνε στα Χανιά να κάνουν τις παρουσιάσεις και να συντονίσουν το workshop; Επίσης για το workshop / hacksession τα παιδιά που έχουν ήδη εμπειρία από το Docker είπαν ότι χρειάζονται τουλάχιστον 2 - 3 ώρες και max 8 άτομα ίδιου επιπέδου... θέλει λίγο συζήτηση και πολύ καλή οργάνωση δηλαδή.

**Comment by zakkak** [comment]
> Πολύ ωραία ιδέα, ποιοι όμως θα πάνε στα Χανιά να κάνουν τις παρουσιάσεις και να συντονίσουν το workshop;

Φαντάζομαι όποιος θέλει μπορεί να πάει.  Εάν δεν υπάρχουν αρκετοί *εθελοντές* τότε προφανώς δεν μπορούμε να το κάνουμε.

> Επίσης για το workshop / hacksession τα παιδιά που έχουν ήδη εμπειρία από το Docker είπαν ότι χρειάζονται τουλάχιστον 2 - 3 ώρες και max 8 άτομα ίδιου επιπέδου... θέλει λίγο συζήτηση και πολύ καλή οργάνωση δηλαδή.

Το Docker hack session πιστεύω είναι αρκετά πιο απαιτητικό από ένα git workshop για αρχάριους.  Ιδανικά και εγώ θα προτιμούσα παραπάνω από 2 ώρες, αλλά δεν ξέρω αν γίνετε να τις έχουμε.  Η μορφή του workshop που είχα κατά νου περιελάμβανε παραδείγματα στον projector που θα πρέπει να *αναπαράγουν* οι ακροατές στον δικό τους υπολογιστή χωρίς να χρειάζεται να πάει κάποιος από πάνω τους και να τους βοηθήσει (βέβαια αυτό προϋποθέτει να έχουν εγκατεστημένα ήδη τα απαραίτητα).

**Comment by kabitakis** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by zakkak** [comment]
Για όσους ενδιαφέρονται, ενημερώθηκα ότι υπάρχουν άτομα διαθέσιμα να φιλοξενήσουν ομιλητές σε περίπτωση που δεν έχουν κάπου να μείνουν και δεν θέλουν να πληρώσουν για ξενοδοχείο.  

Ακόμη, εάν κάποιος είναι σίγουρος για την διαθεσιμότητα του εκείνες τις ημέρες και θέλει να παρουσιάσει/συμμετέχει στην παρουσίαση παρακαλείτε να προσθέσει ένα `:speaker:` σε κάποιο του σχόλιο.

**Comment by zakkak** [comment]
bump

**Comment by zakkak** [comment]
Εγώ κατά 95% δεν θα μπορέσω να πάω.  Εάν δεν ενδιαφέρεται/μπορεί κάποιος άλλος την άλλη εβδομάδα θα κλείσω το issue και θα ενημερώσω τους διοργανωτές.
