### ISSUE TITLE
Software design patterns

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#76]
In software engineering, a design pattern is a general reusable solution to a commonly occurring problem within a given context in software design. A design pattern is not a finished design that can be transformed directly into source or machine code. It is a description or template for how to solve a problem that can be used in many different situations. Patterns are formalized best practices that the programmer can use to solve common problems when designing an application or system.

Proposed by @Archimidis

**Comment by kabitakis** [comment]
:+1:

**Comment by greenman18523** [comment]
:+1:

**Comment by maounis** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by msti** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by agougousis** [comment]
I really can't see how such a topic can fit in an hourly speech, since you cannot teach (or present) a pattern without extensive code examples. Anyway...upvoting!
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by hrysakis** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by pappaschris** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by nikos90** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by npapnet** [comment]
:+1: Also I agree with @agougousis  that this is a subject for many sessions. 
Maybe:
- a  short intro and then 
- Creational, 
- Structural 
- Behavioral

**Comment by Pepemakis** [comment]
:+1:

**Comment by nkyriazis** [comment]
:+1:

**Comment by gvre** [comment]
:+1:

**Comment by nipapada** [comment]
:+1

**Comment by zakkak** [comment]
:-1:

**Comment by VaggeliC** [comment]
:+1:

**Comment by sonaht** [comment]
This topic will be frozen until we get enough people to present it. If you feel that you can help (co)presenting this, just comment further as well as adding the "**speaker**" icon

**Comment by DaKnOb** [comment]
![Mic Drop](http://www.androidcentral.com/sites/androidcentral.com/files/article_images/2016/04/mic-drop-gif.gif) 😜

**Comment by sonaht** [comment]
Closing this as it is the next scheduled meetup for the 12/05/2016
