### ISSUE TITLE
Drupal CMS

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#81]
I really hope @msti will coordinate this topic :)

**Comment by sonaht** [comment]
:+1:

**Comment by msti** [comment]
@kabitakis sure! 
I will come up with a list of possible topics later
:+1:

**Comment by maounis** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

**Comment by kabitakis** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by msti** [comment]
Drupal is a robust CMS/CMF (content management system/framework) that empowers developers to rapidly create web applications. It is built on top of the LAMP (linux, apache, mysql php) stack and is powering many highly prestigious sites.

I propose a crash course talk and workshop that will explain the basics, demystify all the daunting concepts and provide some building experience: 

- Basic installation, concepts and terminology, user/content management, site building with contributed modules and best practices.
- Drupal architecture. The hooking mechanism. Code examples. 
- Putting it all together: Quick creation of a real life web app.

If you find this topic interesting, then thumbs up: <code>:+1:</code>

Anyone interested in talking, please add the <code>:sound:</code> icon
:sound:

**Comment by padeler** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by hariskouk** [comment]
😃

**Comment by DimitrisAgelakis** [comment]
:+1:

**Comment by gvre** [comment]
:+1:

**Comment by skananitos** [comment]
:+1:

**Comment by hrysakis** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by markop** [comment]
:+1:

**Comment by sonaht** [comment]
This is merged in #160
