### ISSUE TITLE
React.js: The hottest JS lib for building UIs

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#82]
- React components
- Virtual DOM
- Data flow
- JSX
- Routing
- Components lifecycle
- Isomorphic development
- Just a touch o flux and redux

**Comment by Archimidis** [comment]
:+1:

**Comment by kormic** [comment]
:+1: yes yes yes!!!

**Comment by ariel2023** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by nikos90** [comment]
:+1:

**Comment by JChrist** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by sugarenia** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by skananitos** [comment]
:+1:

**Comment by AndronikiEnartia** [comment]
:+1:

**Comment by Pepemakis** [comment]
👍

**Comment by kboutsika** [comment]
👍

**Comment by kritsot** [comment]
👍

**Comment by gzografa** [comment]
:+1:

**Comment by George-Aidonidis** [comment]
:+1:

**Comment by AndronikiEnartia** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by tzanis** [comment]
👍

**Comment by sksksksk** [comment]
+1

**Comment by sksksksk** [comment]
:+1:

**Comment by AndronikiEnartia** [comment]
+1

**Comment by AndronikiEnartia** [comment]
👍

**Comment by sonaht** [comment]
:+1:

**Comment by msti** [comment]
👍

**Comment by agougousis** [comment]
:+1:

**Comment by sifalios** [comment]
:+1:

**Comment by npasadakis** [comment]
+1

**Comment by npasadakis** [comment]
:+1:

**Comment by gsaslis** [comment]
Ok, this looks to be the next meetup topic IF we have speakers. 

@kabitakis are you a :speaker: here?
Anyone else??? (Please add a new comment, so we receive updates ;) )

**Comment by kabitakis** [comment]
Hey! Yes, I'm a 🔈 for this one. I suppose this one goes for November or even December.

**Comment by gsaslis** [comment]
Well, we need a September topic, and we don't have speakers for either Django or Sass that have more votes. 

If we don't have speakers for this one either we'll probably just move to the next one. Anyone else care to help?

**Comment by gsaslis** [comment]
http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/events/235052750/
