### ISSUE TITLE
Global Game Jam RETHYMNO 2016

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#83]
Το Global Game Jam αποτελεί το μεγαλύτερο παγκόσμιο γεγονός δημιουργίας παιχνιδιών το οποίο πραγματοποιείται τις ίδιες ημερομηνίες και την ίδια ώρα (τοπική) σε όλο τον κόσμο.

Κατά την διάρκεια της διοργάνωσης (48 ώρες), οι συμμετέχοντες χωρίζονται σε ομάδες (έως 4 άτομα) και καλούνται να φτιάξουν από το μηδέν ένα video game ή ένα board game (επιτραπέζιο) πάνω σε συγκεκριμένη θεματική η οποία τους ανακοινώνεται κατά την έναρξη και είναι κοινή για όλες τις χώρες. Κατά την λήξη της διοργάνωσης, όλα τα παιχνίδια που έχουν φτιαχτεί παραδίδονται στους διοργανωτές και αναρτώνται στην κεντρική σελίδα του Global Game Jam.

Η συμμετοχή στο Global Game Jam είναι δωρεάν και το μόνο που χρειάζεται είναι οι ενδιαφερόμενοι να συμπληρώσουν την φόρμα συμμετοχής που είναι διαθέσιμη στα παρακάτω links:
www.ggjrethymno.weebly.com
http://globalgamejam.org/2016/jam-sites/global-game-jam-rethymno
http://goo.gl/forms/Qd1LXXqeyx
Facebook: www.facebook.com/ggjrethymno/
Twitter: @GGJRETHYMNO

**Comment by sonaht** [comment]
I am closing this:

"Το Global Game Jam Rethymno θα ξεκινήσει την Παρασκευή 29 Ιανουαρίου 2016 και θα ολοκληρωθεί την Κυριακή 31 Ιανουαρίου 2016."
