### ISSUE TITLE
NoSQL

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#84]
NoSQL Databases are becoming a hot topic in Computer Science and Software Engineering. Currently we collect, store and process a lot of data. Relational Databases don't seem to be able to keep up with that. Many of us already moved to NoSQL databases or want to do it soon. 

I propose a talk on NoSQL databases, their types, some basic information on how they work and some tips we may have for both administration as well as development. 

If you're interested in this topic please comment below including the `:+1:` icon. If you posses enough knowledge and are willing to speak about this topic, please include the `:speaker:` icon.

**Comment by DaKnOb** [comment]
:+1:

**Comment by msti** [comment]
:+1:

**Comment by Archimidis** [comment]
:+1:

I would like to help here, if needed that is.

**Comment by DaKnOb** [comment]
Since only few people seen it, I believe we can start "collecting" speakers. Please add the `:speaker:` emoji.

:speaker:

**Comment by gvre** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by maounis** [comment]
:+1:

**Comment by eirinikp** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by sonaht** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by sbehnsen** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by DimitrisAgelakis** [comment]
:+1:

**Comment by skananitos** [comment]
I can contribute with some notes :speaker:

**Comment by sstauross** [comment]
:+1:

**Comment by agougousis** [comment]
:+1:

**Comment by markpapadakis** [comment]
:+1: :speaker:

**Comment by JChrist** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by ManosGEM** [comment]
:+1:

**Comment by mikedi** [comment]
:+1:

**Comment by AndronikiEnartia** [comment]
:+1:

**Comment by Pepemakis** [comment]
👍

**Comment by Hotshuk** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by sonaht** [comment]
We seem to be out of speakers for this one... If you feel that you can copresent this let me know, so we can work this out before tomorrow's (12/05/2016) meetup.
TY

**Comment by nkvorn** [comment]
:speaker:

Hi, I believe I can prepare a presentation for NoSQL. I have some parts ready from a recent relevant presentation I made so with some extra work I can have something decent to show.

If you are interested just inform me about week ahead the presentation since it is a vast subject!

Thank You

**Comment by sonaht** [comment]
Pls get into gitter: https://gitter.im/devstaff-crete/DevStaff-Heraklion i
get in touch with @DaKnOb and @rkrambovitis  who will co presenting the
next meetup on NoSQL.

thanks

Θ.
