### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by DaKnOb** [devstaff-crete/DevStaff-Heraklion#85]
The Onion Router (or Tor for short) is a P2P network that not only allows anonymous browsing of the Internet, but also supports hidden services, special domain names that are completely anonymous, both for the website as well as for the user. 

In this topic we can see how Tor works, how it gains its anonymity, as well as how to setup a hidden service and run our website and/or web app / service there, in addition to the Internet version. 

If you feel like we should also include some more content, feel free to say it in the comments below. If you have experience on this subject and want to be a speaker, just comment `:speaker:`. If you like this topic and want to view it in one of the upcoming meet ups, go ahead and comment `:+1:`.

**Comment by DaKnOb** [comment]
:+1: :speaker:

**Comment by maounis** [comment]
Great topic.

On the Docker side, Jessie Frazelle was a great resource for me:

How to Route Traffic through a Tor Docker container:
https://blog.jessfraz.com/post/routing-traffic-through-tor-docker-container/

Tor + Docker = Anonymous ♥:
https://www.youtube.com/watch?v=4u8egQ7rvMk

:+1:

**Comment by DaKnOb** [comment]
@maounis I was watching the video an hour before submitting the topic. And then I watched the 32C3 talk about Hidden Services..

**Comment by gsaslis** [comment]
:+1:

**Comment by msti** [comment]
:+1: 

Onion Pi for creating an anonymous wi-fi hotspot https://learn.adafruit.com/onion-pi/overview

Do you think we can broaden the scope so that it includes more options for staying anonymous online? (eg pgp/gpg,  vpns, cryptocurrency) ?

**Comment by eirinikp** [comment]
:+1:

**Comment by EraserheadX** [comment]
:+1:

**Comment by maounis** [comment]
@DaKnOb Ha ha, actually I was inside the presentation room that day. It took place at DockerCon in Barcelona :)

**Comment by tzermias** [comment]
:+1:  Great topic!

**Comment by padeler** [comment]
:+1:

**Comment by DaKnOb** [comment]
@msti I don't think we'll have the time but maybe it would be good to suggest that as another topic.

**Comment by estavrak** [comment]
:+1:
:speaker: 
:heart:

**Comment by sonaht** [comment]
:+1:

**Comment by estavrak** [comment]
![selection_052](https://cloud.githubusercontent.com/assets/13367693/12178903/beabdeac-b57c-11e5-842a-3727a6d72664.png)

**Comment by DaKnOb** [comment]
Ironically I started an(other) Exit Node yesterday..

**Comment by pappaschris** [comment]
:+1:

**Comment by npapnet** [comment]
+1

**Comment by kmgalanakis** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by Pepemakis** [comment]
:+1:

**Comment by npasadakis** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by ManosGEM** [comment]
+1:

**Comment by ManosGEM** [comment]
:+1:

**Comment by flouris** [comment]
:+1:

**Comment by Pepemakis** [comment]
👍

**Comment by webdevgr** [comment]
:+1:

**Comment by markop** [comment]
:+1:

**Comment by sonaht** [comment]
Closing this as it has been planned for Thursday, March 9, 2017
