### ISSUE TITLE
Functional Programming in PHP

### ISSUE THREAD

**Issue by kapolos** [devstaff-crete/DevStaff-Heraklion#87]
Καλησπέρα σας,

I am amazed that I hadn't heard about devstaff-heraklion earlier - better late than never I guess, Ι will be happy to meet you in person at the upcoming meeting :)

My strong expertise is in `PHP`, `Ember.js` and `Node`. I thought I'd kick-start my topic suggestions with the thing that has been on my mind the most in the recent months: **Functional Programming in PHP**. 

Functional style practitioners in PHP have been historically a tiny group, mainly for 2 reasons - the language constructs impose a heavy boilerplate/verbosity penalty and the infamous aversion to change in the PHP community - remember the great procedural vs OOP flame wars? ;)

Great thing is that with PHP 5.6+, things have started to change and there now exist a healthy amount of good libraries that make functional programming in PHP fun and easy.

So here is what I suggest to cover, the depth of each dependent on the overall time:
- What Functional Programming is
- What FP provides to you as a programmer (benefits)
- The real reason why you will fall in love with FP (fun)
- A walk-through of the major concepts in FP
- An overview of the available PHP FP libraries 
- A practical guide to start embracing FP in PHP with [Pramda](https://github.com/kapolos/pramda)

:loud_sound:

**Comment by zakkak** [comment]
Hi John/Gianni,

I am not sure the time is enough to cover all these.  Maybe you could focus on the FP part in a talk and organize a Hack Session for the FP in PHP part.

:+1:

**Comment by kapolos** [comment]
Great idea with the Hack Session @zakkak ! Covering the theoretical aspect in a talk and then getting our hands dirty with actual coding sounds great :+1:

**Comment by nikos90** [comment]
:+1:

**Comment by padeler** [comment]
:+1:

**Comment by sonaht** [comment]
liking this :+1:

**Comment by sonaht** [comment]
@kapolos Welcome to the devstaff community. By the way if you feel like talking about this specific subject, pls amend your post including the ":loud_sound:" (without the quotes) indicating the ability to talk about this. As far as a hack session is concerned go ahead feel free to organise one... I am confident that             people will flock in !!!

**Comment by kapolos** [comment]
@sonaht Icon added, thanks for letting me know. :+1: 

Regarding the hack session, do you mean the same as @zakkak ? I.e. going over the Functional Programming concepts on a talk and then doing FP in PHP specifically at the hack session? Or should the hack session include the theoretical overview as well?

**Comment by sonaht** [comment]
Well a hack session should probably follow the meetup but given the subjects already chosen it seems that it might take some time for the meetup to happen. So in all fairness "a number" of hack sessions might happen to cover these...(just a suggestion)

Hack sessions by default can not have too many people invited (or taking part) as they need to be hands on sessions. A series of such hack sessions will most definitely create a trend, ie a solid group that will take this to a higher level eventually by sharing knowledge as well as advancing it.

In any case the more people voting this the better. On the next meetup talk to people about it... lets see what happens

**Comment by eirinikp** [comment]
:+1:

**Comment by kritsot** [comment]
:+1:

**Comment by ariel2023** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by StVak** [comment]
+1

**Comment by npapnet** [comment]
:+1:

**Comment by kmgalanakis** [comment]
:+1:

**Comment by kboutsika** [comment]
:+1:

**Comment by svelon** [comment]
:+1:

**Comment by sonaht** [comment]
This was covered... see meetup 31. Closing this
