### ISSUE TITLE
Tor hack session

### ISSUE THREAD

**Issue by sonaht** [devstaff-crete/DevStaff-Heraklion#88]
I am seriously interested in this subject and I want to, will actually organise, a hack session on this soon.

Point of this will be a seriously fast knowledge transfer.

I know that @DaKnOb will be interested in actually providing all info, and actually allowing us to brain pick

**Comment by maounis** [comment]
:+1: Hold me a seat over there!

**Comment by DaKnOb** [comment]
:speaker: here, the claims made by @sonaht are true.. :-)

We'll be talking about Tor and its architecture, anonymity, etc.

Topics:

* How Tor works (routing)
* Relay Nodes
* Exit Nodes
* Bridges
* Setting up a node
* Hidden Services
* Tor Browser
* Anything else you want

**Comment by msti** [comment]
:+1:

**Comment by nikos90** [comment]
:+1:

**Comment by zakkak** [comment]
:+1:  Although your hack session does not comply to the guidelines @sonaht ;)

**Comment by DaKnOb** [comment]
@zakkak It is a work in progress.

**Comment by zakkak** [comment]
WIPs are not allowed upstream!

**Comment by sonaht** [comment]
@zakkak ???

**Comment by Archimidis** [comment]
:+1:

**Comment by zakkak** [comment]
@sonaht just keeding ;)

**Comment by gvre** [comment]
:+1:

**Comment by tzermias** [comment]
:+1:

**Comment by DaKnOb** [comment]
Probably **one** more seat left. Who's interested?

**Comment by konchalas** [comment]
:+1:  I am interested

**Comment by DaKnOb** [comment]
Please check [here](http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/events/227937496/?rv=co1) as we add more information.

**Comment by sonaht** [comment]
It seems that I have made a mistake and I created a meetup session as well, which I hoped would have remained unpublished (which to me means that no one sees it)...

People have rsvp'ed there as well as voted here. I will keep this one here since it was created first.

I know that there ia an extra person coming but I assume this will be it.

I will inform on place and time...but it looks like Tuesday at 20.00 at Office_12 Coworking Space.

Stay tuned

**Comment by vervelak** [comment]
:+1:

**Comment by sonaht** [comment]
Guys it is fixed...

DATE&TIME: Tuesday 12/01/2016, at 20.00. 
PLACE: Office_12 Coworking Space, Μιχαήλ Ηλιάδη 12, Ηράκλειο

PRESENTER: @DaKnOb 

ATTENDEES: @gsaslis , @maounis, @zakkak, @sonaht, @msti, @nikos90, @Archimidis, @gvre, @tzermias, @konchalas, @vervelak,

**Comment by kabitakis** [comment]
:+1:

**Comment by sonaht** [comment]
A very interesting night yesterday, with a lot of info coming in, many many questions as diverse as possible with equally interesting answers.

A final question remains as to if devstaff as a community would get involved into running nodes of any kind, and that shall be discussed in a future general get together or even a specific one.

Thank you @DaKnOb for the effort !!!

**Comment by DaKnOb** [comment]
It was my pleasure. As I have *some* experience with running Tor Nodes, I believe I could help technically but would love to show someone as well..
