### ISSUE TITLE
ESPA hack session (business oriented session)

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#89]
Even though I don't believe a developer should consider making business in Greece anymore, because of the unviable taxation model (earn 10, live with 2), there are some ESPA funding programs that are suppose to be proclaimed for SMEs. I make a lot of research for myself on this subject anyway and I could share my knowledge and experience in case some people are interested. It's not actually a hack session, it's an ad-hoc event, a presentation of the upcoming programs and best practices.

**Comment by msti** [comment]
I would definitely interested in this :+1: 
Thx Nikos

**Comment by zakkak** [comment]
Me too :+1:

**Comment by sonaht** [comment]
:+1: interested as well !!!

**Comment by Archimidis** [comment]
:+1:

**Comment by DaKnOb** [comment]
:+1:

**Comment by maounis** [comment]
:+1:

**Comment by sstauross** [comment]
:+1:

**Comment by gzografa** [comment]
:+1:

**Comment by webdevgr** [comment]
:+1:

**Comment by gvre** [comment]
:+1:

**Comment by npasadakis** [comment]
Count me in

**Comment by agougousis** [comment]
:+1:

**Comment by zakkak** [comment]
http://www.antagonistikotita.gr/epanek/prokirixeis.asp

**Comment by padeler** [comment]
nice :+1:

**Comment by hrysakis** [comment]
:+1:

**Comment by kabitakis** [comment]
Hello! I created a gitter channel about this: https://gitter.im/devstaff-crete/ESPA
Please join and let's arrange the hack session anytime soon (or just keep it virtual)
Cheers!

**Comment by kabitakis** [comment]
I'm closing this one and we could open a new one if necessary.
