### ISSUE TITLE
Docker Hack Session volume 2

### ISSUE THREAD

**Issue by kabitakis** [devstaff-crete/DevStaff-Heraklion#91]
It's time!
* Host: Nikos Kampitakis
* Place: [Office_12 Coworking Space](http://office12.gr/)
* Date: Tuesday 19/1/16 20:00
* Attendees: 10
* Prerequisites:
  * Docker Hack Session vol.1 material
  * Let's decide on others! Docker compose? Swarm? Tutum? Rancher? Volumes?

http://www.meetup.com/DevStaff-A-Developer-Community-Gathering-In-Crete/events/228054404/

**Comment by Archimidis** [comment]
:+1:

**Comment by maounis** [comment]
:+1:

**Comment by sonaht** [comment]
:+1: 

I suggest docker swarm, compose, and volumes. This way we make a good approach to generic tools before we go to otherwise available ones.

The API should go after that, with all the other tools that make use of this

**Comment by DaKnOb** [comment]
:+1:

**Comment by konchalas** [comment]
:+1: 
I didn't come to the first session, but i know a bit about docker. I hope i can keep up with you guys.

**Comment by msti** [comment]
:+1:

**Comment by gsaslis** [comment]
:thumbsup:

-- 
Yorgos Saslis
Software Engineer

**Comment by gvre** [comment]
:+1:
