### ISSUE TITLE
Document library

### ISSUE THREAD

**Issue by msti** [devstaff-crete/DevStaff-Heraklion#92]
I spent a good amount of time today writing an agreement for a service I plan to provide for a client. This document may be useful to people planning to provide a similar service. 

We can create a library of generic documents (templates) that people can download and adjust to their specific use cases. We can use store the documents at github and use google docs for suggesting edits.

**Comment by Archimidis** [comment]
That would be awesome! This will definitely help people like me that are noobs to these kind of stuff.

**Comment by kabitakis** [comment]
@msti I love your idea!
:+1:

**Comment by sonaht** [comment]
It is a great idea... I just hope people in general are willing to share. :+1:

**Comment by maounis** [comment]
:+1: A very good thought!

**Comment by DaKnOb** [comment]
:+1: 

I can share my Tor Exit responses to Abuse E-Mails. They can be useful to people who are willing to setup such node. Hopefully if everyone replies to these e-mails in the same manner, they will eventually limit them.. :-)

**Comment by sonaht** [comment]
Well a document library can have all sorts of "documents", just need a pretty good categorisation, by all means go for it

**Comment by kormic** [comment]
:+1: Awesome!!!

**Comment by padeler** [comment]
great idea @msti :+1:

**Comment by sstauross** [comment]
:+1:

**Comment by zakkak** [comment]
Related:

 * [Contract killer](https://gist.github.com/malarkey/4031110)
 * [Legal Markdown](https://github.com/compleatang/legal-markdown)
 * [Open source legal documents for developers](http://www.docracy.com/topic/1e6bi5l90z/open-source-legal-documents-for-developers?startPdfDownload=false

I also remember coming across a github repository specifically tailored to contracts but I can't find it.

**Comment by msti** [comment]
@sonaht  Sharing is an issue. If people are not willing to share we can start with some links like those posted above.

I am mostly looking for simple docs that a web developer can understand and alter. The Contract killer posted above rocks! \m/ Thanks @zakkak
