### ISSUE TITLE
Hack Summit, Virtual Event and Hackathon @ February 22nd-25th, 2016

### ISSUE THREAD

**Issue by zakkak** [devstaff-crete/DevStaff-Heraklion#98]
A Virtual Event for Developers.

Featuring programming language creators, open-source contributors, and thought leaders!

The largest virtual conference in history!
The largest programming conference in history!
The largest hackathon in history!

https://hacksummit.org
https://koding.com/Hackathon

**Comment by sonaht** [comment]
@zakkak can we close this if not needed anymore pls ?
